openapi: 3.0.1
info:
  title: Advanced Voice Services Operations
  description: This service domain operates the telephone channel infrastructure, including the IVR and any other automated devices as appropriate. This includes handling default routing rules and intra-day/session adjustments to deal with peak load or other operational variations
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/AdvancedVoiceServicesOperations/10.0.0
paths:
  /AdvancedVoiceServicesOperations/Initiate:
    post:
      tags:
      - CR - VoiceChannelOperatingSession
      summary: InCR Initiate the voice channel service
      description: InCR Initiate the voice channel service
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/VoiceChannelOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoiceChannelOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AdvancedVoiceServicesOperations/{advancedvoiceservicesoperationsId}/Update:
    put:
      tags:
      - CR - VoiceChannelOperatingSession
      summary: UpCR Update the voice access service menu during the session
      description: UpCR Update the voice access service menu during the session
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/AdvancedVoiceServicesOperationsID'
      requestBody:
        $ref: '#/components/requestBodies/VoiceChannelOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoiceChannelOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AdvancedVoiceServicesOperations/{advancedvoiceservicesoperationsId}/Request:
    put:
      tags:
      - CR - VoiceChannelOperatingSession
      summary: RqCR Report an issue with the production service
      description: RqCR Report an issue with the production service
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/AdvancedVoiceServicesOperationsID'
      requestBody:
        $ref: '#/components/requestBodies/VoiceChannelOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoiceChannelOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AdvancedVoiceServicesOperations/{advancedvoiceservicesoperationsId}/Retrieve:
    get:
      tags:
      - CR - VoiceChannelOperatingSession
      summary: ReCR Retrieve details and statistics relating to a session
      description: ReCR Retrieve details and statistics relating to a session
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/AdvancedVoiceServicesOperationsID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoiceChannelOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AdvancedVoiceServicesOperations/{advancedvoiceservicesoperationsId}/Inbound/Initiate:
    post:
      tags:
      - BQ - Inbound
      summary: InBQ Execute an inbound voice connection
      description: InBQ Execute an inbound voice connection
      operationId: InitiateInbound
      parameters:
      - $ref: '#/components/parameters/AdvancedVoiceServicesOperationsID'
      requestBody:
        $ref: '#/components/requestBodies/InitiateInboundRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateInboundResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AdvancedVoiceServicesOperations/{advancedvoiceservicesoperationsId}/Inbound/{inboundId}/Retrieve:
    get:
      tags:
      - BQ - Inbound
      summary: ReBQ Retrieve details about an inbound voice connection
      description: ReBQ Retrieve details about an inbound voice connection
      operationId: RetrieveInbound
      parameters:
      - $ref: '#/components/parameters/AdvancedVoiceServicesOperationsID'
      - $ref: '#/components/parameters/InboundID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveInboundResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AdvancedVoiceServicesOperations/{advancedvoiceservicesoperationsId}/Outbound/Initiate:
    post:
      tags:
      - BQ - Outbound
      summary: InBQ Execute an outbound voice connection
      description: InBQ Execute an outbound voice connection
      operationId: InitiateOutbound
      parameters:
      - $ref: '#/components/parameters/AdvancedVoiceServicesOperationsID'
      requestBody:
        $ref: '#/components/requestBodies/InitiateOutboundRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateOutboundResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AdvancedVoiceServicesOperations/{advancedvoiceservicesoperationsId}/Outbound/{outboundId}/Retrieve:
    get:
      tags:
      - BQ - Outbound
      summary: ReBQ Retrieve details about an outbound voice connection
      description: ReBQ Retrieve details about an outbound voice connection
      operationId: RetrieveOutbound
      parameters:
      - $ref: '#/components/parameters/AdvancedVoiceServicesOperationsID'
      - $ref: '#/components/parameters/OutboundID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveOutboundResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    VoiceChannelOperatingSession:
      type: object
      properties:
        AdvancedVoiceServicesOperationsServiceMenu:
          type: string
        VChannelServiceSessionStatistics:
          type: string
        VChannelServiceSessionReportType:
          type: string
        VChannelServiceSessionReport:
          type: string
        VChannelProductionIssueRecord:
          type: string
        EmployeeOrBusinessUnitReference:
          type: object
        CustomerContactRecordReference:
          type: object
        ProductionIssueType:
          type: string
        ProductionIssueDescription:
          type: string
        ProductionIssueDiagnosis:
          type: string
        ProductionIssueResolutionTask:
          type: string
        ProductionIssueStatus:
          type: string
    Inbound:
      type: object
      properties:
        VChannelDeviceReference:
          type: object
        VChannelDevicePropertyValue:
          type: string
        VChannelInboundConnectionStartTime:
          type: string
        VChannelInboundConnectionDuration:
          type: string
        VChannelInboundConnectionContactReference:
          type: object
    Outbound:
      type: object
      properties:
        Employee/BusinessUnitReference:
          type: object
        CustomerContactRecordReference:
          type: object
        CustomerSessionDialogueRecord:
          type: string
        VChannelCustomerDeviceReference:
          type: object
        VChannelOutboundConnectionStartTime:
          type: string
        VChannelOutboundConnectionDuration:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    InitiateInboundRequest:
      type: object
      properties:
        VoiceChannelOperatingSession:
          type: object
          properties:
            AdvancedVoiceServicesOperationsServiceMenu:
              type: string
        Inbound:
          type: object
          properties:
            VChannelDeviceReference:
              type: object
            VChannelDevicePropertyValue:
              type: string
            VChannelInboundConnectionContactReference:
              type: object
    InitiateInboundResponse:
      type: object
      properties:
        VoiceChannelOperatingSession:
          type: object
          properties:
            VChannelServiceSessionStatistics:
              type: string
        Inbound:
          type: object
          properties:
            VChannelInboundConnectionStartTime:
              type: string
            VChannelInboundConnectionDuration:
              type: string
    RetrieveInboundResponse:
      type: object
      properties:
        VoiceChannelOperatingSession:
          type: object
          properties:
            AdvancedVoiceServicesOperationsServiceMenu:
              type: string
            VChannelServiceSessionStatistics:
              type: string
        Inbound:
          type: object
          properties:
            VChannelDeviceReference:
              type: object
            VChannelDevicePropertyValue:
              type: string
            VChannelInboundConnectionStartTime:
              type: string
            VChannelInboundConnectionDuration:
              type: string
            VChannelInboundConnectionContactReference:
              type: object
    InitiateOutboundRequest:
      type: object
      properties:
        VoiceChannelOperatingSession:
          type: object
          properties:
            VChannelServiceSessionStatistics:
              type: string
        Outbound:
          type: object
          properties:
            EmployeeOrBusinessUnitReference:
              type: object
            CustomerContactRecordReference:
              type: object
            CustomerSessionDialogueRecord:
              type: string
            VChannelCustomerDeviceReference:
              type: object
    InitiateOutboundResponse:
      type: object
      properties:
        VoiceChannelOperatingSession:
          type: object
          properties:
            VChannelServiceSessionStatistics:
              type: string
        Outbound:
          type: object
          properties:
            CustomerSessionDialogueRecord:
              type: string
            VChannelOutboundConnectionStartTime:
              type: string
            VChannelOutboundConnectionDuration:
              type: string
    RetrieveOutboundResponse:
      type: object
      properties:
        VoiceChannelOperatingSession:
          type: object
          properties:
            VChannelServiceSessionStatistics:
              type: string
        Outbound:
          type: object
          properties:
            EmployeeOrBusinessUnitReference:
              type: object
            CustomerContactRecordReference:
              type: object
            CustomerSessionDialogueRecord:
              type: string
            VChannelCustomerDeviceReference:
              type: object
            VChannelOutboundConnectionStartTime:
              type: string
            VChannelOutboundConnectionDuration:
              type: string
  parameters:
    AdvancedVoiceServicesOperationsID:
      name: advancedvoiceservicesoperationsId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    InboundID:
      name: inboundId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    OutboundID:
      name: outboundId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    VoiceChannelOperatingSession:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VoiceChannelOperatingSession'
    InitiateInboundRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateInboundRequest'
    InitiateOutboundRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateOutboundRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
