openapi: 3.0.1
info:
  title: Asset And Liability Management
  description: The unit overseeing the  banks asset & liability policies and position
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/AssetAndLiabilityManagement/10.0.0
paths:
  /AssetAndLiabilityManagement/{assetandliabilitymanagementId}/Update:
    put:
      tags:
      - CR - AssetAndLiabilityPortfolioStrategy
      summary: UpCR Update aspects of the bank's asset and liability policies
      description: UpCR Update aspects of the bank's asset and liability policies
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/AssetAndLiabilityManagementID'
      requestBody:
        $ref: '#/components/requestBodies/AssetAndLiabilityPortfolioStrategy'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetAndLiabilityPortfolioStrategy'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AssetAndLiabilityManagement/{assetandliabilitymanagementId}/Request:
    put:
      tags:
      - CR - AssetAndLiabilityPortfolioStrategy
      summary: RqCR Request manual intervention in the policies
      description: RqCR Request manual intervention in the policies
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/AssetAndLiabilityManagementID'
      requestBody:
        $ref: '#/components/requestBodies/AssetAndLiabilityPortfolioStrategy'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestAssetAndLiabilityPortfolioStrategyResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AssetAndLiabilityManagement/{assetandliabilitymanagementId}/Retrieve:
    get:
      tags:
      - CR - AssetAndLiabilityPortfolioStrategy
      summary: ReCR Retrieve details about the bank's asset and liability policies
      description: ReCR Retrieve details about the bank's asset and liability policies
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/AssetAndLiabilityManagementID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetAndLiabilityPortfolioStrategy'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AssetAndLiabilityManagement/{assetandliabilitymanagementId}/TransactionAlignment/Create:
    post:
      tags:
      - BQ - TransactionAlignment
      summary: CrBQ Create a proposed transaction submission under the policy
      description: CrBQ Create a proposed transaction submission under the policy
      operationId: CreateTransactionAlignment
      parameters:
      - $ref: '#/components/parameters/AssetAndLiabilityManagementID'
      requestBody:
        $ref: '#/components/requestBodies/CreateTransactionAlignmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTransactionAlignmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AssetAndLiabilityManagement/{assetandliabilitymanagementId}/TransactionAlignment/{transactionalignmentId}/Request:
    put:
      tags:
      - BQ - TransactionAlignment
      summary: RqBQ Request manual intervention during an assessment
      description: RqBQ Request manual intervention during an assessment
      operationId: RequestTransactionAlignment
      parameters:
      - $ref: '#/components/parameters/AssetAndLiabilityManagementID'
      - $ref: '#/components/parameters/TransactionAlignmentID'
      requestBody:
        $ref: '#/components/requestBodies/RequestTransactionAlignmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestTransactionAlignmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /AssetAndLiabilityManagement/{assetandliabilitymanagementId}/TransactionAlignment/{transactionalignmentId}/Retrieve:
    get:
      tags:
      - BQ - TransactionAlignment
      summary: ReBQ Retrieve details about a transaction alignment assessment
      description: ReBQ Retrieve details about a transaction alignment assessment
      operationId: RetrieveTransactionAlignment
      parameters:
      - $ref: '#/components/parameters/AssetAndLiabilityManagementID'
      - $ref: '#/components/parameters/TransactionAlignmentID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveTransactionAlignmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    AssetAndLiabilityPortfolioStrategy:
      type: object
      properties:
        AssetAndLiabilityBalanceSheet:
          type: string
        AssetAndLiabilityMaturityLadder:
          type: string
        AssetAndLiabilityCapitalAllocation:
          type: string
        AssetAndLiabilityPolicyGoalRecord:
          type: string
        AssetAndLiabilityPolicyType:
          type: string
        AssetAndLiabilityPolicyTypeDefinition:
          type: string
        AssetAndLiabilityPolicyTypeGoals:
          type: string
        AssetAndLiabilityPolicyTypePosition:
          type: string
        AssetAndLiabilityPolicyTypeSensitivityAssessment:
          type: string
    TransactionAlignment:
      type: object
      properties:
        BusinessUnitReference:
          type: object
        ProposedTransactionOriginatorReference:
          type: object
        ProposedTransactionType:
          type: string
        ProposedTransactionDescription:
          type: string
        ProposedTransactionAmount:
          type: number
        ProposedTransactionRiskAssessment:
          type: string
        DocumentDirectoryEntryInstanceReference:
          type: object
        CorrespondenceInstanceReference:
          type: object
        DateType:
          type: string
        Date:
          type: string
        AssetAndLiabilityAlignmentAssessment:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    RequestAssetAndLiabilityPortfolioStrategyResponse:
      type: object
      properties:
        AssetAndLiabilityPortfolioStrategy:
          type: object
          properties:
            AssetAndLiabilityPolicyGoalRecord:
              type: string
            AssetAndLiabilityPolicyType:
              type: string
            AssetAndLiabilityPolicyTypeDefinition:
              type: string
            AssetAndLiabilityPolicyTypeGoals:
              type: string
            AssetAndLiabilityPolicyTypePosition:
              type: string
            AssetAndLiabilityPolicyTypeSensitivityAssessment:
              type: string
    CreateTransactionAlignmentRequest:
      type: object
      properties:
        AssetAndLiabilityPortfolioStrategy:
          type: object
          properties:
            AssetAndLiabilityPolicyType:
              type: string
            AssetAndLiabilityPolicyTypeDefinition:
              type: string
            AssetAndLiabilityPolicyTypeGoals:
              type: string
            AssetAndLiabilityPolicyTypePosition:
              type: string
            AssetAndLiabilityPolicyTypeSensitivityAssessment:
              type: string
        TransactionAlignment:
          type: object
          properties:
            BusinessUnitReference:
              type: object
            ProposedTransactionOriginatorReference:
              type: object
            ProposedTransactionType:
              type: string
            ProposedTransactionDescription:
              type: string
            ProposedTransactionAmount:
              type: number
            ProposedTransactionRiskAssessment:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorrespondenceInstanceReference:
              type: object
            DateType:
              type: string
    CreateTransactionAlignmentResponse:
      type: object
      properties:
        AssetAndLiabilityPortfolioStrategy:
          type: object
          properties:
            AssetAndLiabilityPolicyType:
              type: string
            AssetAndLiabilityPolicyTypeDefinition:
              type: string
            AssetAndLiabilityPolicyTypeGoals:
              type: string
            AssetAndLiabilityPolicyTypePosition:
              type: string
            AssetAndLiabilityPolicyTypeSensitivityAssessment:
              type: string
        TransactionAlignment:
          type: object
          properties:
            DateType:
              type: string
            AssetAndLiabilityAlignmentAssessment:
              type: string
    RequestTransactionAlignmentRequest:
      type: object
      properties:
        TransactionAlignment:
          type: object
          properties:
            BusinessUnitReference:
              type: object
            ProposedTransactionOriginatorReference:
              type: object
            ProposedTransactionType:
              type: string
            ProposedTransactionDescription:
              type: string
            ProposedTransactionAmount:
              type: number
            ProposedTransactionRiskAssessment:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorrespondenceInstanceReference:
              type: object
            DateType:
              type: string
    RequestTransactionAlignmentResponse:
      type: object
      properties:
        TransactionAlignment:
          type: object
          properties:
            DateType:
              type: string
            AssetAndLiabilityAlignmentAssessment:
              type: string
    RetrieveTransactionAlignmentResponse:
      type: object
      properties:
        AssetAndLiabilityPortfolioStrategy:
          type: object
          properties:
            AssetAndLiabilityPolicyType:
              type: string
            AssetAndLiabilityPolicyTypeDefinition:
              type: string
            AssetAndLiabilityPolicyTypeGoals:
              type: string
            AssetAndLiabilityPolicyTypePosition:
              type: string
            AssetAndLiabilityPolicyTypeSensitivityAssessment:
              type: string
        TransactionAlignment:
          type: object
          properties:
            BusinessUnitReference:
              type: object
            ProposedTransactionOriginatorReference:
              type: object
            ProposedTransactionType:
              type: string
            ProposedTransactionDescription:
              type: string
            ProposedTransactionAmount:
              type: number
            ProposedTransactionRiskAssessment:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorrespondenceInstanceReference:
              type: object
            DateType:
              type: string
            AssetAndLiabilityAlignmentAssessment:
              type: string
  parameters:
    AssetAndLiabilityManagementID:
      name: assetandliabilitymanagementId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    TransactionAlignmentID:
      name: transactionalignmentId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    AssetAndLiabilityPortfolioStrategy:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AssetAndLiabilityPortfolioStrategy'
    CreateTransactionAlignmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateTransactionAlignmentRequest'
    RequestTransactionAlignmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestTransactionAlignmentRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
