openapi: 3.0.1
info:
  title: Business Unit Management
  description: Track and report on business unit activity and financial performance
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/BusinessUnitManagement/10.0.0
paths:
  /BusinessUnitManagement/Create:
    post:
      tags:
      - CR - BusinessUnitManagementPlan
      summary: CrCR Create the management plan for the business unit
      description: CrCR Create the management plan for the business unit
      operationId: Create
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/BusinessUnitManagementPlan'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessUnitManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /BusinessUnitManagement/{businessunitmanagementId}/Update:
    put:
      tags:
      - CR - BusinessUnitManagementPlan
      summary: UpCR Update aspects of the business unit management plan
      description: UpCR Update aspects of the business unit management plan
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/BusinessUnitManagementID'
      requestBody:
        $ref: '#/components/requestBodies/BusinessUnitManagementPlan'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessUnitManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /BusinessUnitManagement/{businessunitmanagementId}/Request:
    put:
      tags:
      - CR - BusinessUnitManagementPlan
      summary: RqCR Request manual intervention with the plan (e.g. reprioritize activities)
      description: RqCR Request manual intervention with the plan (e.g. reprioritize activities)
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/BusinessUnitManagementID'
      requestBody:
        $ref: '#/components/requestBodies/BusinessUnitManagementPlan'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessUnitManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /BusinessUnitManagement/{businessunitmanagementId}/Retrieve:
    get:
      tags:
      - CR - BusinessUnitManagementPlan
      summary: ReCR Retrieve details about the business unit management plan
      description: ReCR Retrieve details about the business unit management plan
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/BusinessUnitManagementID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessUnitManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /BusinessUnitManagement/{businessunitmanagementId}/Performance/{performanceId}/Update:
    put:
      tags:
      - BQ - Performance
      summary: UpBQ Update details of the activity analysis for the business unit
      description: UpBQ Update details of the activity analysis for the business unit
      operationId: UpdatePerformance
      parameters:
      - $ref: '#/components/parameters/BusinessUnitManagementID'
      - $ref: '#/components/parameters/PerformanceID'
      requestBody:
        $ref: '#/components/requestBodies/Performance'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Performance'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /BusinessUnitManagement/{businessunitmanagementId}/Performance/{performanceId}/Request:
    put:
      tags:
      - BQ - Performance
      summary: RqBQ Request manual intervention in the business unit performance analysis (e.g. revise projections)
      description: RqBQ Request manual intervention in the business unit performance analysis (e.g. revise projections)
      operationId: RequestPerformance
      parameters:
      - $ref: '#/components/parameters/BusinessUnitManagementID'
      - $ref: '#/components/parameters/PerformanceID'
      requestBody:
        $ref: '#/components/requestBodies/Performance'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Performance'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /BusinessUnitManagement/{businessunitmanagementId}/Performance/{performanceId}/Retrieve:
    get:
      tags:
      - BQ - Performance
      summary: ReBQ Retrieve details about the business unit activity analysis
      description: ReBQ Retrieve details about the business unit activity analysis
      operationId: RetrievePerformance
      parameters:
      - $ref: '#/components/parameters/BusinessUnitManagementID'
      - $ref: '#/components/parameters/PerformanceID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Performance'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /BusinessUnitManagement/{businessunitmanagementId}/Troubleshooting/Create:
    post:
      tags:
      - BQ - Troubleshooting
      summary: CrBQ Create a service troubleshooting activity (to address major production issue)
      description: CrBQ Create a service troubleshooting activity (to address major production issue)
      operationId: CreateTroubleshooting
      parameters:
      - $ref: '#/components/parameters/BusinessUnitManagementID'
      requestBody:
        $ref: '#/components/requestBodies/BusinessUnitManagementPlan'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessUnitManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /BusinessUnitManagement/{businessunitmanagementId}/Troubleshooting/{troubleshootingId}/Update:
    put:
      tags:
      - BQ - Troubleshooting
      summary: UpBQ Update details of a troubleshooting plan item
      description: UpBQ Update details of a troubleshooting plan item
      operationId: UpdateTroubleshooting
      parameters:
      - $ref: '#/components/parameters/BusinessUnitManagementID'
      - $ref: '#/components/parameters/TroubleshootingID'
      requestBody:
        $ref: '#/components/requestBodies/Troubleshooting'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Troubleshooting'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /BusinessUnitManagement/{businessunitmanagementId}/Troubleshooting/{troubleshootingId}/Request:
    put:
      tags:
      - BQ - Troubleshooting
      summary: RqBQ Request manual intervention to a troubleshooting action
      description: RqBQ Request manual intervention to a troubleshooting action
      operationId: RequestTroubleshooting
      parameters:
      - $ref: '#/components/parameters/BusinessUnitManagementID'
      - $ref: '#/components/parameters/TroubleshootingID'
      requestBody:
        $ref: '#/components/requestBodies/Troubleshooting'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Troubleshooting'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /BusinessUnitManagement/{businessunitmanagementId}/Troubleshooting/{troubleshootingId}/Retrieve:
    get:
      tags:
      - BQ - Troubleshooting
      summary: ReBQ Retrieve details about troubleshooting activity
      description: ReBQ Retrieve details about troubleshooting activity
      operationId: RetrieveTroubleshooting
      parameters:
      - $ref: '#/components/parameters/BusinessUnitManagementID'
      - $ref: '#/components/parameters/TroubleshootingID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Troubleshooting'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    BusinessUnitManagementPlan:
      type: object
      properties:
        BusinessUnitManagementPlanPeriod:
          type: string
        BusinessUnitUsagePoliciesAndGuidelines:
          type: string
        BusinessUnitPerformanceGoals:
          type: string
        BusinessUnitOperatingSchedule:
          type: string
        BusinessUnitOperatingOrganization:
          type: string
        BusinessUnitResourcePlan:
          type: string
        BusinessUnitTrainingPlan:
          type: string
    Performance:
      type: object
      properties:
        BusinessUnitResourceUtilization:
          type: string
        BusinessUnitOutput/WorkProjections:
          type: string
        BusinessUnitPerformanceStatistics:
          type: string
        BusinessUnitPerformanceStatisticType:
          type: string
        BusinessUnitPerformanceStatisticValue:
          type: string
        BusinessUnitPerformanceStatisticInterpretation:
          type: string
        BusinessUnitPerformanceStatisticRecommendation:
          type: string
    Troubleshooting:
      type: object
      properties:
        BusinessUnitProductionIssueRecord:
          type: string
        BusinessUnitIssueAnalysisAndRecommendedResponse:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    BusinessUnitManagementID:
      name: businessunitmanagementId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    PerformanceID:
      name: performanceId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    TroubleshootingID:
      name: troubleshootingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    BusinessUnitManagementPlan:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BusinessUnitManagementPlan'
    Performance:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Performance'
    Troubleshooting:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Troubleshooting'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
