openapi: 3.0.1
info:
  title: Card Authorization
  description: This service domain is responsible for the real time card authorization decisions for credit/charge cards.
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/CardAuthorization/10.0.0
paths:
  /CardAuthorization/Evaluate:
    post:
      tags:
      - CR - CreditCardAuthorizationAssessment
      summary: EvCR Evaluate a card transaction authorization assessment
      description: EvCR Evaluate a card transaction authorization assessment
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/CreditCardAuthorizationAssessment'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardAuthorizationAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardAuthorization/{cardauthorizationId}/Update:
    put:
      tags:
      - CR - CreditCardAuthorizationAssessment
      summary: UpCR Update details of a card transaction authorization assessment
      description: UpCR Update details of a card transaction authorization assessment
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/CardAuthorizationID'
      requestBody:
        $ref: '#/components/requestBodies/CreditCardAuthorizationAssessment'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardAuthorizationAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardAuthorization/{cardauthorizationId}/Retrieve:
    get:
      tags:
      - CR - CreditCardAuthorizationAssessment
      summary: ReCR Retrieve details about an active car transaction authorization task
      description: ReCR Retrieve details about an active car transaction authorization task
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/CardAuthorizationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardAuthorizationAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardAuthorization/{cardauthorizationId}/DeviceCheck/{devicecheckId}/Update:
    put:
      tags:
      - BQ - DeviceCheck
      summary: UpBQ Update details for the device check
      description: UpBQ Update details for the device check
      operationId: UpdateDeviceCheck
      parameters:
      - $ref: '#/components/parameters/CardAuthorizationID'
      - $ref: '#/components/parameters/DeviceCheckID'
      requestBody:
        $ref: '#/components/requestBodies/DeviceCheck'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceCheck'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardAuthorization/{cardauthorizationId}/DeviceCheck/{devicecheckId}/Retrieve:
    get:
      tags:
      - BQ - DeviceCheck
      summary: ReBQ Retrieve details about the device check
      description: ReBQ Retrieve details about the device check
      operationId: RetrieveDeviceCheck
      parameters:
      - $ref: '#/components/parameters/CardAuthorizationID'
      - $ref: '#/components/parameters/DeviceCheckID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceCheck'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardAuthorization/{cardauthorizationId}/Authentication/{authenticationId}/Update:
    put:
      tags:
      - BQ - Authentication
      summary: UpBQ Update details for the card holder authentication check
      description: UpBQ Update details for the card holder authentication check
      operationId: UpdateAuthentication
      parameters:
      - $ref: '#/components/parameters/CardAuthorizationID'
      - $ref: '#/components/parameters/AuthenticationID'
      requestBody:
        $ref: '#/components/requestBodies/Authentication'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authentication'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardAuthorization/{cardauthorizationId}/Authentication/{authenticationId}/Retrieve:
    get:
      tags:
      - BQ - Authentication
      summary: ReBQ Retrieve details about the card holder authentication check
      description: ReBQ Retrieve details about the card holder authentication check
      operationId: RetrieveAuthentication
      parameters:
      - $ref: '#/components/parameters/CardAuthorizationID'
      - $ref: '#/components/parameters/AuthenticationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveAuthenticationResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardAuthorization/{cardauthorizationId}/CreditCheck/{creditcheckId}/Retrieve:
    get:
      tags:
      - BQ - CreditCheck
      summary: ReBQ Retrieve details about the credit check
      description: ReBQ Retrieve details about the credit check
      operationId: RetrieveCreditCheck
      parameters:
      - $ref: '#/components/parameters/CardAuthorizationID'
      - $ref: '#/components/parameters/CreditCheckID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveCreditCheckResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardAuthorization/{cardauthorizationId}/FraudCheck/{fraudcheckId}/Retrieve:
    get:
      tags:
      - BQ - FraudCheck
      summary: ReBQ Retrieve details about the fraud check
      description: ReBQ Retrieve details about the fraud check
      operationId: RetrieveFraudCheck
      parameters:
      - $ref: '#/components/parameters/CardAuthorizationID'
      - $ref: '#/components/parameters/FraudCheckID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveFraudCheckResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardAuthorization/{cardauthorizationId}/StandIn/{standinId}/Retrieve:
    get:
      tags:
      - BQ - StandIn
      summary: ReBQ Retrieve details about the stand in check
      description: ReBQ Retrieve details about the stand in check
      operationId: RetrieveStandIn
      parameters:
      - $ref: '#/components/parameters/CardAuthorizationID'
      - $ref: '#/components/parameters/StandInID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandIn'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CreditCardAuthorizationAssessment:
      type: object
      properties:
        NetworkReference:
          type: object
        ParticipantAcquirerBankReference:
          type: object
        ParticipantIssuerBankReference:
          type: object
        CardTransactionRecord:
          type: string
        CardTransactionProductInstanceReference:
          type: object
        CardHolderReference:
          type: object
        CardTransactionIssuedDeviceReference:
          type: object
        CardTransactionNetworkReference:
          type: object
        CardTransactionIssuingBankReference:
          type: object
        CardTransactionMerchantAcquiringBankReference:
          type: object
        CardTransactionType:
          type: string
        CardTransactionCurrency:
          type: string
        CardTransactionAmountType:
          type: string
        CardTransactionAmount:
          type: number
        CardTransactionMerchantReference:
          type: object
        CardTransactionLocationReference:
          type: object
        CardTransactionProductandServiceReference:
          type: object
        CardTransactionDateOrTime:
          type: string
        CardTransactionFXConversionCharge:
          type: string
        CardTransactionInterchargeFee:
          type: string
        CardTransactionAuthorizationRecord:
          type: string
    StandIn:
      type: object
      properties:
        NegativeFileReference:
          type: object
        CardAccountStandInAuthorizationResult:
          type: string
    DeviceCheck:
      type: object
      properties:
        IssuedDeviceSecurityCode:
          type: string
        IssuedDeviceCryptogram:
          type: string
        IssuedDeviceCVV:
          type: string
        IssuedDeviceBIN:
          type: string
        IssuedDeviceCheckDigit:
          type: string
        IssuedDeviceValidThrough:
          type: string
        IssuedDeviceCheckResult:
          type: string
    FraudCheck:
      type: object
      properties:
        FraudCheckResult:
          type: string
    CreditCheck:
      type: object
      properties:
        CardAccountavailablebalancecheckresult:
          type: string
    Authentication:
      type: object
      properties:
        CardTransactionProductInstanceReference:
          type: object
        CardHolderAccountPassword:
          type: string
        IssuedDevicePIN:
          type: string
        AuthenticationSecretQuestionReference:
          type: object
        AuthenticationSecretQuestionTemplate:
          type: string
        AuthenticationSecretQuestionValue:
          type: string
        AuthenticationCheckResult:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    RetrieveAuthenticationResponse:
      type: object
      properties:
        CreditCardAuthorizationAssessment:
          type: object
          properties:
            CardTransactionRecord:
              type: string
            CardHolderReference:
              type: object
        Authentication:
          type: object
          properties:
            CardTransactionProductInstanceReference:
              type: object
            CardHolderAccountPassword:
              type: string
            IssuedDevicePIN:
              type: string
            AuthenticationSecretQuestionReference:
              type: object
            AuthenticationSecretQuestionTemplate:
              type: string
            AuthenticationSecretQuestionValue:
              type: string
            AuthenticationCheckResult:
              type: string
    RetrieveCreditCheckResponse:
      type: object
      properties:
        CreditCardAuthorizationAssessment:
          type: object
          properties:
            CardTransactionProductInstanceReference:
              type: object
            CardHolderReference:
              type: object
        CreditCheck:
          type: object
          properties:
            CardAccountavailablebalancecheckresult:
              type: string
    RetrieveFraudCheckResponse:
      type: object
      properties:
        CreditCardAuthorizationAssessment:
          type: object
          properties:
            NetworkReference:
              type: object
            ParticipantAcquirerBankReference:
              type: object
            ParticipantIssuerBankReference:
              type: object
            CardTransactionRecord:
              type: string
            CardTransactionProductInstanceReference:
              type: object
            CardHolderReference:
              type: object
            CardTransactionIssuedDeviceReference:
              type: object
            CardTransactionNetworkReference:
              type: object
            CardTransactionIssuingBankReference:
              type: object
            CardTransactionMerchantAcquiringBankReference:
              type: object
            CardTransactionType:
              type: string
            CardTransactionCurrency:
              type: string
            CardTransactionAmountType:
              type: string
            CardTransactionMerchantReference:
              type: object
            CardTransactionLocationReference:
              type: object
            CardTransactionProductandServiceReference:
              type: object
            CardTransactionDateOrTime:
              type: string
            CardTransactionFXConversionCharge:
              type: string
            CardTransactionInterchargeFee:
              type: string
            CardTransactionAuthorizationRecord:
              type: string
        FraudCheck:
          type: object
          properties:
            FraudCheckResult:
              type: string
  parameters:
    CardAuthorizationID:
      name: cardauthorizationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    StandInID:
      name: standinId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    DeviceCheckID:
      name: devicecheckId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    FraudCheckID:
      name: fraudcheckId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    CreditCheckID:
      name: creditcheckId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    AuthenticationID:
      name: authenticationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    CreditCardAuthorizationAssessment:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreditCardAuthorizationAssessment'
    DeviceCheck:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeviceCheck'
    Authentication:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Authentication'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
