openapi: 3.0.1
info:
  title: Card Network Participant Facility
  description: This service domain orchestrates the activities related to the inclusion of new Acquirers and Issuers in the Card Network, their terms and conditions and their status.
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/CardNetworkParticipantFacility/10.0.0
paths:
  /CardNetworkParticipantFacility/Initiate:
    post:
      tags:
      - CR - CardNetworkParticipantFacility
      summary: InCR Initiate a new network participant facility
      description: InCR Initiate a new network participant facility
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/CardNetworkParticipantFacility'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardNetworkParticipantFacility'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardNetworkParticipantFacility/{cardnetworkparticipantfacilityId}/Update:
    put:
      tags:
      - CR - CardNetworkParticipantFacility
      summary: UpCR Update details for an active network participant facility
      description: UpCR Update details for an active network participant facility
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/CardNetworkParticipantFacilityID'
      requestBody:
        $ref: '#/components/requestBodies/CardNetworkParticipantFacility'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardNetworkParticipantFacility'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardNetworkParticipantFacility/{cardnetworkparticipantfacilityId}/Retrieve:
    get:
      tags:
      - CR - CardNetworkParticipantFacility
      summary: ReCR Retrieve details about a network participant facility
      description: ReCR Retrieve details about a network participant facility
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/CardNetworkParticipantFacilityID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardNetworkParticipantFacility'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardNetworkParticipantFacility/{cardnetworkparticipantfacilityId}/ParticipantAccount/{participantaccountId}/Update:
    put:
      tags:
      - BQ - ParticipantAccount
      summary: UpBQ Update an account posting made to the network participant
      description: UpBQ Update an account posting made to the network participant
      operationId: UpdateParticipantAccount
      parameters:
      - $ref: '#/components/parameters/CardNetworkParticipantFacilityID'
      - $ref: '#/components/parameters/ParticipantAccountID'
      requestBody:
        $ref: '#/components/requestBodies/ParticipantAccount'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantAccount'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardNetworkParticipantFacility/{cardnetworkparticipantfacilityId}/ParticipantAccount/{participantaccountId}/Execute:
    put:
      tags:
      - BQ - ParticipantAccount
      summary: ExBQ Execute a posting against the participant's account
      description: ExBQ Execute a posting against the participant's account
      operationId: ExecuteParticipantAccount
      parameters:
      - $ref: '#/components/parameters/CardNetworkParticipantFacilityID'
      - $ref: '#/components/parameters/ParticipantAccountID'
      requestBody:
        $ref: '#/components/requestBodies/ParticipantAccount'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantAccount'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardNetworkParticipantFacility/{cardnetworkparticipantfacilityId}/ParticipantAccount/{participantaccountId}/Retrieve:
    get:
      tags:
      - BQ - ParticipantAccount
      summary: ReBQ Retrieve details about an account posting or account
      description: ReBQ Retrieve details about an account posting or account
      operationId: RetrieveParticipantAccount
      parameters:
      - $ref: '#/components/parameters/CardNetworkParticipantFacilityID'
      - $ref: '#/components/parameters/ParticipantAccountID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardNetworkParticipantFacility'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardNetworkParticipantFacility/{cardnetworkparticipantfacilityId}/ParticipantService/{participantserviceId}/Update:
    put:
      tags:
      - BQ - ParticipantService
      summary: UpBQ Update details about a participant service request
      description: UpBQ Update details about a participant service request
      operationId: UpdateParticipantService
      parameters:
      - $ref: '#/components/parameters/CardNetworkParticipantFacilityID'
      - $ref: '#/components/parameters/ParticipantServiceID'
      requestBody:
        $ref: '#/components/requestBodies/ParticipantService'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantService'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardNetworkParticipantFacility/{cardnetworkparticipantfacilityId}/ParticipantService/{participantserviceId}/Execute:
    put:
      tags:
      - BQ - ParticipantService
      summary: ExBQ Execute an automated participant service request (e.g. merchant alert)
      description: ExBQ Execute an automated participant service request (e.g. merchant alert)
      operationId: ExecuteParticipantService
      parameters:
      - $ref: '#/components/parameters/CardNetworkParticipantFacilityID'
      - $ref: '#/components/parameters/ParticipantServiceID'
      requestBody:
        $ref: '#/components/requestBodies/ParticipantService'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantService'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardNetworkParticipantFacility/{cardnetworkparticipantfacilityId}/ParticipantService/{participantserviceId}/Request:
    put:
      tags:
      - BQ - ParticipantService
      summary: RqBQ Request manual intervention with a service request (e.g. arbitration)
      description: RqBQ Request manual intervention with a service request (e.g. arbitration)
      operationId: RequestParticipantService
      parameters:
      - $ref: '#/components/parameters/CardNetworkParticipantFacilityID'
      - $ref: '#/components/parameters/ParticipantServiceID'
      requestBody:
        $ref: '#/components/requestBodies/ParticipantService'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantService'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CardNetworkParticipantFacility/{cardnetworkparticipantfacilityId}/ParticipantService/{participantserviceId}/Retrieve:
    get:
      tags:
      - BQ - ParticipantService
      summary: ReBQ Retrieve details about participant service requests
      description: ReBQ Retrieve details about participant service requests
      operationId: RetrieveParticipantService
      parameters:
      - $ref: '#/components/parameters/CardNetworkParticipantFacilityID'
      - $ref: '#/components/parameters/ParticipantServiceID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardNetworkParticipantFacility'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CardNetworkParticipantFacility:
      type: object
      properties:
        ProductandServiceReference:
          type: object
        CustomerReference:
          type: object
        PartyReference:
          type: object
        FacilityTerms:
          type: string
        ParticipantAcquirerBankReference:
          type: object
        ParticipantAcquirerBankClearingandSettlementTerms:
          type: string
        ParticipantAcquirerBankServiceSchedule:
          type: string
        ParticipantIssuerBankReference:
          type: object
        ParticipantIssuerBankClearingandSettlementTerms:
          type: string
        ParticipantIssuerBankServiceSchedule:
          type: string
    ParticipantAccount:
      type: object
      properties:
        ParticipantAccountPostingTransaction:
          type: string
        NetworkParticipantFacilityAccountPostingPurpose:
          type: string
        NetworkParticipantFacilityAccountPostingAmount:
          type: number
        NetworkParticipantFacilityAccountPostingValueDate:
          type: string
        NetworkParticipantFacilityAccountPostingResult:
          type: string
    ParticipantService:
      type: object
      properties:
        ParticipantServiceRecord:
          type: string
        NetworkParticipantServiceType:
          type: string
        NetworkParticipantServiceCharge:
          type: string
        NetworkParticipantServiceDate/Time:
          type: string
        NetworkParticipantNetworkServiceRequestWorkProduct:
          type: string
        NetworkParticipantNetworkServiceRequestResult:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    CardNetworkParticipantFacilityID:
      name: cardnetworkparticipantfacilityId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ParticipantAccountID:
      name: participantaccountId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ParticipantServiceID:
      name: participantserviceId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    CardNetworkParticipantFacility:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CardNetworkParticipantFacility'
    ParticipantAccount:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ParticipantAccount'
    ParticipantService:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ParticipantService'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
