openapi: 3.0.1
info:
  title: Cheque Processing
  description: Handle the processing of paper cheques, generating financial transactions for processing
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/ChequeProcessing/10.0.0
paths:
  /ChequeProcessing/{chequeprocessingId}/Control:
    put:
      tags:
      - CR - ChequeProcessingOperatingSession
      summary: CoCR Control the processing of Cheque Processing Operating Session
      description: CoCR Control the processing of Cheque Processing Operating Session
      operationId: Control
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      requestBody:
        $ref: '#/components/requestBodies/ChequeProcessingOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChequeProcessingOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/{chequeprocessingId}/Exchange:
    put:
      tags:
      - CR - ChequeProcessingOperatingSession
      summary: EcCR Accept, verify, etc. aspects of Cheque Processing Operating Session processing
      description: EcCR Accept, verify, etc. aspects of Cheque Processing Operating Session processing
      operationId: Exchange
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      requestBody:
        $ref: '#/components/requestBodies/ChequeProcessingOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChequeProcessingOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/{chequeprocessingId}/Execute:
    put:
      tags:
      - CR - ChequeProcessingOperatingSession
      summary: ExCR Execute an available automated action for Cheque Processing Operating Session
      description: ExCR Execute an available automated action for Cheque Processing Operating Session
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      requestBody:
        $ref: '#/components/requestBodies/ChequeProcessingOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChequeProcessingOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/Initiate:
    post:
      tags:
      - CR - ChequeProcessingOperatingSession
      summary: InCR Instantiate a new Cheque Processing Operating Session
      description: InCR Instantiate a new Cheque Processing Operating Session
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/ChequeProcessingOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChequeProcessingOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/{chequeprocessingId}/Retrieve:
    get:
      tags:
      - CR - ChequeProcessingOperatingSession
      summary: ReCR Retrieve details about any aspect of Cheque Processing Operating Session
      description: ReCR Retrieve details about any aspect of Cheque Processing Operating Session
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChequeProcessingOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/{chequeprocessingId}/Request:
    put:
      tags:
      - CR - ChequeProcessingOperatingSession
      summary: RqCR Request manual intervention or a decision with respect to Cheque Processing Operating Session
      description: RqCR Request manual intervention or a decision with respect to Cheque Processing Operating Session
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      requestBody:
        $ref: '#/components/requestBodies/ChequeProcessingOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChequeProcessingOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/{chequeprocessingId}/Update:
    put:
      tags:
      - CR - ChequeProcessingOperatingSession
      summary: UpCR Update details relating to Cheque Processing Operating Session
      description: UpCR Update details relating to Cheque Processing Operating Session
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      requestBody:
        $ref: '#/components/requestBodies/ChequeProcessingOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChequeProcessingOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/{chequeprocessingId}/FinancialTransactionInitiation/{financialtransactioninitiationId}/Exchange:
    put:
      tags:
      - BQ - FinancialTransactionInitiation
      summary: EcBQ Accept, verify, etc. aspects of Financial Transaction Initiation processing
      description: EcBQ Accept, verify, etc. aspects of Financial Transaction Initiation processing
      operationId: ExchangeFinancialTransactionInitiation
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      - $ref: '#/components/parameters/FinancialTransactionInitiationID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialTransactionInitiation'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialTransactionInitiation'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/{chequeprocessingId}/CancelledChequeHandling/{cancelledchequehandlingId}/Retrieve:
    get:
      tags:
      - BQ - CancelledChequeHandling
      summary: ReBQ Retrieve details about any aspect of Cancelled Cheque Handling
      description: ReBQ Retrieve details about any aspect of Cancelled Cheque Handling
      operationId: RetrieveCancelledChequeHandling
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      - $ref: '#/components/parameters/CancelledChequeHandlingID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelledChequeHandling'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/{chequeprocessingId}/ChequeExtraction/{chequeextractionId}/Retrieve:
    get:
      tags:
      - BQ - ChequeExtraction
      summary: ReBQ Retrieve details about any aspect of Cheque Extraction
      description: ReBQ Retrieve details about any aspect of Cheque Extraction
      operationId: RetrieveChequeExtraction
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      - $ref: '#/components/parameters/ChequeExtractionID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChequeExtraction'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/{chequeprocessingId}/FinancialTransactionInitiation/{financialtransactioninitiationId}/Retrieve:
    get:
      tags:
      - BQ - FinancialTransactionInitiation
      summary: ReBQ Retrieve details about any aspect of Financial Transaction Initiation
      description: ReBQ Retrieve details about any aspect of Financial Transaction Initiation
      operationId: RetrieveFinancialTransactionInitiation
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      - $ref: '#/components/parameters/FinancialTransactionInitiationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialTransactionInitiation'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ChequeProcessing/{chequeprocessingId}/CancelledChequeHandling/{cancelledchequehandlingId}/Update:
    put:
      tags:
      - BQ - CancelledChequeHandling
      summary: UpBQ Update details relating to Cancelled Cheque Handling
      description: UpBQ Update details relating to Cancelled Cheque Handling
      operationId: UpdateCancelledChequeHandling
      parameters:
      - $ref: '#/components/parameters/ChequeProcessingID'
      - $ref: '#/components/parameters/CancelledChequeHandlingID'
      requestBody:
        $ref: '#/components/requestBodies/CancelledChequeHandling'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelledChequeHandling'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ChequeProcessingOperatingSession:
      type: object
      properties:
        ChequeProcessingOperatingSessionSchedule:
          type: string
        ChequeProcessingOperatingSessionStatus:
          type: string
        ChequeProcessingOperatingSessionUsageLog:
          type: string
        ChequeProcessingOperatingSessionReference:
          type: object
        ChequeProcessingOperatingSessionServiceProviderReference:
          type: object
        ChequeProcessingOperatingSessionType:
          type: string
        ChequeProcessingOperatingSessionServiceProviderSchedule:
          type: string
        ChequeProcessingOperatingSessionServiceType:
          type: string
        ChequeProcessingOperatingSessionServiceConfiguration:
          type: string
    ChequeProcessingOutcome:
      type: object
      properties:
        ChequeProcessingIncident:
          type: string
        ChequeProcessingProvision:
          type: string
    CancelledChequeHandling:
      type: object
      properties:
        CancelledChequeHandlingPreconditions:
          type: string
        CancelledChequeHandlingFunctionSchedule:
          type: string
        CancelledChequeHandling:
          type: object
        CancelledChequeHandlingServiceType:
          type: string
        CancelledChequeHandlingServiceDescription:
          type: string
        CancelledChequeHandlingServiceInputsandOuputs:
          type: string
        CancelledChequeHandlingServiceWorkProduct:
          type: string
        CancelledChequeHandlingServiceName:
          type: string
    ChequeExtraction:
      type: object
      properties:
        ChequeExtractionPreconditions:
          type: string
        ChequeExtractionFunctionSchedule:
          type: string
        ChequeExtraction:
          type: object
        ChequeExtractionServiceType:
          type: string
        ChequeExtractionServiceDescription:
          type: string
        ChequeExtractionServiceInputsandOuputs:
          type: string
        ChequeExtractionServiceWorkProduct:
          type: string
        ChequeExtractionServiceName:
          type: string
    FinancialTransactionInitiation:
      type: object
      properties:
        FinancialTransactionInitiationPreconditions:
          type: string
        FinancialTransactionInitiationFunctionSchedule:
          type: string
        FinancialTransactionInitiation:
          type: object
        FinancialTransactionInitiationServiceType:
          type: string
        FinancialTransactionInitiationServiceDescription:
          type: string
        FinancialTransactionInitiationServiceInputsandOuputs:
          type: string
        FinancialTransactionInitiationServiceWorkProduct:
          type: string
        FinancialTransactionInitiationServiceName:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    ChequeProcessingID:
      name: chequeprocessingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ChequeProcessingOutcomeID:
      name: chequeprocessingoutcomeId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    CancelledChequeHandlingID:
      name: cancelledchequehandlingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ChequeExtractionID:
      name: chequeextractionId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    FinancialTransactionInitiationID:
      name: financialtransactioninitiationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    ChequeProcessingOperatingSession:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ChequeProcessingOperatingSession'
    FinancialTransactionInitiation:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FinancialTransactionInitiation'
    CancelledChequeHandling:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CancelledChequeHandling'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
