openapi: 3.0.1
info:
  title: Competitor Analysis
  description: Solicit, consolidate and analyze competitor specific public domain data to develop competitor insights and comparisons
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/CompetitorAnalysis/10.0.0
paths:
  /CompetitorAnalysis/Evaluate:
    post:
      tags:
      - CR - CompetitorAnalysis
      summary: EvCR Initialize competitor analysis
      description: EvCR Initialize competitor analysis
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/CompetitorAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitorAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CompetitorAnalysis/{competitoranalysisId}/Execute:
    put:
      tags:
      - CR - CompetitorAnalysis
      summary: ExCR Obtain an automated refresh of maintained competitor analysis
      description: ExCR Obtain an automated refresh of maintained competitor analysis
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/CompetitorAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/CompetitorAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitorAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CompetitorAnalysis/{competitoranalysisId}/Request:
    put:
      tags:
      - CR - CompetitorAnalysis
      summary: RqCR Request a manual intervention in the development of competitor analysis
      description: RqCR Request a manual intervention in the development of competitor analysis
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/CompetitorAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/CompetitorAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitorAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CompetitorAnalysis/{competitoranalysisId}/Retrieve:
    get:
      tags:
      - CR - CompetitorAnalysis
      summary: ReCR Retrieve details about competitor analysis activity
      description: ReCR Retrieve details about competitor analysis activity
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/CompetitorAnalysisID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitorAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CompetitorAnalysis:
      type: object
      properties:
        CompetitorAnalysisType:
          type: string
        CompetitorAnalysisSpecification:
          type: string
        CompetitorAnalysisGuidance:
          type: string
        CompetitorAnalysisAlgorithmReference:
          type: object
        CompetitorAnalysisRequestRecord:
          type: string
        CompetitorAnalysisRequest:
          type: string
        EmployeeOrBusinessUnitReference:
          type: object
        CompetitorAnalysisRequestWorkProducts:
          type: string
        CompetitorAnalysisRequestResult:
          type: string
        CompetitorAnalysisUsageRecord:
          type: string
        CompetitorAnalysisUsage:
          type: string
        CompetitorAnalysisImpact:
          type: string
    AnalysisAlgorithm:
      type: object
      properties:
        AnalysisAlgorithmType:
          type: string
        AnalysisAlgorithmSpecification:
          type: string
        AnalysisAlgorithmReferencedMarketResearchRecord:
          type: object
        MarketResearchReportTypeReference:
          type: string
        MarketResearchReportTypeDefinition:
          type: string
        MarketResearchReportVersion/Period:
          type: string
        MarketResearchReport:
          type: string
        AnalysisAlgorithmRequestRecord:
          type: string
        AnalysisAlgorithmRequest:
          type: string
        AnalysisAlgorithmWorkProducts:
          type: string
        AnalysisAlgorithmRequestResult:
          type: string
        AnalysisAlgorithmUsageRecord:
          type: string
        AnalysisAlgorithmUsage:
          type: string
        AnalysisAlgorithmImpact:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    CompetitorAnalysisID:
      name: competitoranalysisId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    AnalysisAlgorithmID:
      name: analysisalgorithmId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    CompetitorAnalysis:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CompetitorAnalysis'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
