openapi: 3.0.1
info:
  title: Contact Center Management
  description: Oversee the assignment and operation of the customer contact center
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/ContactCenterManagement/10.0.0
paths:
  /ContactCenterManagement/Create:
    post:
      tags:
      - CR - ContactCenterManagementPlan
      summary: CrCR Create the management plan for the contact center
      description: CrCR Create the management plan for the contact center
      operationId: Create
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/ContactCenterManagementPlan'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactCenterManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ContactCenterManagement/{contactcentermanagementId}/Update:
    put:
      tags:
      - CR - ContactCenterManagementPlan
      summary: UpCR Update aspects of the contact center management plan
      description: UpCR Update aspects of the contact center management plan
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/ContactCenterManagementID'
      requestBody:
        $ref: '#/components/requestBodies/ContactCenterManagementPlan'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactCenterManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ContactCenterManagement/{contactcentermanagementId}/Request:
    put:
      tags:
      - CR - ContactCenterManagementPlan
      summary: RqCR Request manual intervention with the plan (e.g. reprioritize activities)
      description: RqCR Request manual intervention with the plan (e.g. reprioritize activities)
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/ContactCenterManagementID'
      requestBody:
        $ref: '#/components/requestBodies/ContactCenterManagementPlan'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactCenterManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ContactCenterManagement/{contactcentermanagementId}/Retrieve:
    get:
      tags:
      - CR - ContactCenterManagementPlan
      summary: ReCR Retrieve details about the contact center management plan
      description: ReCR Retrieve details about the contact center management plan
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/ContactCenterManagementID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactCenterManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ContactCenterManagement/{contactcentermanagementId}/Performance/{performanceId}/Update:
    put:
      tags:
      - BQ - Performance
      summary: UpBQ Update details of the activity analysis for the contact center
      description: UpBQ Update details of the activity analysis for the contact center
      operationId: UpdatePerformance
      parameters:
      - $ref: '#/components/parameters/ContactCenterManagementID'
      - $ref: '#/components/parameters/PerformanceID'
      requestBody:
        $ref: '#/components/requestBodies/Performance'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Performance'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ContactCenterManagement/{contactcentermanagementId}/Performance/{performanceId}/Request:
    put:
      tags:
      - BQ - Performance
      summary: RqBQ Request manual intervention in the contact center performance analysis (e.g. revise projections)
      description: RqBQ Request manual intervention in the contact center performance analysis (e.g. revise projections)
      operationId: RequestPerformance
      parameters:
      - $ref: '#/components/parameters/ContactCenterManagementID'
      - $ref: '#/components/parameters/PerformanceID'
      requestBody:
        $ref: '#/components/requestBodies/Performance'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Performance'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ContactCenterManagement/{contactcentermanagementId}/Performance/{performanceId}/Retrieve:
    get:
      tags:
      - BQ - Performance
      summary: ReBQ Retrieve details about the contact center activity analysis
      description: ReBQ Retrieve details about the contact center activity analysis
      operationId: RetrievePerformance
      parameters:
      - $ref: '#/components/parameters/ContactCenterManagementID'
      - $ref: '#/components/parameters/PerformanceID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Performance'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ContactCenterManagement/{contactcentermanagementId}/Troubleshooting/Create:
    post:
      tags:
      - BQ - Troubleshooting
      summary: CrBQ Create a service troubleshooting activity (to address major production issue)
      description: CrBQ Create a service troubleshooting activity (to address major production issue)
      operationId: CreateTroubleshooting
      parameters:
      - $ref: '#/components/parameters/ContactCenterManagementID'
      requestBody:
        $ref: '#/components/requestBodies/ContactCenterManagementPlan'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactCenterManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ContactCenterManagement/{contactcentermanagementId}/Troubleshooting/{troubleshootingId}/Update:
    put:
      tags:
      - BQ - Troubleshooting
      summary: UpBQ Update details of a troubleshooting plan item
      description: UpBQ Update details of a troubleshooting plan item
      operationId: UpdateTroubleshooting
      parameters:
      - $ref: '#/components/parameters/ContactCenterManagementID'
      - $ref: '#/components/parameters/TroubleshootingID'
      requestBody:
        $ref: '#/components/requestBodies/Troubleshooting'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Troubleshooting'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ContactCenterManagement/{contactcentermanagementId}/Troubleshooting/{troubleshootingId}/Request:
    put:
      tags:
      - BQ - Troubleshooting
      summary: RqBQ Request manual intervention to a troubleshooting action
      description: RqBQ Request manual intervention to a troubleshooting action
      operationId: RequestTroubleshooting
      parameters:
      - $ref: '#/components/parameters/ContactCenterManagementID'
      - $ref: '#/components/parameters/TroubleshootingID'
      requestBody:
        $ref: '#/components/requestBodies/Troubleshooting'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Troubleshooting'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ContactCenterManagement/{contactcentermanagementId}/Troubleshooting/{troubleshootingId}/Retrieve:
    get:
      tags:
      - BQ - Troubleshooting
      summary: ReBQ Retrieve details about troubleshooting activity
      description: ReBQ Retrieve details about troubleshooting activity
      operationId: RetrieveTroubleshooting
      parameters:
      - $ref: '#/components/parameters/ContactCenterManagementID'
      - $ref: '#/components/parameters/TroubleshootingID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Troubleshooting'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ContactCenterManagementPlan:
      type: object
      properties:
        ContactCenterManagementPlanPeriod:
          type: string
        ContactCenterUsagePoliciesAndGuidelines:
          type: string
        ContactCenterServicePerformanceGoals:
          type: string
        ContactCenterServiceSchedule:
          type: string
        ContactCenterServiceOperatingConfiguration:
          type: string
        ContactCenterResourcePlan:
          type: string
        ContactCenterTrainingPlan:
          type: string
    Troubleshooting:
      type: object
      properties:
        ContactCenterProductionIssueRecord:
          type: string
        ContactCenterIssueAnalysisAndRecommendedResponse:
          type: string
    Performance:
      type: object
      properties:
        ContactCenterPositionUtilization:
          type: string
        ContactCenterLoadingProjections:
          type: string
        ContactCenterServiceStatistics:
          type: string
        ContactCenterServiceStatisticType:
          type: string
        ContactCenterServiceStatisticValue:
          type: string
        ContactCenterServiceStatisticInterpretation:
          type: string
        ContactCenterServiceStatisticRecommendation:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    ContactCenterManagementID:
      name: contactcentermanagementId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    TroubleshootingID:
      name: troubleshootingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    PerformanceID:
      name: performanceId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    ContactCenterManagementPlan:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ContactCenterManagementPlan'
    Performance:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Performance'
    Troubleshooting:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Troubleshooting'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
