openapi: 3.0.1
info:
  title: Corporate Treasury
  description: This service domain orchestrates the consolidation and presentation of summary transaction details in order to assemble a timely and accurate view of the overall treasury position of the Bank at any one time. It is also responsible for determining the different interest and exchange rates applied to different products and services within the bank
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/CorporateTreasury/10.0.0
paths:
  /CorporateTreasury/{corporatetreasuryId}/Update:
    put:
      tags:
      - CR - CorporateTreasuryManagementPlan
      summary: UpCR Update the corporate treasury plan
      description: UpCR Update the corporate treasury plan
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/CorporateTreasuryID'
      requestBody:
        $ref: '#/components/requestBodies/UpdateCorporateTreasuryManagementPlanRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCorporateTreasuryManagementPlanResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTreasury/{corporatetreasuryId}/Retrieve:
    get:
      tags:
      - CR - CorporateTreasuryManagementPlan
      summary: ReCR Retrieve details about the corporate treasury plan
      description: ReCR Retrieve details about the corporate treasury plan
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/CorporateTreasuryID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorporateTreasuryManagementPlan'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTreasury/{corporatetreasuryId}/Liquidity/{liquidityId}/Capture:
    put:
      tags:
      - BQ - Liquidity
      summary: CaBQ Capture transactions feeding into liquidity analysis
      description: CaBQ Capture transactions feeding into liquidity analysis
      operationId: CaptureLiquidity
      parameters:
      - $ref: '#/components/parameters/CorporateTreasuryID'
      - $ref: '#/components/parameters/LiquidityID'
      requestBody:
        $ref: '#/components/requestBodies/CaptureLiquidityRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTreasury/{corporatetreasuryId}/Liquidity/{liquidityId}/Retrieve:
    get:
      tags:
      - BQ - Liquidity
      summary: ReBQ Retrieve liquidity analysis details
      description: ReBQ Retrieve liquidity analysis details
      operationId: RetrieveLiquidity
      parameters:
      - $ref: '#/components/parameters/CorporateTreasuryID'
      - $ref: '#/components/parameters/LiquidityID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveLiquidityResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTreasury/{corporatetreasuryId}/TacticalFunding/{tacticalfundingId}/Retrieve:
    get:
      tags:
      - BQ - TacticalFunding
      summary: ReBQ Retrieve tactical funding details
      description: ReBQ Retrieve tactical funding details
      operationId: RetrieveTacticalFunding
      parameters:
      - $ref: '#/components/parameters/CorporateTreasuryID'
      - $ref: '#/components/parameters/TacticalFundingID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TacticalFunding'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTreasury/{corporatetreasuryId}/StrategicFunding/{strategicfundingId}/Capture:
    put:
      tags:
      - BQ - StrategicFunding
      summary: CaBQ Capture details of large strategic transactions
      description: CaBQ Capture details of large strategic transactions
      operationId: CaptureStrategicFunding
      parameters:
      - $ref: '#/components/parameters/CorporateTreasuryID'
      - $ref: '#/components/parameters/StrategicFundingID'
      requestBody:
        $ref: '#/components/requestBodies/CaptureStrategicFundingRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTreasury/{corporatetreasuryId}/StrategicFunding/{strategicfundingId}/Retrieve:
    get:
      tags:
      - BQ - StrategicFunding
      summary: ReBQ Retrieve strategic funding details
      description: ReBQ Retrieve strategic funding details
      operationId: RetrieveStrategicFunding
      parameters:
      - $ref: '#/components/parameters/CorporateTreasuryID'
      - $ref: '#/components/parameters/StrategicFundingID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StrategicFunding'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTreasury/{corporatetreasuryId}/Securitization/{securitizationId}/Update:
    put:
      tags:
      - BQ - Securitization
      summary: UpBQ Update securitization tranche and task details
      description: UpBQ Update securitization tranche and task details
      operationId: UpdateSecuritization
      parameters:
      - $ref: '#/components/parameters/CorporateTreasuryID'
      - $ref: '#/components/parameters/SecuritizationID'
      requestBody:
        $ref: '#/components/requestBodies/UpdateSecuritizationRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSecuritizationResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTreasury/{corporatetreasuryId}/Securitization/{securitizationId}/Retrieve:
    get:
      tags:
      - BQ - Securitization
      summary: ReBQ Retrieve securitization tranche and task related details
      description: ReBQ Retrieve securitization tranche and task related details
      operationId: RetrieveSecuritization
      parameters:
      - $ref: '#/components/parameters/CorporateTreasuryID'
      - $ref: '#/components/parameters/SecuritizationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Securitization'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTreasury/{corporatetreasuryId}/BankRates/{bankratesId}/Retrieve:
    get:
      tags:
      - BQ - BankRates
      summary: ReBQ Retrieve bank rate table and details
      description: ReBQ Retrieve bank rate table and details
      operationId: RetrieveBankRates
      parameters:
      - $ref: '#/components/parameters/CorporateTreasuryID'
      - $ref: '#/components/parameters/BankRatesID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveBankRatesResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CorporateTreasuryManagementPlan:
      type: object
      properties:
        TreasuryPlanningPoliciesAndGuidelines:
          type: string
        TreasuryPlanOperatingParameters:
          type: string
        TreasuryPlanGoals:
          type: string
        EnterpriseFinancialStatements:
          type: string
        EnterpriseBalanceSheetDetailedContent:
          type: string
        EnterpriseBankAccountingAndCashManagementRecords:
          type: string
        CapitalOrWholesaleMarketTransactions:
          type: string
        CurrencyandRateRiskAnalysis:
          type: object
    StrategicFunding:
      type: object
      properties:
        FinancialPerformanceandBalanceSheetProjections:
          type: string
        ECMAndDCMMarketTransactions:
          type: string
        StrategicInvestmentHoldings/Transactions:
          type: string
        EnterpriseBalanceSheetPositions:
          type: string
        StrategicFundingResolutionTask:
          type: string
    Securitization:
      type: object
      properties:
        BankSecuritizationPoliciesandguidelines:
          type: string
        SecuritizationTrancheReference:
          type: object
        SecuritizationTrancheRecord:
          type: string
        SecuritizationTask:
          type: string
    Liquidity:
      type: object
      properties:
        EnterpriseLiquidity/CashManagementAnalysis:
          type: string
        EnterpriseLargePaymentTransactionRecords:
          type: string
        BusinessUnitFinancialReports:
          type: string
        LiquidityResolutionTask:
          type: string
    BankRates:
      type: object
      properties:
        BankRateType:
          type: string
        BankRateValue:
          type: object
        BankRateValueDate:
          type: string
        BankRateValueHistory:
          type: object
        BankRateRecordReference:
          type: object
        BankRateRecord:
          type: object
        BankRateRecordDate:
          type: string
    TacticalFunding:
      type: object
      properties:
        CapitalAdequacyRequirements:
          type: string
        BankPositionsandHedgingRequirements:
          type: string
        EnterpriseBalanceSheetPositions:
          type: string
        TacticalFundingResolutionTask:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    UpdateCorporateTreasuryManagementPlanRequest:
      type: object
      properties:
        CorporateTreasuryManagementPlan:
          type: object
          properties:
            TreasuryPlanningPoliciesAndGuidelines:
              type: string
            TreasuryPlanOperatingParameters:
              type: string
            TreasuryPlanGoals:
              type: string
    UpdateCorporateTreasuryManagementPlanResponse:
      type: object
      properties:
        CorporateTreasuryManagementPlan:
          type: object
          properties:
            TreasuryPlanningPoliciesAndGuidelines:
              type: string
            TreasuryPlanOperatingParameters:
              type: string
            TreasuryPlanGoals:
              type: string
    CaptureLiquidityRequest:
      type: object
      properties:
        Liquidity:
          type: object
          properties:
            EnterpriseLargePaymentTransactionRecords:
              type: string
    RetrieveLiquidityResponse:
      type: object
      properties:
        CorporateTreasuryManagementPlan:
          type: object
          properties:
            EnterpriseBankAccountingAndCashManagementRecords:
              type: string
            CurrencyandRateRiskAnalysis:
              type: object
        Liquidity:
          type: object
          properties:
            EnterpriseLiquidityOrCashManagementAnalysis:
              type: string
            EnterpriseLargePaymentTransactionRecords:
              type: string
            BusinessUnitFinancialReports:
              type: string
            LiquidityResolutionTask:
              type: string
    CaptureStrategicFundingRequest:
      type: object
      properties:
        StrategicFunding:
          type: object
          properties:
            ECMAndDCMMarketTransactions:
              type: string
            StrategicInvestmentHoldingsOrTransactions:
              type: string
    UpdateSecuritizationRequest:
      type: object
      properties:
        Securitization:
          type: object
          properties:
            SecuritizationTrancheRecord:
              type: string
            SecuritizationTask:
              type: string
    UpdateSecuritizationResponse:
      type: object
      properties:
        Securitization:
          type: object
          properties:
            SecuritizationTrancheRecord:
              type: string
            SecuritizationTask:
              type: string
    RetrieveBankRatesResponse:
      type: object
      properties:
        BankRates:
          type: object
          properties:
            BankRateType:
              type: string
            BankRateValue:
              type: object
            BankRateValueDate:
              type: string
            BankRateValueHistory:
              type: object
            BankRateRecordReference:
              type: object
            BankRateRecordDate:
              type: string
  parameters:
    CorporateTreasuryID:
      name: corporatetreasuryId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    StrategicFundingID:
      name: strategicfundingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    SecuritizationID:
      name: securitizationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    LiquidityID:
      name: liquidityId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    BankRatesID:
      name: bankratesId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    TacticalFundingID:
      name: tacticalfundingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    UpdateCorporateTreasuryManagementPlanRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateCorporateTreasuryManagementPlanRequest'
    CaptureLiquidityRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CaptureLiquidityRequest'
    CaptureStrategicFundingRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CaptureStrategicFundingRequest'
    UpdateSecuritizationRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateSecuritizationRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
