openapi: 3.0.1
info:
  title: Corporate Tax Advisory
  description: A fee or commission based product providing tax specific assessments, advice and guidance for corporate customers
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/CorporateTaxAdvisory/10.0.0
paths:
  /CorporateTaxAdvisory/Initiate:
    post:
      tags:
      - CR - CorporateTaxAdvisoryFacility
      summary: InCR Initiate a corporate tax advisory service
      description: InCR Initiate a corporate tax advisory service
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/CorporateTaxAdvisoryFacility'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorporateTaxAdvisoryFacility'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/Update:
    put:
      tags:
      - CR - CorporateTaxAdvisoryFacility
      summary: UpCR Update details for a corporate tax advisory service
      description: UpCR Update details for a corporate tax advisory service
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      requestBody:
        $ref: '#/components/requestBodies/CorporateTaxAdvisoryFacility'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorporateTaxAdvisoryFacility'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/Request:
    put:
      tags:
      - CR - CorporateTaxAdvisoryFacility
      summary: RqCR Request manual intervention during the advisory service
      description: RqCR Request manual intervention during the advisory service
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      requestBody:
        $ref: '#/components/requestBodies/CorporateTaxAdvisoryFacility'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorporateTaxAdvisoryFacility'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/Retrieve:
    get:
      tags:
      - CR - CorporateTaxAdvisoryFacility
      summary: ReCR Retrieve details about a corporate tax advisory service arrangement
      description: ReCR Retrieve details about a corporate tax advisory service arrangement
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CorporateTaxAdvisoryFacility'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/TaxOptimization/Initiate:
    post:
      tags:
      - BQ - TaxOptimization
      summary: InBQ Initiate a corporate tax optimization advisory session
      description: InBQ Initiate a corporate tax optimization advisory session
      operationId: InitiateTaxOptimization
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      requestBody:
        $ref: '#/components/requestBodies/InitiateTaxOptimizationRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateTaxOptimizationResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/TaxOptimization/{taxoptimizationId}/Update:
    put:
      tags:
      - BQ - TaxOptimization
      summary: UpBQ Update details about a corporate tax optimization advisory session
      description: UpBQ Update details about a corporate tax optimization advisory session
      operationId: UpdateTaxOptimization
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      - $ref: '#/components/parameters/TaxOptimizationID'
      requestBody:
        $ref: '#/components/requestBodies/TaxOptimization'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxOptimization'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/TaxOptimization/{taxoptimizationId}/Request:
    put:
      tags:
      - BQ - TaxOptimization
      summary: RqBQ Request manual intervention in a session
      description: RqBQ Request manual intervention in a session
      operationId: RequestTaxOptimization
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      - $ref: '#/components/parameters/TaxOptimizationID'
      requestBody:
        $ref: '#/components/requestBodies/TaxOptimization'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxOptimization'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/TaxOptimization/{taxoptimizationId}/Retrieve:
    get:
      tags:
      - BQ - TaxOptimization
      summary: ReBQ Retrieve details about a corporate tax optimization advisory session
      description: ReBQ Retrieve details about a corporate tax optimization advisory session
      operationId: RetrieveTaxOptimization
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      - $ref: '#/components/parameters/TaxOptimizationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxOptimization'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/ServiceFees/Initiate:
    post:
      tags:
      - BQ - ServiceFees
      summary: InBQ Initialize service fee processing for corporate tax advisory services
      description: InBQ Initialize service fee processing for corporate tax advisory services
      operationId: InitiateServiceFees
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      requestBody:
        $ref: '#/components/requestBodies/ServiceFees'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceFees'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/ServiceFees/{servicefeesId}/Update:
    put:
      tags:
      - BQ - ServiceFees
      summary: UpBQ Update details of service fees for corporate tax advisory services
      description: UpBQ Update details of service fees for corporate tax advisory services
      operationId: UpdateServiceFees
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      - $ref: '#/components/parameters/ServiceFeesID'
      requestBody:
        $ref: '#/components/requestBodies/ServiceFees'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceFees'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/ServiceFees/{servicefeesId}/Execute:
    put:
      tags:
      - BQ - ServiceFees
      summary: ExBQ Execute/apply a fee for a corporate tax advisory session
      description: ExBQ Execute/apply a fee for a corporate tax advisory session
      operationId: ExecuteServiceFees
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      - $ref: '#/components/parameters/ServiceFeesID'
      requestBody:
        $ref: '#/components/requestBodies/ServiceFees'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceFees'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CorporateTaxAdvisory/{corporatetaxadvisoryId}/ServiceFees/{servicefeesId}/Retrieve:
    get:
      tags:
      - BQ - ServiceFees
      summary: ReBQ Retrieve details about service fees for a corporate tax advisory service
      description: ReBQ Retrieve details about service fees for a corporate tax advisory service
      operationId: RetrieveServiceFees
      parameters:
      - $ref: '#/components/parameters/CorporateTaxAdvisoryID'
      - $ref: '#/components/parameters/ServiceFeesID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceFees'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CorporateTaxAdvisoryFacility:
      type: object
      properties:
        ProductInstanceReference:
          type: object
        CustomerReference:
          type: object
        BankBranchOrLocationReference:
          type: object
        EmployeeOrBusinessUnitReference:
          type: object
        CorporateTaxAdvisoryWorkProducts:
          type: string
        DocumentDirectoryEntryInstanceReference:
          type: object
        CorporateTaxAdviceSessionSchedule:
          type: string
        CorporateTaxAdviceConsolidationRecord:
          type: string
        DateType:
          type: string
        Date:
          type: string
    ServiceFees:
      type: object
      properties:
        FeeApplicationRecord:
          type: string
        FeeTransaction:
          type: string
        FeeTransactionDescription:
          type: string
        FeeTransactionType:
          type: string
        FeeTransactionCharge:
          type: string
    TaxOptimization:
      type: object
      properties:
        ProductandServiceReference:
          type: object
        SpecialistSupportTask:
          type: string
        SpecialistEmployee/BusinessUnitReference:
          type: object
        SpecialistAdviceDescription:
          type: string
        SpecialistAdviceCharge:
          type: string
        TaxOptimizationGuidanceAdviceResult:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    InitiateTaxOptimizationRequest:
      type: object
      properties:
        CorporateTaxAdvisoryFacility:
          type: object
          properties:
            ProductInstanceReference:
              type: object
            CustomerReference:
              type: object
            BankBranchOrLocationReference:
              type: object
            EmployeeOrBusinessUnitReference:
              type: object
            CorporateTaxAdvisoryWorkProducts:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorporateTaxAdviceSessionSchedule:
              type: string
            DateType:
              type: string
        TaxOptimization:
          type: object
          properties:
            ProductandServiceReference:
              type: object
            SpecialistSupportTask:
              type: string
            SpecialistEmployeeOrBusinessUnitReference:
              type: object
    InitiateTaxOptimizationResponse:
      type: object
      properties:
        CorporateTaxAdvisoryFacility:
          type: object
          properties:
            BankBranchOrLocationReference:
              type: object
            EmployeeOrBusinessUnitReference:
              type: object
            CorporateTaxAdvisoryWorkProducts:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            CorporateTaxAdviceSessionSchedule:
              type: string
            CorporateTaxAdviceConsolidationRecord:
              type: string
            DateType:
              type: string
        TaxOptimization:
          type: object
          properties:
            SpecialistSupportTask:
              type: string
            SpecialistEmployeeOrBusinessUnitReference:
              type: object
            SpecialistAdviceDescription:
              type: string
            SpecialistAdviceCharge:
              type: string
            TaxOptimizationGuidanceAdviceResult:
              type: string
  parameters:
    CorporateTaxAdvisoryID:
      name: corporatetaxadvisoryId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ServiceFeesID:
      name: servicefeesId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    TaxOptimizationID:
      name: taxoptimizationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    CorporateTaxAdvisoryFacility:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CorporateTaxAdvisoryFacility'
    InitiateTaxOptimizationRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateTaxOptimizationRequest'
    TaxOptimization:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TaxOptimization'
    ServiceFees:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceFees'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
