openapi: 3.0.1
info:
  title: Credit Card Position Keeping
  description: Maintain a log of credit card bookings and authorizations for operational and management information, tracking and reconciliation purposes.
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/CreditCardPositionKeeping/10.0.0
paths:
  /CreditCardPositionKeeping/{creditcardpositionkeepingId}/Capture:
    put:
      tags:
      - CR - CreditCardPositionLog
      summary: Capture Credit Card Position Log
      description: Capture Credit Card Position Log
      operationId: Capture
      parameters:
      - $ref: '#/components/parameters/CreditCardPositionKeepingID'
      requestBody:
        $ref: '#/components/requestBodies/CreditCardPositionLog'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardPositionLog'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditCardPositionKeeping/{creditcardpositionkeepingId}/Control:
    put:
      tags:
      - CR - CreditCardPositionLog
      summary: Control Credit Card Position Log
      description: Control Credit Card Position Log
      operationId: Control
      parameters:
      - $ref: '#/components/parameters/CreditCardPositionKeepingID'
      requestBody:
        $ref: '#/components/requestBodies/CreditCardPositionLog'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardPositionLog'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditCardPositionKeeping/Initiate:
    post:
      tags:
      - CR - CreditCardPositionLog
      summary: Initiate Credit Card Position Log
      description: Initiate Credit Card Position Log
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/CreditCardPositionLog'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardPositionLog'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditCardPositionKeeping/{creditcardpositionkeepingId}/Notify:
    get:
      tags:
      - CR - CreditCardPositionLog
      summary: Notify Credit Card Position Log
      description: Notify Credit Card Position Log
      operationId: Notify
      parameters:
      - $ref: '#/components/parameters/CreditCardPositionKeepingID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardPositionLog'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditCardPositionKeeping/{creditcardpositionkeepingId}/Retrieve:
    get:
      tags:
      - CR - CreditCardPositionLog
      summary: Retrieve Credit Card Position Log
      description: Retrieve Credit Card Position Log
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/CreditCardPositionKeepingID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardPositionLog'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditCardPositionKeeping/{creditcardpositionkeepingId}/Update:
    put:
      tags:
      - CR - CreditCardPositionLog
      summary: Update Credit Card Position Log
      description: Update Credit Card Position Log
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/CreditCardPositionKeepingID'
      requestBody:
        $ref: '#/components/requestBodies/CreditCardPositionLog'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardPositionLog'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditCardPositionKeeping/{creditcardpositionkeepingId}/CardTransactionEvent/{cardtransactioneventId}/Capture:
    put:
      tags:
      - BQ - CardTransactionEvent
      summary: Capture Card Transaction Event
      description: Capture Card Transaction Event
      operationId: CaptureCardTransactionEvent
      parameters:
      - $ref: '#/components/parameters/CreditCardPositionKeepingID'
      - $ref: '#/components/parameters/CardTransactionEventID'
      requestBody:
        $ref: '#/components/requestBodies/CardTransactionEvent'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardTransactionEvent'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditCardPositionKeeping/{creditcardpositionkeepingId}/CardTransactionEvent/{cardtransactioneventId}/Notify:
    get:
      tags:
      - BQ - CardTransactionEvent
      summary: Notify Card Transaction Event
      description: Notify Card Transaction Event
      operationId: NotifyCardTransactionEvent
      parameters:
      - $ref: '#/components/parameters/CreditCardPositionKeepingID'
      - $ref: '#/components/parameters/CardTransactionEventID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardTransactionEvent'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditCardPositionKeeping/{creditcardpositionkeepingId}/CardTransactionEvent/{cardtransactioneventId}/Retrieve:
    get:
      tags:
      - BQ - CardTransactionEvent
      summary: Retrieve Card Transaction Event
      description: Retrieve Card Transaction Event
      operationId: RetrieveCardTransactionEvent
      parameters:
      - $ref: '#/components/parameters/CreditCardPositionKeepingID'
      - $ref: '#/components/parameters/CardTransactionEventID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardTransactionEvent'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditCardPositionKeeping/{creditcardpositionkeepingId}/CardTransactionEvent/{cardtransactioneventId}/Update:
    put:
      tags:
      - BQ - CardTransactionEvent
      summary: Update Card Transaction Event
      description: Update Card Transaction Event
      operationId: UpdateCardTransactionEvent
      parameters:
      - $ref: '#/components/parameters/CreditCardPositionKeepingID'
      - $ref: '#/components/parameters/CardTransactionEventID'
      requestBody:
        $ref: '#/components/requestBodies/CardTransactionEvent'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardTransactionEvent'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CreditCardPositionLog:
      type: object
      properties:
        CreditCardPositionLogParameterType:
          type: string
          description: A Classification value that distinguishes between business service events logged within Credit Card Position Log
        CreditCardPositionLogSelectedOption:
          type: string
          description: A selected optional business service as subject matter of Credit Card Position Log
        CreditCardPositionLogType:
          type: string
          description: The type of Credit Card Position Log
        CreditCardPositionLogSchedule:
          type: object
          description: Timetable to track Credit Card Position Log
        CreditCardPositionLogUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events  of Credit Card Position Log
        CreditCardPositionLogUpdateLog:
          type: string
          description: Reference to the log of (update) ativities/events of Credit Card Position Log
        CreditCardPositionLogAssociatedParty:
          type: object
          description: Reference to the party who is involved in Credit Card Position Log
        CreditCardPositionLogBusinessUnitReference:
          type: object
          description: Reference to the business unit which is involved in Credit Card Position Log
        CreditCardPositionLogCustomerReference:
          type: object
          description: Reference to the customer who is involved in Credit Card Position Log
        CreditCardPositionLogServiceConfiguration:
          type: string
          description: The configuration of Credit Card Position Log
        CreditCardPositionLogPosition:
          type: string
          description: The position of Credit Card Position Log
        CreditCardPositionLogPositionType:
          type: string
          description: A classification value expressing the kind of position withing the Credit Card Position Log
        CreditCardPositionLogPositionLimitTime:
          type: string
          description: Reference to the time limitation related to the position of Credit Card Position Log
        CreditCardPositionLogReference:
          type: string
          description: An unique reference to an item or an occurrence of Credit Card Position Log
    CardTransactionEvent:
      type: object
      properties:
        Preconditions:
          type: object
          description: The required status/situation before the event is captured
        Schedule:
          type: object
          description: The timing and key actions/milestones involved in capturing the event
        BusinessService:
          type: object
          description: The Card Transaction Event specific Business Service
        Postconditions:
          type: object
          description: The completion status once the event has been captured
        CreditCardPositionLogReference:
          type: string
          description: Reference to Card Transaction Event
        CardTransactionEventReference:
          type: string
          description: Reference to Card Transaction Event
        CardTransactionEventType:
          type: string
          description: The type of Card Transaction Event
    CreditCardPositionKeepingOutcome:
      type: object
      properties:
        CreditCardPositionKeepingIncident:
          type: string
          description: ''
        CreditCardPositionKeepingLog:
          type: string
          description: ''
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: NA
        status:
          type: string
          description: NA
        message:
          type: string
          description: NA
  parameters:
    CreditCardPositionKeepingID:
      name: creditcardpositionkeepingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    CardTransactionEventID:
      name: cardtransactioneventId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    CreditCardPositionKeepingOutcomeID:
      name: creditcardpositionkeepingoutcomeId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    CreditCardPositionLog:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreditCardPositionLog'
    CardTransactionEvent:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CardTransactionEvent'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
