openapi: 3.0.1
info:
  title: Document Library
  description: This Service Domain provides a directory based categorization and storage mechanism for documents created and referenced by the bank
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/DocumentLibrary/10.0.0
paths:
  /DocumentLibrary/Register:
    post:
      tags:
      - CR - DocumentDirectoryEntry
      summary: InCR Register a document in the central catalog
      description: InCR Register a document in the central catalog
      operationId: Register
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/DocumentDirectoryEntry'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentDirectoryEntry'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /DocumentLibrary/{documentlibraryId}/Update:
    put:
      tags:
      - CR - DocumentDirectoryEntry
      summary: UpCR Update details about a document in the catalog
      description: UpCR Update details about a document in the catalog
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/DocumentLibraryID'
      requestBody:
        $ref: '#/components/requestBodies/DocumentDirectoryEntry'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentDirectoryEntry'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /DocumentLibrary/{documentlibraryId}/Request:
    put:
      tags:
      - CR - DocumentDirectoryEntry
      summary: Request Document Directory Entry
      description: Request Document Directory Entry
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/DocumentLibraryID'
      requestBody:
        $ref: '#/components/requestBodies/DocumentDirectoryEntry'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentDirectoryEntry'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /DocumentLibrary/{documentlibraryId}/Retrieve:
    get:
      tags:
      - CR - DocumentDirectoryEntry
      summary: ReCR Retrieve details about a document
      description: ReCR Retrieve details about a document
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/DocumentLibraryID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentDirectoryEntry'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    DocumentDirectoryEntry:
      type: object
      properties:
        DocumentName:
          type: string
        LocationReference:
          type: object
        BusinessUnitOrEmployeeReference:
          type: object
        ProductandServiceReference:
          type: object
        ProductandServiceActionReference:
          type: object
        DocumentCreationDate:
          type: string
        DocumentCaptureDateOrTime:
          type: string
        DocumentTypeOrDescription:
          type: string
        DocumentContent:
          type: string
        DocumentProvisioningHistory:
          type: string
        DocumentProvisioningRequest:
          type: string
        DocumentProvisioningSchedule:
          type: string
        DocumentProvisioningResult:
          type: string
        DocumentVersionHistory:
          type: string
        DocumentVersion:
          type: string
        DocumentVersionDate:
          type: string
        DocumentVerificationHistory:
          type: string
        DocumentVerificationTaskDescription:
          type: string
        DocumentVerificationServiceProviderReference:
          type: object
        DocumentVerificationTaskResult:
          type: string
        DocumentAmendmentHistory:
          type: string
        DocumentAmendmentDescription:
          type: string
        DocumentAmendmentResult:
          type: string
        DocumentUpdateHistory:
          type: string
        DocumentUpdateDescription:
          type: string
        DocumentUpdateResult:
          type: string
        DocumentArchivingHistory:
          type: string
        DocumentArchivingAction:
          type: string
        DocumentArchiveReference:
          type: object
        DocumentMediaOrFormat:
          type: string
        DocumentSubjectReference:
          type: object
        DocumentLocation:
          type: string
        DocumentStatus:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    DocumentLibraryID:
      name: documentlibraryId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    DocumentDirectoryEntry:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DocumentDirectoryEntry'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
