openapi: 3.0.1
info:
  title: Financial Market Research
  description: The service domain consolidates external financial market research
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/FinancialMarketResearch/10.0.0
paths:
  /FinancialMarketResearch/Register:
    post:
      tags:
      - CR - FinancialMarketResearchDirectoryEntry
      summary: InCR Register or establish a financial market research viewpoint
      description: InCR Register or establish a financial market research viewpoint
      operationId: Register
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketResearchDirectoryEntry'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketResearchDirectoryEntry'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketResearch/{financialmarketresearchId}/Update:
    put:
      tags:
      - CR - FinancialMarketResearchDirectoryEntry
      summary: UpCR Update the details or make-up of a financial market research viewpoint
      description: UpCR Update the details or make-up of a financial market research viewpoint
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/FinancialMarketResearchID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketResearchDirectoryEntry'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketResearchDirectoryEntry'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketResearch/{financialmarketresearchId}/Execute:
    put:
      tags:
      - CR - FinancialMarketResearchDirectoryEntry
      summary: ExCR Automatically extract details of a maintained financial market research viewpoint
      description: ExCR Automatically extract details of a maintained financial market research viewpoint
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/FinancialMarketResearchID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketResearchDirectoryEntry'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketResearchDirectoryEntry'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketResearch/{financialmarketresearchId}/Request:
    put:
      tags:
      - CR - FinancialMarketResearchDirectoryEntry
      summary: RqCR Request a viewpoint is refreshed or adjusted in some manner
      description: RqCR Request a viewpoint is refreshed or adjusted in some manner
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/FinancialMarketResearchID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketResearchDirectoryEntry'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketResearchDirectoryEntry'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketResearch/{financialmarketresearchId}/Retrieve:
    get:
      tags:
      - CR - FinancialMarketResearchDirectoryEntry
      summary: ReCR Retrieve details about and the content of a maintained financial market research viewpoint
      description: ReCR Retrieve details about and the content of a maintained financial market research viewpoint
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/FinancialMarketResearchID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketResearchDirectoryEntry'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    FinancialMarketResearchDirectoryEntry:
      type: object
      properties:
        FinancialMarketResearchViewpointType:
          type: string
        FinancialMarketResearchViewpointDescription:
          type: string
        ReferencedFinancialMarketResearchRecord:
          type: string
        FinancialMarketResearchReportTypeReference:
          type: string
        FinancialMarketResearchReportTypeDefinition:
          type: string
        FinancialMarketResearchReportVersionOrPeriod:
          type: string
        FinancialMarketResearchReport:
          type: string
        FinancialMarketResearchViewpointUsage:
          type: string
        FinancialMarketResearchReportRequest:
          type: string
        EmployeeOrBusinessUnitReference:
          type: object
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    FinancialMarketResearchID:
      name: financialmarketresearchId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    FinancialMarketResearchDirectoryEntry:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FinancialMarketResearchDirectoryEntry'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
