openapi: 3.0.1
info:
  title: Financial Gateway
  description: This service domain operates automated message interfaces to secure networks such as SWIFT, TELEX, ACH and Financial Market/Exchange reporting services
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/FinancialGateway/10.0.0
paths:
  /FinancialGateway/Initiate:
    post:
      tags:
      - CR - FinancialGatewayOperatingSession
      summary: InCR Initiate the financial gateway service session
      description: InCR Initiate the financial gateway service session
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/FinancialGatewayOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialGatewayOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialGateway/{financialgatewayId}/Update:
    put:
      tags:
      - CR - FinancialGatewayOperatingSession
      summary: UpCR Update the gateway service details
      description: UpCR Update the gateway service details
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/FinancialGatewayID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialGatewayOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialGatewayOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialGateway/{financialgatewayId}/Request:
    put:
      tags:
      - CR - FinancialGatewayOperatingSession
      summary: RqCR Report an issue with the production service
      description: RqCR Report an issue with the production service
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/FinancialGatewayID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialGatewayOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialGatewayOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialGateway/{financialgatewayId}/Retrieve:
    get:
      tags:
      - CR - FinancialGatewayOperatingSession
      summary: ReCR Retrieve details and statistics relating to a session
      description: ReCR Retrieve details and statistics relating to a session
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/FinancialGatewayID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialGatewayOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialGateway/{financialgatewayId}/Inbound/Initiate:
    post:
      tags:
      - BQ - Inbound
      summary: InBQ Initiate inbound financial message handling
      description: InBQ Initiate inbound financial message handling
      operationId: InitiateInbound
      parameters:
      - $ref: '#/components/parameters/FinancialGatewayID'
      requestBody:
        $ref: '#/components/requestBodies/InitiateInboundRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateInboundResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialGateway/{financialgatewayId}/Inbound/{inboundId}/Retrieve:
    get:
      tags:
      - BQ - Inbound
      summary: ReBQ Retrieve details about an inbound financial message
      description: ReBQ Retrieve details about an inbound financial message
      operationId: RetrieveInbound
      parameters:
      - $ref: '#/components/parameters/FinancialGatewayID'
      - $ref: '#/components/parameters/InboundID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveInboundResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialGateway/{financialgatewayId}/Outbound/Initiate:
    post:
      tags:
      - BQ - Outbound
      summary: InBQ Initiate outbound financial message handling
      description: InBQ Initiate outbound financial message handling
      operationId: InitiateOutbound
      parameters:
      - $ref: '#/components/parameters/FinancialGatewayID'
      requestBody:
        $ref: '#/components/requestBodies/InitiateOutboundRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateOutboundResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialGateway/{financialgatewayId}/Outbound/{outboundId}/Retrieve:
    get:
      tags:
      - BQ - Outbound
      summary: ReBQ Retrieve details about an outbound financial message
      description: ReBQ Retrieve details about an outbound financial message
      operationId: RetrieveOutbound
      parameters:
      - $ref: '#/components/parameters/FinancialGatewayID'
      - $ref: '#/components/parameters/OutboundID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveOutboundResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    FinancialGatewayOperatingSession:
      type: object
      properties:
        FinancialGatewayServiceType:
          type: string
        FinancialGatewayServiceSessionStatistics:
          type: string
        FinancialGatewayServiceSessionReportType:
          type: string
        FinancialGatewayServiceSessionReport:
          type: string
        FinancialGatewayServiceSessionDate:
          type: string
        FinancialGatewayServiceSessionIssueRecord:
          type: string
        EmployeeOrBusinessUnitReference:
          type: object
        MessageReference:
          type: object
        ProductionIssueType:
          type: string
        ProductionIssueDescription:
          type: string
        ProductionIssueDiagnosis:
          type: string
        ProductionIssueResolutionTask:
          type: string
        ProductionIssueRecord:
          type: string
        ProductionIssueStatus:
          type: string
    Inbound:
      type: object
      properties:
        FinancialGatewayInboundMessageType:
          type: string
        FinancialGatewayInboundMessageRecord:
          type: string
        FinancialGatewayInboundMessageReceiver:
          type: string
        FinancialGatewayInboundMessageStatus:
          type: string
    Outbound:
      type: object
      properties:
        FinancialGatewayOutboundMessageType:
          type: string
        FinancialGatewayOutboundMessageRecord:
          type: string
        FinancialGatewayOutboundMessageSender:
          type: string
        FinancialGatewayOutboundMessageReceiver:
          type: string
        FinancialGatewayOutboundMessageStatus:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    InitiateInboundRequest:
      type: object
      properties:
        FinancialGatewayOperatingSession:
          type: object
          properties:
            FinancialGatewayServiceType:
              type: string
            FinancialGatewayServiceSessionStatistics:
              type: string
        Inbound:
          type: object
          properties:
            FinancialGatewayInboundMessageType:
              type: string
            FinancialGatewayInboundMessageRecord:
              type: string
            FinancialGatewayInboundMessageReceiver:
              type: string
            FinancialGatewayInboundMessageStatus:
              type: string
    InitiateInboundResponse:
      type: object
      properties:
        FinancialGatewayOperatingSession:
          type: object
          properties:
            FinancialGatewayServiceSessionStatistics:
              type: string
        Inbound:
          type: object
          properties:
            FinancialGatewayInboundMessageStatus:
              type: string
    RetrieveInboundResponse:
      type: object
      properties:
        FinancialGatewayOperatingSession:
          type: object
          properties:
            FinancialGatewayServiceType:
              type: string
            FinancialGatewayServiceSessionStatistics:
              type: string
        Inbound:
          type: object
          properties:
            FinancialGatewayInboundMessageType:
              type: string
            FinancialGatewayInboundMessageRecord:
              type: string
            FinancialGatewayInboundMessageReceiver:
              type: string
            FinancialGatewayInboundMessageStatus:
              type: string
    InitiateOutboundRequest:
      type: object
      properties:
        FinancialGatewayOperatingSession:
          type: object
          properties:
            FinancialGatewayServiceType:
              type: string
            FinancialGatewayServiceSessionStatistics:
              type: string
        Outbound:
          type: object
          properties:
            FinancialGatewayOutboundMessageType:
              type: string
            FinancialGatewayOutboundMessageRecord:
              type: string
            FinancialGatewayOutboundMessageSender:
              type: string
            FinancialGatewayOutboundMessageReceiver:
              type: string
            FinancialGatewayOutboundMessageStatus:
              type: string
    InitiateOutboundResponse:
      type: object
      properties:
        FinancialGatewayOperatingSession:
          type: object
          properties:
            FinancialGatewayServiceSessionStatistics:
              type: string
        Outbound:
          type: object
          properties:
            FinancialGatewayOutboundMessageStatus:
              type: string
    RetrieveOutboundResponse:
      type: object
      properties:
        FinancialGatewayOperatingSession:
          type: object
          properties:
            FinancialGatewayServiceType:
              type: string
            FinancialGatewayServiceSessionStatistics:
              type: string
        Outbound:
          type: object
          properties:
            FinancialGatewayOutboundMessageType:
              type: string
            FinancialGatewayOutboundMessageRecord:
              type: string
            FinancialGatewayOutboundMessageSender:
              type: string
            FinancialGatewayOutboundMessageReceiver:
              type: string
            FinancialGatewayOutboundMessageStatus:
              type: string
  parameters:
    FinancialGatewayID:
      name: financialgatewayId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    InboundID:
      name: inboundId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    OutboundID:
      name: outboundId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    FinancialGatewayOperatingSession:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FinancialGatewayOperatingSession'
    InitiateInboundRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateInboundRequest'
    InitiateOutboundRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateOutboundRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
