openapi: 3.0.1
info:
  title: Financial Market Analysis
  description: Provide different types of financial market analysis using available financial market information and research
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/FinancialMarketAnalysis/10.0.0
paths:
  /FinancialMarketAnalysis/{financialmarketanalysisId}/Execute:
    put:
      tags:
      - CR - FinancialMarketAnalysis
      summary: ExCR Execute an available automated action for Financial Market Analysis
      description: ExCR Execute an available automated action for Financial Market Analysis
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/FinancialMarketAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketAnalysis/Initiate:
    post:
      tags:
      - CR - FinancialMarketAnalysis
      summary: InCR Instantiate a new Financial Market Analysis
      description: InCR Instantiate a new Financial Market Analysis
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketAnalysis/{financialmarketanalysisId}/Retrieve:
    get:
      tags:
      - CR - FinancialMarketAnalysis
      summary: ReCR Retrieve details about any aspect of Financial Market Analysis
      description: ReCR Retrieve details about any aspect of Financial Market Analysis
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/FinancialMarketAnalysisID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketAnalysis/{financialmarketanalysisId}/Request:
    put:
      tags:
      - CR - FinancialMarketAnalysis
      summary: RqCR Request manual intervention or a decision with respect to Financial Market Analysis
      description: RqCR Request manual intervention or a decision with respect to Financial Market Analysis
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/FinancialMarketAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketAnalysis/{financialmarketanalysisId}/Update:
    put:
      tags:
      - CR - FinancialMarketAnalysis
      summary: UpCR Update details relating to Financial Market Analysis
      description: UpCR Update details relating to Financial Market Analysis
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/FinancialMarketAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketAnalysis/{financialmarketanalysisId}/FinancialMarketInsight/{financialmarketinsightId}/Execute:
    put:
      tags:
      - BQ - FinancialMarketInsight
      summary: ExBQ Execute an available automated action for Financial Market Insight
      description: ExBQ Execute an available automated action for Financial Market Insight
      operationId: ExecuteFinancialMarketInsight
      parameters:
      - $ref: '#/components/parameters/FinancialMarketAnalysisID'
      - $ref: '#/components/parameters/FinancialMarketInsightID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketInsight'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketInsight'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketAnalysis/{financialmarketanalysisId}/FinancialMarketInsight/Initiate:
    post:
      tags:
      - BQ - FinancialMarketInsight
      summary: InBQ Instantiate a new Financial Market Insight
      description: InBQ Instantiate a new Financial Market Insight
      operationId: InitiateFinancialMarketInsight
      parameters:
      - $ref: '#/components/parameters/FinancialMarketAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketInsight'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketInsight'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketAnalysis/{financialmarketanalysisId}/FinancialMarketInsight/{financialmarketinsightId}/Retrieve:
    get:
      tags:
      - BQ - FinancialMarketInsight
      summary: ReBQ Retrieve details about any aspect of Financial Market Insight
      description: ReBQ Retrieve details about any aspect of Financial Market Insight
      operationId: RetrieveFinancialMarketInsight
      parameters:
      - $ref: '#/components/parameters/FinancialMarketAnalysisID'
      - $ref: '#/components/parameters/FinancialMarketInsightID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketInsight'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketAnalysis/{financialmarketanalysisId}/FinancialMarketInsight/{financialmarketinsightId}/Request:
    put:
      tags:
      - BQ - FinancialMarketInsight
      summary: RqBQ Request manual intervention or a decision with respect to Financial Market Insight
      description: RqBQ Request manual intervention or a decision with respect to Financial Market Insight
      operationId: RequestFinancialMarketInsight
      parameters:
      - $ref: '#/components/parameters/FinancialMarketAnalysisID'
      - $ref: '#/components/parameters/FinancialMarketInsightID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketInsight'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketInsight'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FinancialMarketAnalysis/{financialmarketanalysisId}/FinancialMarketInsight/{financialmarketinsightId}/Update:
    put:
      tags:
      - BQ - FinancialMarketInsight
      summary: UpBQ Update details relating to Financial Market Insight
      description: UpBQ Update details relating to Financial Market Insight
      operationId: UpdateFinancialMarketInsight
      parameters:
      - $ref: '#/components/parameters/FinancialMarketAnalysisID'
      - $ref: '#/components/parameters/FinancialMarketInsightID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialMarketInsight'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialMarketInsight'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    FinancialMarketAnalysis:
      type: object
      properties:
        FinancialMarketAnalysisParameterType:
          type: string
        FinancialMarketAnalysisSelectedOption:
          type: string
        FinancialMarketAnalysisRequest:
          type: string
        FinancialMarketAnalysisSchedule:
          type: string
        FinancialMarketAnalysisStatus:
          type: string
        FinancialMarketAnalysisUsageLog:
          type: string
        FinancialMarketAnalysisRequesterReference:
          type: object
    FinancialMarketInsight:
      type: object
      properties:
        FinancialMarketInsightPreconditions:
          type: string
        FinancialMarketInsightAnalysisSchedule:
          type: string
        FinancialMarketInsightVersionNumber:
          type: string
        FinancialMarketAnalysis:
          type: object
        FinancialMarketAnalysisServiceType:
          type: string
        FinancialMarketAnalysisServiceDescription:
          type: string
        FinancialMarketAnalysisServiceInputsandOuputs:
          type: string
        FinancialMarketAnalysisServiceWorkProduct:
          type: string
        FinancialMarketAnalysisServiceName:
          type: string
    FinancialMarketAnalysisOutcome:
      type: object
      properties:
        FinancialMarketAnalysisWorkProduct:
          type: string
        FinancialMarketAnalysisAnalysisType:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    FinancialMarketAnalysisID:
      name: financialmarketanalysisId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    FinancialMarketInsightID:
      name: financialmarketinsightId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    FinancialMarketAnalysisOutcomeID:
      name: financialmarketanalysisoutcomeId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    FinancialMarketAnalysis:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FinancialMarketAnalysis'
    FinancialMarketInsight:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FinancialMarketInsight'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
