openapi: 3.0.1
info:
  title: Guideline Compliance
  description: This service domain develops and applies a portfolio of guideline compliance tests to confirm adherence to bank and regulator imposed internal procedures. Tests may be made on complete transaction data or a meaningful samples as appropriate to mitigate exposure to non-compliant behaviors. Compliance checks may be in response to a schedule, a specific request as part of normal processing or may be initiated randomly as an oversight activity
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/GuidelineCompliance/10.0.0
paths:
  /GuidelineCompliance/Evaluate:
    post:
      tags:
      - CR - GuidelineComplianceAssessment
      summary: EvCR Start a guideline compliance evaluation assessment
      description: EvCR Start a guideline compliance evaluation assessment
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/EvaluateGuidelineComplianceAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateGuidelineComplianceAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /GuidelineCompliance/{guidelinecomplianceId}/Update:
    put:
      tags:
      - CR - GuidelineComplianceAssessment
      summary: UpCR Update submitted details or content for an on-going guideline compliance assessment
      description: UpCR Update submitted details or content for an on-going guideline compliance assessment
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/GuidelineComplianceID'
      requestBody:
        $ref: '#/components/requestBodies/UpdateGuidelineComplianceAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateGuidelineComplianceAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /GuidelineCompliance/{guidelinecomplianceId}/Retrieve:
    get:
      tags:
      - CR - GuidelineComplianceAssessment
      summary: ReCR Retrieve details and content from an active guideline compliance assessment
      description: ReCR Retrieve details and content from an active guideline compliance assessment
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/GuidelineComplianceID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GuidelineComplianceAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    GuidelineComplianceAssessment:
      type: object
      properties:
        GuidelineComplianceAssessmentType:
          type: string
        BusinessUnitReference:
          type: object
        ProductandServiceReference:
          type: object
        CustomerReference:
          type: object
        DocumentReference:
          type: object
        GuidelineComplianceAssessmentWorkProducts:
          type: string
        GuidelineComplianceAssessmentResult:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    EvaluateGuidelineComplianceAssessmentRequest:
      type: object
      properties:
        GuidelineComplianceAssessment:
          type: object
          properties:
            GuidelineComplianceAssessmentType:
              type: string
            BusinessUnitReference:
              type: object
            ProductandServiceReference:
              type: object
            CustomerReference:
              type: object
            DocumentReference:
              type: object
            GuidelineComplianceAssessmentWorkProducts:
              type: string
    EvaluateGuidelineComplianceAssessmentResponse:
      type: object
      properties:
        GuidelineComplianceAssessment:
          type: object
          properties:
            DocumentReference:
              type: object
            GuidelineComplianceAssessmentWorkProducts:
              type: string
            GuidelineComplianceAssessmentResult:
              type: string
    UpdateGuidelineComplianceAssessmentRequest:
      type: object
      properties:
        GuidelineComplianceAssessment:
          type: object
          properties:
            GuidelineComplianceAssessmentType:
              type: string
            BusinessUnitReference:
              type: object
            ProductandServiceReference:
              type: object
            CustomerReference:
              type: object
            DocumentReference:
              type: object
            GuidelineComplianceAssessmentWorkProducts:
              type: string
    UpdateGuidelineComplianceAssessmentResponse:
      type: object
      properties:
        GuidelineComplianceAssessment:
          type: object
          properties:
            GuidelineComplianceAssessmentType:
              type: string
            BusinessUnitReference:
              type: object
            ProductandServiceReference:
              type: object
            CustomerReference:
              type: object
            DocumentReference:
              type: object
            GuidelineComplianceAssessmentWorkProducts:
              type: string
  parameters:
    GuidelineComplianceID:
      name: guidelinecomplianceId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    EvaluateGuidelineComplianceAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateGuidelineComplianceAssessmentRequest'
    UpdateGuidelineComplianceAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateGuidelineComplianceAssessmentRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
