openapi: 3.0.1
info:
  title: Investment Portfolio Analysis
  description: Assess and report on investment portfolio make-up, valuation and performance
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/InvestmentPortfolioAnalysis/10.0.0
paths:
  /InvestmentPortfolioAnalysis/Evaluate:
    post:
      tags:
      - CR - ManagedInvestmentPortfolioAnalysis
      summary: EvCR perform an evaluation of an investment portfolio
      description: EvCR perform an evaluation of an investment portfolio
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/ManagedInvestmentPortfolioAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManagedInvestmentPortfolioAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InvestmentPortfolioAnalysis/{investmentportfolioanalysisId}/Execute:
    put:
      tags:
      - CR - ManagedInvestmentPortfolioAnalysis
      summary: ExCR Execute an automated task for a evaluation
      description: ExCR Execute an automated task for a evaluation
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/InvestmentPortfolioAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/ManagedInvestmentPortfolioAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManagedInvestmentPortfolioAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InvestmentPortfolioAnalysis/{investmentportfolioanalysisId}/Request:
    put:
      tags:
      - CR - ManagedInvestmentPortfolioAnalysis
      summary: RqCR Request manual intervention for an evaluation
      description: RqCR Request manual intervention for an evaluation
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/InvestmentPortfolioAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/ManagedInvestmentPortfolioAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManagedInvestmentPortfolioAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InvestmentPortfolioAnalysis/{investmentportfolioanalysisId}/Retrieve:
    get:
      tags:
      - CR - ManagedInvestmentPortfolioAnalysis
      summary: ReCR Retrieve details about an investment portfolio analysis
      description: ReCR Retrieve details about an investment portfolio analysis
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/InvestmentPortfolioAnalysisID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManagedInvestmentPortfolioAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InvestmentPortfolioAnalysis/{investmentportfolioanalysisId}/PerformanceAnalysis/{performanceanalysisId}/Execute:
    put:
      tags:
      - BQ - PerformanceAnalysis
      summary: ExBQ Execute an automated task for a specific type of analysis
      description: ExBQ Execute an automated task for a specific type of analysis
      operationId: ExecutePerformanceAnalysis
      parameters:
      - $ref: '#/components/parameters/InvestmentPortfolioAnalysisID'
      - $ref: '#/components/parameters/PerformanceAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/PerformanceAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerformanceAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InvestmentPortfolioAnalysis/{investmentportfolioanalysisId}/PerformanceAnalysis/{performanceanalysisId}/Request:
    put:
      tags:
      - BQ - PerformanceAnalysis
      summary: RqBQ Request manual intervention for a specific type of analysis
      description: RqBQ Request manual intervention for a specific type of analysis
      operationId: RequestPerformanceAnalysis
      parameters:
      - $ref: '#/components/parameters/InvestmentPortfolioAnalysisID'
      - $ref: '#/components/parameters/PerformanceAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/PerformanceAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerformanceAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InvestmentPortfolioAnalysis/{investmentportfolioanalysisId}/PerformanceAnalysis/{performanceanalysisId}/Retrieve:
    get:
      tags:
      - BQ - PerformanceAnalysis
      summary: ReBQ Retrieve details about a specific type of investment portfolio analysis
      description: ReBQ Retrieve details about a specific type of investment portfolio analysis
      operationId: RetrievePerformanceAnalysis
      parameters:
      - $ref: '#/components/parameters/InvestmentPortfolioAnalysisID'
      - $ref: '#/components/parameters/PerformanceAnalysisID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManagedInvestmentPortfolioAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ManagedInvestmentPortfolioAnalysis:
      type: object
      properties:
        ProductInstanceReference:
          type: object
        CustomerReference:
          type: object
        EmployeeOrBusinessUnitReference:
          type: object
        InvestmentPortfolioInstanceReference:
          type: object
        InvestmentPortfolioAnalysisSchedule:
          type: string
        InvestmentAccountArrangementInstanceReference:
          type: object
        InvestmentPortfolioAnalysisReport:
          type: string
        InvestmentPortfolioAnalysisType:
          type: string
        InvestmentPortfolioAnalysisResult:
          type: string
        InvestmentPortfolioAnalysisReportingDate:
          type: string
        DocumentDirectoryEntryInstanceReference:
          type: object
    PerformanceAnalysis:
      type: object
      properties:
        InvestmentPortfolioPerformanceAnalysisType:
          type: string
        InvestmentPortfolioPerformanceAnalysisTask:
          type: string
        InvestmentPerformanceRequestSpecification:
          type: string
        InvestmentPerformanceModelReference:
          type: object
        InvestmentPerformanceProductandServiceActivityReport:
          type: string
        InvestmentPerformanceFinancialMarketResearchReport:
          type: string
        InvestmentPerformanceWorkProducts:
          type: string
        InvestmentPerformanceRequestResult:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    InvestmentPortfolioAnalysisID:
      name: investmentportfolioanalysisId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    PerformanceAnalysisID:
      name: performanceanalysisId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    ManagedInvestmentPortfolioAnalysis:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ManagedInvestmentPortfolioAnalysis'
    PerformanceAnalysis:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PerformanceAnalysis'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
