openapi: 3.0.1
info:
  title: Lead and Opportunity Management
  description: This service domain captures, classifies and track sales lead/opportunities with established clients for additional products or services. It handles the processing of the opportunity through to the point of formal offer processing.
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/LeadandOpportunityManagement/10.0.0
paths:
  /LeadandOpportunityManagement/Initiate:
    post:
      tags:
      - CR - LeadandOpportunityProcedure
      summary: InCR Initiate lead/opportunity procedure (capture the lead details)
      description: InCR Initiate lead/opportunity procedure (capture the lead details)
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/LeadandOpportunityProcedure'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeadandOpportunityProcedure'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /LeadandOpportunityManagement/{leadandopportunitymanagementId}/Update:
    put:
      tags:
      - CR - LeadandOpportunityProcedure
      summary: UpCR Update details about a lead/opportunity
      description: UpCR Update details about a lead/opportunity
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/LeadandOpportunityManagementID'
      requestBody:
        $ref: '#/components/requestBodies/LeadandOpportunityProcedure'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeadandOpportunityProcedure'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /LeadandOpportunityManagement/{leadandopportunitymanagementId}/Retrieve:
    get:
      tags:
      - CR - LeadandOpportunityProcedure
      summary: ReCR Retrieve details about a lead/opportunity
      description: ReCR Retrieve details about a lead/opportunity
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/LeadandOpportunityManagementID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeadandOpportunityProcedure'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /LeadandOpportunityManagement/{leadandopportunitymanagementId}/Development/Initiate:
    post:
      tags:
      - BQ - Development
      summary: InBQ Initiate, assign development of a lead/opportunity
      description: InBQ Initiate, assign development of a lead/opportunity
      operationId: InitiateDevelopment
      parameters:
      - $ref: '#/components/parameters/LeadandOpportunityManagementID'
      requestBody:
        $ref: '#/components/requestBodies/InitiateDevelopmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Development'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /LeadandOpportunityManagement/{leadandopportunitymanagementId}/Development/{developmentId}/Update:
    put:
      tags:
      - BQ - Development
      summary: UpBQ Update details about lean/opportunity development task
      description: UpBQ Update details about lean/opportunity development task
      operationId: UpdateDevelopment
      parameters:
      - $ref: '#/components/parameters/LeadandOpportunityManagementID'
      - $ref: '#/components/parameters/DevelopmentID'
      requestBody:
        $ref: '#/components/requestBodies/Development'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Development'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /LeadandOpportunityManagement/{leadandopportunitymanagementId}/Development/{developmentId}/Execute:
    put:
      tags:
      - BQ - Development
      summary: ExBQ Execute automated action against a lead opportunity development task (e.g. generate message)
      description: ExBQ Execute automated action against a lead opportunity development task (e.g. generate message)
      operationId: ExecuteDevelopment
      parameters:
      - $ref: '#/components/parameters/LeadandOpportunityManagementID'
      - $ref: '#/components/parameters/DevelopmentID'
      requestBody:
        $ref: '#/components/requestBodies/Development'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Development'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /LeadandOpportunityManagement/{leadandopportunitymanagementId}/Development/{developmentId}/Request:
    put:
      tags:
      - BQ - Development
      summary: RqBQ Request manual intervention in development (e.g. prospect contact)
      description: RqBQ Request manual intervention in development (e.g. prospect contact)
      operationId: RequestDevelopment
      parameters:
      - $ref: '#/components/parameters/LeadandOpportunityManagementID'
      - $ref: '#/components/parameters/DevelopmentID'
      requestBody:
        $ref: '#/components/requestBodies/Development'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Development'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /LeadandOpportunityManagement/{leadandopportunitymanagementId}/Development/{developmentId}/Retrieve:
    get:
      tags:
      - BQ - Development
      summary: ReBQ Retrieve details about lead/opportunity development
      description: ReBQ Retrieve details about lead/opportunity development
      operationId: RetrieveDevelopment
      parameters:
      - $ref: '#/components/parameters/LeadandOpportunityManagementID'
      - $ref: '#/components/parameters/DevelopmentID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveDevelopmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    LeadandOpportunityProcedure:
      type: object
      properties:
        CustomerReference:
          type: object
        CustomerCampaignReference:
          type: object
        CustomerCampaignType:
          type: string
        CustomerCampaignVersionNumber:
          type: string
        ProductandServiceType:
          type: string
        ProductInstanceReference:
          type: object
        EmployeeOrBusinessUnitReference:
          type: object
        LeadandOpportunityDescription:
          type: string
        DateOrTimeOrLocation:
          type: string
    Development:
      type: object
      properties:
        Employee/BusinessUnitReference:
          type: object
        CustomerContactRecordReference:
          type: object
        CorrespondenceInstanceReference:
          type: object
        CorrespondenceContent:
          type: string
        DocumentDirectoryEntryInstanceReference:
          type: object
        DocumentContent:
          type: string
        LeadDevelopmentWorkProducts:
          type: string
        LeadDevelopmentTaskResult:
          type: string
        Date/Time/Location:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    InitiateDevelopmentRequest:
      type: object
      properties:
        LeadandOpportunityProcedure:
          type: object
          properties:
            CustomerReference:
              type: object
            CustomerCampaignReference:
              type: object
            CustomerCampaignType:
              type: string
            CustomerCampaignVersionNumber:
              type: string
            ProductandServiceType:
              type: string
            ProductInstanceReference:
              type: object
            EmployeeOrBusinessUnitReference:
              type: object
            LeadandOpportunityDescription:
              type: string
            DateOrTimeOrLocation:
              type: string
        Development:
          type: object
          properties:
            DocumentDirectoryEntryInstanceReference:
              type: object
    RetrieveDevelopmentResponse:
      type: object
      properties:
        LeadandOpportunityProcedure:
          type: object
          properties:
            CustomerReference:
              type: object
            CustomerCampaignReference:
              type: object
            CustomerCampaignType:
              type: string
            CustomerCampaignVersionNumber:
              type: string
            ProductandServiceType:
              type: string
            ProductInstanceReference:
              type: object
            EmployeeOrBusinessUnitReference:
              type: object
            LeadandOpportunityDescription:
              type: string
            DateOrTimeOrLocation:
              type: string
        Development:
          type: object
          properties:
            CustomerContactRecordReference:
              type: object
            CorrespondenceInstanceReference:
              type: object
            CorrespondenceContent:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            DocumentContent:
              type: string
            LeadDevelopmentWorkProducts:
              type: string
            LeadDevelopmentTaskResult:
              type: string
  parameters:
    LeadandOpportunityManagementID:
      name: leadandopportunitymanagementId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    DevelopmentID:
      name: developmentId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    LeadandOpportunityProcedure:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LeadandOpportunityProcedure'
    InitiateDevelopmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateDevelopmentRequest'
    Development:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Development'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
