openapi: 3.0.1
info:
  title: Position Management
  description: The Service Domain tracks the bank's consolidated financial positions for major customers and complex market conditions
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/PositionManagement/10.0.0
paths:
  /PositionManagement/Initiate:
    post:
      tags:
      - CR - FinancialPositionState
      summary: InCR Initialize a monitored financial position
      description: InCR Initialize a monitored financial position
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/FinancialPositionState'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialPositionState'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PositionManagement/{positionmanagementId}/Update:
    put:
      tags:
      - CR - FinancialPositionState
      summary: UpCR Update the settings and notification arrangements for a position
      description: UpCR Update the settings and notification arrangements for a position
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/PositionManagementID'
      requestBody:
        $ref: '#/components/requestBodies/FinancialPositionState'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialPositionState'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PositionManagement/{positionmanagementId}/Request:
    put:
      tags:
      - CR - FinancialPositionState
      summary: ReCR Get details and the current value of a monitored position
      description: ReCR Get details and the current value of a monitored position
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/PositionManagementID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinancialPositionState'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PositionManagement/{positionmanagementId}/TrialTransaction/Initiate:
    post:
      tags:
      - BQ - TrialTransaction
      summary: InBQ Initiate the evaluation impact of a trial transaction
      description: InBQ Initiate the evaluation impact of a trial transaction
      operationId: InitiateTrialTransaction
      parameters:
      - $ref: '#/components/parameters/PositionManagementID'
      requestBody:
        $ref: '#/components/requestBodies/TrialTransaction'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrialTransaction'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PositionManagement/{positionmanagementId}/TrialTransaction/{trialtransactionId}/Update:
    put:
      tags:
      - BQ - TrialTransaction
      summary: UpBQ Update details of a trial transaction
      description: UpBQ Update details of a trial transaction
      operationId: UpdateTrialTransaction
      parameters:
      - $ref: '#/components/parameters/PositionManagementID'
      - $ref: '#/components/parameters/TrialTransactionID'
      requestBody:
        $ref: '#/components/requestBodies/TrialTransaction'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrialTransaction'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PositionManagement/{positionmanagementId}/TrialTransaction/{trialtransactionId}/Retrieve:
    get:
      tags:
      - BQ - TrialTransaction
      summary: ReBQ Retrieve details about a trial transaction and its position impact
      description: ReBQ Retrieve details about a trial transaction and its position impact
      operationId: RetrieveTrialTransaction
      parameters:
      - $ref: '#/components/parameters/PositionManagementID'
      - $ref: '#/components/parameters/TrialTransactionID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrialTransaction'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PositionManagement/{positionmanagementId}/TransactionApplication/Initiate:
    post:
      tags:
      - BQ - TransactionApplication
      summary: InBQ Initiate the registering of a transaction against the position
      description: InBQ Initiate the registering of a transaction against the position
      operationId: InitiateTransactionApplication
      parameters:
      - $ref: '#/components/parameters/PositionManagementID'
      requestBody:
        $ref: '#/components/requestBodies/TransactionApplication'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionApplication'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PositionManagement/{positionmanagementId}/TransactionApplication/{transactionapplicationId}/Update:
    put:
      tags:
      - BQ - TransactionApplication
      summary: UpBQ Update details of a registered transaction
      description: UpBQ Update details of a registered transaction
      operationId: UpdateTransactionApplication
      parameters:
      - $ref: '#/components/parameters/PositionManagementID'
      - $ref: '#/components/parameters/TransactionApplicationID'
      requestBody:
        $ref: '#/components/requestBodies/TransactionApplication'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionApplication'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PositionManagement/{positionmanagementId}/TransactionApplication/{transactionapplicationId}/Retrieve:
    get:
      tags:
      - BQ - TransactionApplication
      summary: ReBQ Retrieve details about a registered transaction and its position impact
      description: ReBQ Retrieve details about a registered transaction and its position impact
      operationId: RetrieveTransactionApplication
      parameters:
      - $ref: '#/components/parameters/PositionManagementID'
      - $ref: '#/components/parameters/TransactionApplicationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionApplication'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    FinancialPositionState:
      type: object
      properties:
        PositionType:
          type: string
        PositionCustomerReference:
          type: object
        PositionSector:
          type: string
        PositionProductType:
          type: string
        PositionDefinition:
          type: string
        PositionThresholdsOrLimits:
          type: string
        PositionValue:
          type: string
        PositionNotificationArrangementReference:
          type: object
        PositionNotificationArrangementRecord:
          type: string
        PositionNotificationBusinessUnitReference:
          type: object
        PositionNotificationDetails:
          type: string
        PositionNotificationRecord:
          type: string
    TransactionApplication:
      type: object
      properties:
        TransactionReference:
          type: object
        TransactionType:
          type: string
        TransactionRecord:
          type: string
        TransactionAmount:
          type: number
        TransactionDate:
          type: string
        TransactionBookingEntity:
          type: string
        TransactionPositionImpactAssessment:
          type: string
    TrialTransaction:
      type: object
      properties:
        TrialTransactionReference:
          type: object
        TrialTransactionType:
          type: string
        TrialTransactionRecord:
          type: string
        TrialTransactionAmount:
          type: number
        TrialTransactionDate:
          type: string
        TrialTransactionBookingEntity:
          type: string
        TrailTransactionPositionImpactAssessment:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    PositionManagementID:
      name: positionmanagementId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    TransactionApplicationID:
      name: transactionapplicationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    TrialTransactionID:
      name: trialtransactionId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    FinancialPositionState:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FinancialPositionState'
    TrialTransaction:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TrialTransaction'
    TransactionApplication:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TransactionApplication'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
