openapi: 3.0.1
info:
  title: Production Release
  description: Maintain and apply production release tests for new and updated systems
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/ProductionRelease/10.0.0
paths:
  /ProductionRelease/Evaluate:
    post:
      tags:
      - CR - ProductionSystemAssessment
      summary: EvCR Evaluate various risk exposures for a production release
      description: EvCR Evaluate various risk exposures for a production release
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/ProductionSystemAssessment'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionSystemAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProductionRelease/{productionreleaseId}/Update:
    put:
      tags:
      - CR - ProductionSystemAssessment
      summary: UpCR Update aspects of an active production release evaluation
      description: UpCR Update aspects of an active production release evaluation
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/ProductionReleaseID'
      requestBody:
        $ref: '#/components/requestBodies/ProductionSystemAssessment'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionSystemAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProductionRelease/{productionreleaseId}/Request:
    put:
      tags:
      - CR - ProductionSystemAssessment
      summary: RqCR Request manual intervention in an evaluation
      description: RqCR Request manual intervention in an evaluation
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/ProductionReleaseID'
      requestBody:
        $ref: '#/components/requestBodies/ProductionSystemAssessment'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionSystemAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProductionRelease/{productionreleaseId}/Retrieve:
    get:
      tags:
      - CR - ProductionSystemAssessment
      summary: ReCR Retrieve details about a production release evaluation
      description: ReCR Retrieve details about a production release evaluation
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/ProductionReleaseID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionSystemAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProductionRelease/{productionreleaseId}/FunctionalRisk/{functionalriskId}/Retrieve:
    get:
      tags:
      - BQ - FunctionalRisk
      summary: ReBQ Retrieve details about a functional risk assessment
      description: ReBQ Retrieve details about a functional risk assessment
      operationId: RetrieveFunctionalRisk
      parameters:
      - $ref: '#/components/parameters/ProductionReleaseID'
      - $ref: '#/components/parameters/FunctionalRiskID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveFunctionalRiskResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProductionRelease/{productionreleaseId}/ProductionRisk/{productionriskId}/Retrieve:
    get:
      tags:
      - BQ - ProductionRisk
      summary: ReBQ Retrieve details about a production risk assessment
      description: ReBQ Retrieve details about a production risk assessment
      operationId: RetrieveProductionRisk
      parameters:
      - $ref: '#/components/parameters/ProductionReleaseID'
      - $ref: '#/components/parameters/ProductionRiskID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveProductionRiskResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProductionRelease/{productionreleaseId}/BusinessRisk/{businessriskId}/Retrieve:
    get:
      tags:
      - BQ - BusinessRisk
      summary: ReBQ Retrieve details about a business risk assessment
      description: ReBQ Retrieve details about a business risk assessment
      operationId: RetrieveBusinessRisk
      parameters:
      - $ref: '#/components/parameters/ProductionReleaseID'
      - $ref: '#/components/parameters/BusinessRiskID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveBusinessRiskResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProductionRelease/{productionreleaseId}/OperationalRisk/{operationalriskId}/Retrieve:
    get:
      tags:
      - BQ - OperationalRisk
      summary: ReBQ Retrieve details about a operational risk assessment
      description: ReBQ Retrieve details about a operational risk assessment
      operationId: RetrieveOperationalRisk
      parameters:
      - $ref: '#/components/parameters/ProductionReleaseID'
      - $ref: '#/components/parameters/OperationalRiskID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveOperationalRiskResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ProductionSystemAssessment:
      type: object
      properties:
        ProductionReleaseName:
          type: string
        EmployeeOrBusinessUnitReference:
          type: object
        ProductionReleaseType:
          type: string
        ProductionReleaseDescription:
          type: string
        ProductionReleaseTestProfile:
          type: string
        ProductionReleaseTestSchedule:
          type: string
        ProductionReleaseConsolidationRecord:
          type: string
        DocumentDirectoryEntryInstanceReference:
          type: object
        DateType:
          type: string
        Date:
          type: string
    ProductionRisk:
      type: object
      properties:
        ProductionRiskSystemTestType:
          type: string
        ProductionRiskSystemTestDescription:
          type: string
        ProductionRiskSystemTestWorkProduct:
          type: string
        ProductionRiskSystemTestResult:
          type: string
    FunctionalRisk:
      type: object
      properties:
        FunctionalRiskSystemTestType:
          type: string
        FunctionalRiskSystemTestDescription:
          type: string
        FunctionalRiskSystemTestWorkProduct:
          type: string
        FunctionalRiskSystemTestResult:
          type: string
    OperationalRisk:
      type: object
      properties:
        OperationalRiskSystemTestType:
          type: string
        OperationalRiskSystemTestDescription:
          type: string
        OperationalRiskSystemTestWorkProduct:
          type: string
        OperationalRiskSystemTestResult:
          type: string
    BusinessRisk:
      type: object
      properties:
        BusinessRiskSystemTestType:
          type: string
        BusinessRiskSystemTestDescription:
          type: string
        BusinessRiskTestWorkProduct:
          type: string
        BusinessRiskTestResult:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    RetrieveFunctionalRiskResponse:
      type: object
      properties:
        ProductionSystemAssessment:
          type: object
          properties:
            ProductionReleaseName:
              type: string
            EmployeeOrBusinessUnitReference:
              type: object
            ProductionReleaseType:
              type: string
            ProductionReleaseDescription:
              type: string
            ProductionReleaseTestProfile:
              type: string
            ProductionReleaseTestSchedule:
              type: string
            ProductionReleaseConsolidationRecord:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            DateType:
              type: string
        FunctionalRisk:
          type: object
          properties:
            FunctionalRiskSystemTestType:
              type: string
            FunctionalRiskSystemTestDescription:
              type: string
            FunctionalRiskSystemTestWorkProduct:
              type: string
            FunctionalRiskSystemTestResult:
              type: string
    RetrieveProductionRiskResponse:
      type: object
      properties:
        ProductionSystemAssessment:
          type: object
          properties:
            ProductionReleaseName:
              type: string
            EmployeeOrBusinessUnitReference:
              type: object
            ProductionReleaseType:
              type: string
            ProductionReleaseDescription:
              type: string
            ProductionReleaseTestProfile:
              type: string
            ProductionReleaseTestSchedule:
              type: string
            ProductionReleaseConsolidationRecord:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            DateType:
              type: string
        ProductionRisk:
          type: object
          properties:
            ProductionRiskSystemTestType:
              type: string
            ProductionRiskSystemTestDescription:
              type: string
            ProductionRiskSystemTestWorkProduct:
              type: string
            ProductionRiskSystemTestResult:
              type: string
    RetrieveBusinessRiskResponse:
      type: object
      properties:
        ProductionSystemAssessment:
          type: object
          properties:
            ProductionReleaseName:
              type: string
            EmployeeOrBusinessUnitReference:
              type: object
            ProductionReleaseType:
              type: string
            ProductionReleaseDescription:
              type: string
            ProductionReleaseTestProfile:
              type: string
            ProductionReleaseTestSchedule:
              type: string
            ProductionReleaseConsolidationRecord:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            DateType:
              type: string
        BusinessRisk:
          type: object
          properties:
            BusinessRiskSystemTestType:
              type: string
            BusinessRiskSystemTestDescription:
              type: string
            BusinessRiskTestWorkProduct:
              type: string
            BusinessRiskTestResult:
              type: string
    RetrieveOperationalRiskResponse:
      type: object
      properties:
        ProductionSystemAssessment:
          type: object
          properties:
            ProductionReleaseName:
              type: string
            EmployeeOrBusinessUnitReference:
              type: object
            ProductionReleaseType:
              type: string
            ProductionReleaseDescription:
              type: string
            ProductionReleaseTestProfile:
              type: string
            ProductionReleaseTestSchedule:
              type: string
            ProductionReleaseConsolidationRecord:
              type: string
            DocumentDirectoryEntryInstanceReference:
              type: object
            DateType:
              type: string
        OperationalRisk:
          type: object
          properties:
            OperationalRiskSystemTestType:
              type: string
            OperationalRiskSystemTestDescription:
              type: string
            OperationalRiskSystemTestWorkProduct:
              type: string
            OperationalRiskSystemTestResult:
              type: string
  parameters:
    ProductionReleaseID:
      name: productionreleaseId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ProductionRiskID:
      name: productionriskId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    FunctionalRiskID:
      name: functionalriskId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    OperationalRiskID:
      name: operationalriskId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    BusinessRiskID:
      name: businessriskId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    ProductionSystemAssessment:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductionSystemAssessment'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
