openapi: 3.0.1
info:
  title: Prospect Campaign Design
  description: Design and refine prospect campaign specifications based on their impact
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/ProspectCampaignDesign/10.0.0
paths:
  /ProspectCampaignDesign/Create:
    post:
      tags:
      - CR - ProspectCampaignSpecification
      summary: CrCR Create or register an imported prospect campaign design
      description: CrCR Create or register an imported prospect campaign design
      operationId: Create
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/ProspectCampaignSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProspectCampaignSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProspectCampaignDesign/{prospectcampaigndesignId}/Update:
    put:
      tags:
      - CR - ProspectCampaignSpecification
      summary: UpCr Update details of a prospect campaign specification or usage record
      description: UpCr Update details of a prospect campaign specification or usage record
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/ProspectCampaignDesignID'
      requestBody:
        $ref: '#/components/requestBodies/ProspectCampaignSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProspectCampaignSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProspectCampaignDesign/{prospectcampaigndesignId}/Capture:
    put:
      tags:
      - CR - ProspectCampaignSpecification
      summary: CaCR Capture impact feedback against a prospect campaign specification
      description: CaCR Capture impact feedback against a prospect campaign specification
      operationId: Capture
      parameters:
      - $ref: '#/components/parameters/ProspectCampaignDesignID'
      requestBody:
        $ref: '#/components/requestBodies/ProspectCampaignSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProspectCampaignSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProspectCampaignDesign/{prospectcampaigndesignId}/Execute:
    put:
      tags:
      - CR - ProspectCampaignSpecification
      summary: ExCR Execute an automated action for a prospect campaign specification
      description: ExCR Execute an automated action for a prospect campaign specification
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/ProspectCampaignDesignID'
      requestBody:
        $ref: '#/components/requestBodies/ProspectCampaignSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProspectCampaignSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProspectCampaignDesign/{prospectcampaigndesignId}/Request:
    put:
      tags:
      - CR - ProspectCampaignSpecification
      summary: RqCR Request manual intervention with a prospect campaign specification
      description: RqCR Request manual intervention with a prospect campaign specification
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/ProspectCampaignDesignID'
      requestBody:
        $ref: '#/components/requestBodies/ProspectCampaignSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProspectCampaignSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ProspectCampaignDesign/{prospectcampaigndesignId}/Retrieve:
    get:
      tags:
      - CR - ProspectCampaignSpecification
      summary: ReCR Retrieve details about a prospect campaign specification
      description: ReCR Retrieve details about a prospect campaign specification
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/ProspectCampaignDesignID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProspectCampaignSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ProspectCampaignSpecification:
      type: object
      properties:
        ProspectCampaignType:
          type: string
        ProspectCampaignDescription:
          type: string
        ProspectCampaignMetrics:
          type: string
        ProspectCampaignMetricDefinition:
          type: string
        ProspectCampaignMetricGoal:
          type: string
        ProspectCampaignSpecification:
          type: string
        ProspectCampaignProductandServiceUsage:
          type: string
        ProspectCampaignProductandServiceType:
          type: string
        ProductandServiceCampaignEngagementDescription:
          type: string
        ProductandServiceCampaignTransferPricingArrangement:
          type: string
        ProspectCampaignExecutionGuidelines:
          type: string
        ProspectCampaignEligibility:
          type: string
        ProspectCampaignQualifications:
          type: string
        ProspectCampaignInteractionGuide:
          type: string
        ProspectCampaignConsumables:
          type: string
        ProspectCampaignConsumableType:
          type: string
        ProspectCampaignConsumableDescription:
          type: string
        ProspectCampaignPerformanceRecord:
          type: string
        ProspectCampaignProcedureInstanceReference:
          type: object
        EmployeeOrBusinessUnitReference:
          type: object
        ProspectCampaignProcedureSet-up:
          type: string
        ProspectCampaignProcedureVersionNumber:
          type: string
        ProspectCampaignProcedureResult:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    ProspectCampaignDesignID:
      name: prospectcampaigndesignId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    ProspectCampaignSpecification:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProspectCampaignSpecification'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
