openapi: 3.0.1
info:
  title: Public Reference Data Management
  description: Provide structured access to standard 'global' reference data and definitions associated with market activity such as currency, country and segment identifiers.
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/PublicReferenceDataManagement/10.0.0
paths:
  /PublicReferenceDataManagement/{publicreferencedatamanagementId}/Capture:
    put:
      tags:
      - CR - GlobalStandardSpecification
      summary: CaCR Capture Global Standard Specification activity or event related information
      description: CaCR Capture Global Standard Specification activity or event related information
      operationId: Capture
      parameters:
      - $ref: '#/components/parameters/PublicReferenceDataManagementID'
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalStandardSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PublicReferenceDataManagement/{publicreferencedatamanagementId}/Control:
    put:
      tags:
      - CR - GlobalStandardSpecification
      summary: CoCR Control the processing of Global Standard Specification
      description: CoCR Control the processing of Global Standard Specification
      operationId: Control
      parameters:
      - $ref: '#/components/parameters/PublicReferenceDataManagementID'
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalStandardSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PublicReferenceDataManagement/{publicreferencedatamanagementId}/Exchange:
    put:
      tags:
      - CR - GlobalStandardSpecification
      summary: EcCR Accept, verify, etc. aspects of Global Standard Specification processing
      description: EcCR Accept, verify, etc. aspects of Global Standard Specification processing
      operationId: Exchange
      parameters:
      - $ref: '#/components/parameters/PublicReferenceDataManagementID'
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalStandardSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PublicReferenceDataManagement/Initiate:
    post:
      tags:
      - CR - GlobalStandardSpecification
      summary: InCR Instantiate a new Global Standard Specification
      description: InCR Instantiate a new Global Standard Specification
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalStandardSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PublicReferenceDataManagement/{publicreferencedatamanagementId}/Retrieve:
    get:
      tags:
      - CR - GlobalStandardSpecification
      summary: ReCR Retrieve details about any aspect of Global Standard Specification
      description: ReCR Retrieve details about any aspect of Global Standard Specification
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/PublicReferenceDataManagementID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalStandardSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PublicReferenceDataManagement/{publicreferencedatamanagementId}/Request:
    put:
      tags:
      - CR - GlobalStandardSpecification
      summary: RqCR Request manual intervention or a decision with respect to Global Standard Specification
      description: RqCR Request manual intervention or a decision with respect to Global Standard Specification
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/PublicReferenceDataManagementID'
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalStandardSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PublicReferenceDataManagement/{publicreferencedatamanagementId}/Update:
    put:
      tags:
      - CR - GlobalStandardSpecification
      summary: UpCR Update details relating to Global Standard Specification
      description: UpCR Update details relating to Global Standard Specification
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/PublicReferenceDataManagementID'
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalStandardSpecification'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PublicReferenceDataManagement/{publicreferencedatamanagementId}/GlobalReferenceData/Initiate:
    post:
      tags:
      - BQ - GlobalReferenceData
      summary: InBQ Instantiate a new Global Reference Data
      description: InBQ Instantiate a new Global Reference Data
      operationId: InitiateGlobalReferenceData
      parameters:
      - $ref: '#/components/parameters/PublicReferenceDataManagementID'
      requestBody:
        $ref: '#/components/requestBodies/GlobalReferenceData'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalReferenceData'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /PublicReferenceDataManagement/{publicreferencedatamanagementId}/GlobalReferenceData/{globalreferencedataId}/Retrieve:
    get:
      tags:
      - BQ - GlobalReferenceData
      summary: ReBQ Retrieve details about any aspect of Global Reference Data
      description: ReBQ Retrieve details about any aspect of Global Reference Data
      operationId: RetrieveGlobalReferenceData
      parameters:
      - $ref: '#/components/parameters/PublicReferenceDataManagementID'
      - $ref: '#/components/parameters/GlobalReferenceDataID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlobalReferenceData'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    GlobalStandardSpecification:
      type: object
      properties:
        GlobalStandardSpecificationParameterType:
          type: string
        GlobalStandardSpecificationSelectedOption:
          type: string
        GlobalStandardSpecificationDescription:
          type: string
        GlobalStandardSpecificationVersion:
          type: string
        GlobalStandardSpecificationStatus:
          type: string
        GlobalStandardSpecificationUsageLog:
          type: string
        GlobalStandardSpecificationFeedback:
          type: string
        GlobalStandardSpecificationServiceProviderReference:
          type: object
    GlobalReferenceData:
      type: object
      properties:
        GlobalReferenceDataPreconditions:
          type: object
        GlobalReferenceDataSpecificationSchedule:
          type: object
        GlobalReferenceDataVersionNumber:
          type: object
        ExternalReferenceData:
          type: object
        ExternalReferenceDataServiceType:
          type: string
        ExternalReferenceDataServiceDescription:
          type: object
        ExternalReferenceDataServiceInputsandOuputs:
          type: object
        ExternalReferenceDataServiceWorkProduct:
          type: object
        ExternalReferenceDataServiceName:
          type: object
    PublicReferenceDataManagementOutcome:
      type: object
      properties:
        PublicReferenceDataManagementTask:
          type: object
        PublicReferenceDataManagementDesign:
          type: object
        PublicReferenceDataManagementWorkProduct:
          type: object
        PublicReferenceDataManagementImpactAnalysis:
          type: object
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
  parameters:
    PublicReferenceDataManagementID:
      name: publicreferencedatamanagementId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    GlobalReferenceDataID:
      name: globalreferencedataId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    PublicReferenceDataManagementOutcomeID:
      name: publicreferencedatamanagementoutcomeId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    GlobalStandardSpecification:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GlobalStandardSpecification'
    GlobalReferenceData:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GlobalReferenceData'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
