openapi: 3.0.1
info:
  title: Servicing Activity Analysis
  description: This service domain analyzes servicing activity to support continual service improvement
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/ServicingActivityAnalysis/10.0.0
paths:
  /ServicingActivityAnalysis/Initiate:
    post:
      tags:
      - CR - ServicingRootCauseAnalysis
      summary: EvCR Initialize servicing root cause analysis
      description: EvCR Initialize servicing root cause analysis
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/ServicingRootCauseAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicingRootCauseAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingActivityAnalysis/{servicingactivityanalysisId}/Update:
    put:
      tags:
      - CR - ServicingRootCauseAnalysis
      summary: UpCR Update aspects of servicing root cause analysis
      description: UpCR Update aspects of servicing root cause analysis
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/ServicingActivityAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/ServicingRootCauseAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicingRootCauseAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingActivityAnalysis/{servicingactivityanalysisId}/Execute:
    put:
      tags:
      - CR - ServicingRootCauseAnalysis
      summary: ExCR Execute an automated aspect of root cause analysis
      description: ExCR Execute an automated aspect of root cause analysis
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/ServicingActivityAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/ServicingRootCauseAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicingRootCauseAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingActivityAnalysis/{servicingactivityanalysisId}/Request:
    put:
      tags:
      - CR - ServicingRootCauseAnalysis
      summary: RqCR Request manual intervention in servicing root cause analysis
      description: RqCR Request manual intervention in servicing root cause analysis
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/ServicingActivityAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/ServicingRootCauseAnalysis'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicingRootCauseAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingActivityAnalysis/{servicingactivityanalysisId}/Retrieve:
    get:
      tags:
      - CR - ServicingRootCauseAnalysis
      summary: ReCR Retrieve details about servicing root cause analysis
      description: ReCR Retrieve details about servicing root cause analysis
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/ServicingActivityAnalysisID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicingRootCauseAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingActivityAnalysis/{servicingactivityanalysisId}/RootCauseAlgorithm/Initiate:
    post:
      tags:
      - BQ - RootCauseAlgorithm
      summary: EvBQ Initialize application of a specific algorithm for root cause analysis
      description: EvBQ Initialize application of a specific algorithm for root cause analysis
      operationId: InitiateRootCauseAlgorithm
      parameters:
      - $ref: '#/components/parameters/ServicingActivityAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/InitiateRootCauseAlgorithmRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateRootCauseAlgorithmResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingActivityAnalysis/{servicingactivityanalysisId}/RootCauseAlgorithm/{rootcausealgorithmId}/Request:
    put:
      tags:
      - BQ - RootCauseAlgorithm
      summary: RqBQ Request manual intervention to the application of a root cause algorithm
      description: RqBQ Request manual intervention to the application of a root cause algorithm
      operationId: RequestRootCauseAlgorithm
      parameters:
      - $ref: '#/components/parameters/ServicingActivityAnalysisID'
      - $ref: '#/components/parameters/RootCauseAlgorithmID'
      requestBody:
        $ref: '#/components/requestBodies/RootCauseAlgorithm'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootCauseAlgorithm'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingActivityAnalysis/{servicingactivityanalysisId}/RootCauseAlgorithm/{rootcausealgorithmId}/Retrieve:
    get:
      tags:
      - BQ - RootCauseAlgorithm
      summary: ReBQ Retrieve details about the application of a specific root cause algorithm analysis
      description: ReBQ Retrieve details about the application of a specific root cause algorithm analysis
      operationId: RetrieveRootCauseAlgorithm
      parameters:
      - $ref: '#/components/parameters/ServicingActivityAnalysisID'
      - $ref: '#/components/parameters/RootCauseAlgorithmID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveRootCauseAlgorithmResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ServicingRootCauseAnalysis:
      type: object
      properties:
        ServicingActivityType:
          type: string
        ServicingActivityAnalysisPeriod:
          type: string
        ServicingActivityAnalysisType:
          type: string
        ServicingActivityAnalysisResult:
          type: string
        ServicingActivityAnalysisDetermination:
          type: string
        ServicingActivityAnalysisRecommendation:
          type: string
        ServicingActivityHistoryReport:
          type: string
    RootCauseAlgorithm:
      type: object
      properties:
        ServicingActivityRootCauseAlgorithmSpecification:
          type: string
        ServicingActivityRootCauseAnalysisWorkTaskType:
          type: string
        ServicingActivityRootCauseAnalysisWorkTask:
          type: string
        ServicingActivityRootCauseAnalysisWorkTaskWorkProducts:
          type: string
        ServicingActivityRootCauseAnalysisWorkTaskResult:
          type: string
        ServicingActivityRootCauseAnalysisWorkTaskDate-Time:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    InitiateRootCauseAlgorithmRequest:
      type: object
      properties:
        ServicingRootCauseAnalysis:
          type: object
          properties:
            ServicingActivityType:
              type: string
            ServicingActivityAnalysisPeriod:
              type: string
            ServicingActivityAnalysisType:
              type: string
            ServicingActivityAnalysisResult:
              type: string
            ServicingActivityHistoryReport:
              type: string
        RootCauseAlgorithm:
          type: object
          properties:
            ServicingActivityRootCauseAlgorithmSpecification:
              type: string
            ServicingActivityRootCauseAnalysisWorkTaskType:
              type: string
            ServicingActivityRootCauseAnalysisWorkTaskDate-Time:
              type: string
    InitiateRootCauseAlgorithmResponse:
      type: object
      properties:
        ServicingRootCauseAnalysis:
          type: object
          properties:
            ServicingActivityType:
              type: string
            ServicingActivityAnalysisPeriod:
              type: string
            ServicingActivityAnalysisType:
              type: string
            ServicingActivityAnalysisResult:
              type: string
            ServicingActivityHistoryReport:
              type: string
        RootCauseAlgorithm:
          type: object
          properties:
            ServicingActivityRootCauseAlgorithmSpecification:
              type: string
            ServicingActivityRootCauseAnalysisWorkTaskType:
              type: string
            ServicingActivityRootCauseAnalysisWorkTaskWorkProducts:
              type: string
            ServicingActivityRootCauseAnalysisWorkTaskResult:
              type: string
            ServicingActivityRootCauseAnalysisWorkTaskDate-Time:
              type: string
    RetrieveRootCauseAlgorithmResponse:
      type: object
      properties:
        ServicingRootCauseAnalysis:
          type: object
          properties:
            ServicingActivityType:
              type: string
            ServicingActivityAnalysisPeriod:
              type: string
            ServicingActivityAnalysisType:
              type: string
            ServicingActivityAnalysisResult:
              type: string
            ServicingActivityHistoryReport:
              type: string
        RootCauseAlgorithm:
          type: object
          properties:
            ServicingActivityRootCauseAlgorithmSpecification:
              type: string
            ServicingActivityRootCauseAnalysisWorkTaskType:
              type: string
            ServicingActivityRootCauseAnalysisWorkTaskWorkProducts:
              type: string
            ServicingActivityRootCauseAnalysisWorkTaskResult:
              type: string
            ServicingActivityRootCauseAnalysisWorkTaskDate-Time:
              type: string
  parameters:
    ServicingActivityAnalysisID:
      name: servicingactivityanalysisId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    RootCauseAlgorithmID:
      name: rootcausealgorithmId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    ServicingRootCauseAnalysis:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServicingRootCauseAnalysis'
    InitiateRootCauseAlgorithmRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateRootCauseAlgorithmRequest'
    RootCauseAlgorithm:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RootCauseAlgorithm'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
