openapi: 3.0.1
info:
  title: Servicing Mandate
  description: This service domain maintains the allowed customer servicing arrangements for a service provider covering general access to the bank's products and services and optionally customer specific arrangements
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/ServicingMandate/10.0.0
paths:
  /ServicingMandate/Evaluate:
    post:
      tags:
      - CR - ServicingMandateAgreement
      summary: EvCR Agree terms for a third party servicing mandate
      description: EvCR Agree terms for a third party servicing mandate
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/ServicingMandateAgreement'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicingMandateAgreement'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingMandate/{servicingmandateId}/Update:
    put:
      tags:
      - CR - ServicingMandateAgreement
      summary: UpCR Update terms for a third part mandate
      description: UpCR Update terms for a third part mandate
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/ServicingMandateID'
      requestBody:
        $ref: '#/components/requestBodies/ServicingMandateAgreement'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicingMandateAgreement'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingMandate/{servicingmandateId}/Retrieve:
    get:
      tags:
      - CR - ServicingMandateAgreement
      summary: ReCR Retrieve details about a third party mandate
      description: ReCR Retrieve details about a third party mandate
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/ServicingMandateID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicingMandateAgreement'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingMandate/{servicingmandateId}/CustomerMandate/Evaluate:
    post:
      tags:
      - BQ - CustomerMandate
      summary: EvBQ Agree terms for a customer mandate under the service mandate
      description: EvBQ Agree terms for a customer mandate under the service mandate
      operationId: EvaluateCustomerMandate
      parameters:
      - $ref: '#/components/parameters/ServicingMandateID'
      requestBody:
        $ref: '#/components/requestBodies/ServicingMandateAgreement'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerMandate'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingMandate/{servicingmandateId}/CustomerMandate/{customermandateId}/Update:
    put:
      tags:
      - BQ - CustomerMandate
      summary: UpBQ Update details of the customer mandate
      description: UpBQ Update details of the customer mandate
      operationId: UpdateCustomerMandate
      parameters:
      - $ref: '#/components/parameters/ServicingMandateID'
      - $ref: '#/components/parameters/CustomerMandateID'
      requestBody:
        $ref: '#/components/requestBodies/CustomerMandate'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerMandate'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingMandate/{servicingmandateId}/CustomerMandate/{customermandateId}/Retrieve:
    get:
      tags:
      - BQ - CustomerMandate
      summary: ReBQ Retrieve details about the customer mandate
      description: ReBQ Retrieve details about the customer mandate
      operationId: RetrieveCustomerMandate
      parameters:
      - $ref: '#/components/parameters/ServicingMandateID'
      - $ref: '#/components/parameters/CustomerMandateID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveCustomerMandateResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ServicingMandateAgreement:
      type: object
      properties:
        CustomerReference:
          type: object
        ServicingMandateAgreementType:
          type: string
        ServicingMandateAgreementJurisdiction:
          type: string
        ServicingMandateAgreementValidFromOrToDate:
          type: string
        ServicingMandateAgreementResponsibleParties:
          type: string
        DocumentDirectoryEntryInstanceReference:
          type: object
        ServicingMandateAgreementProductandServiceProfileReference:
          type: object
        ServicingMandateAgreementProductandServiceProfile:
          type: string
        ProductandServiceType:
          type: string
        ServicingMandateAgreementProductandServiceTypeEligibility:
          type: string
    CustomerMandate:
      type: object
      properties:
        CustomerReference:
          type: object
        ServicingMandateAgreementCustomerProductandServiceProfile:
          type: string
        ProductandServiceType:
          type: string
        ServicingMandateAgreementCustomerProductandServiceTypeAccess:
          type: string
        ServicingMandateAgreementCustomerProductandServiceTypeUsage:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    RetrieveCustomerMandateResponse:
      type: object
      properties:
        ServicingMandateAgreement:
          type: object
          properties:
            CustomerReference:
              type: object
            ServicingMandateAgreementType:
              type: string
            ServicingMandateAgreementJurisdiction:
              type: string
            ServicingMandateAgreementValidFromOrToDate:
              type: string
            ServicingMandateAgreementProductandServiceProfileReference:
              type: object
            ProductandServiceType:
              type: string
            ServicingMandateAgreementProductandServiceTypeEligibility:
              type: string
        CustomerMandate:
          type: object
          properties:
            ServicingMandateAgreementCustomerProductandServiceProfile:
              type: string
            ServicingMandateAgreementCustomerProductandServiceTypeAccess:
              type: string
            ServicingMandateAgreementCustomerProductandServiceTypeUsage:
              type: string
  parameters:
    ServicingMandateID:
      name: servicingmandateId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    CustomerMandateID:
      name: customermandateId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    ServicingMandateAgreement:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServicingMandateAgreement'
    CustomerMandate:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CustomerMandate'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
