openapi: 3.0.1
info:
  title: Underwriting
  description: This service domain manages the underwriting decision process for products as appropriate (including many loan types and some insurance products)
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/Underwriting/10.0.0
paths:
  /Underwriting/Evaluate:
    post:
      tags:
      - CR - UnderwritingAssessment
      summary: EvCR Evaluate an underwriting decision
      description: EvCR Evaluate an underwriting decision
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/EvaluateUnderwritingAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateUnderwritingAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /Underwriting/{underwritingId}/Update:
    put:
      tags:
      - CR - UnderwritingAssessment
      summary: UpCR Update details for an underwriting assessment
      description: UpCR Update details for an underwriting assessment
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/UnderwritingID'
      requestBody:
        $ref: '#/components/requestBodies/UpdateUnderwritingAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUnderwritingAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /Underwriting/{underwritingId}/Retrieve:
    get:
      tags:
      - CR - UnderwritingAssessment
      summary: ReCR Retrieve details about an underwriting assessment
      description: ReCR Retrieve details about an underwriting assessment
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/UnderwritingID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveUnderwritingAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    UnderwritingAssessment:
      type: object
      properties:
        UnderwritingGuidelines:
          type: string
        RequiredCustomerEmploymentHistoryDetails:
          type: string
        RequiredCustomerDebtOrAssetStatement:
          type: string
        RequiredCustomerCreditAssessment:
          type: string
        RequiredCollateralCoverage:
          type: string
        RequiredCustomerProductandServicePaymentHistory:
          type: string
        RequiredCustomerDocuments:
          type: string
        ProposedTransactionDetails:
          type: string
        ProductInstanceReference:
          type: object
        ProposedLoanTerms:
          type: string
        ProposedLoanAmount:
          type: number
        LoanPurpose:
          type: string
        CustomerReference:
          type: object
        CustomerReferenceDetails:
          type: object
        CustomerProductEligibilityTerms:
          type: string
        CustomerEmploymentHistory:
          type: string
        CustomerIncomeStatement:
          type: string
        CustomerDebtStatement:
          type: string
        CustomerAssetStatement:
          type: string
        CustomerCreditAssessment:
          type: string
        CustomerProductandServicePaymentHistory:
          type: string
        CollateralItemReference:
          type: object
        CollateralItemType:
          type: string
        CollateralItemValuation:
          type: string
        DocumentReference:
          type: object
        UnderwritingAssessmentDecision:
          type: string
        UnderwritingAssessmentWorkProduct:
          type: string
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
        status:
          type: string
        message:
          type: string
    EvaluateUnderwritingAssessmentRequest:
      type: object
      properties:
        UnderwritingAssessment:
          type: object
          properties:
            UnderwritingGuidelines:
              type: string
            ProposedTransactionDetails:
              type: string
            ProductInstanceReference:
              type: object
            ProposedLoanTerms:
              type: string
            ProposedLoanAmount:
              type: number
            LoanPurpose:
              type: string
            CustomerReference:
              type: object
            CustomerReferenceDetails:
              type: object
            CustomerProductEligibilityTerms:
              type: string
            CustomerIncomeStatement:
              type: string
            CustomerDebtStatement:
              type: string
            CustomerAssetStatement:
              type: string
            CollateralItemReference:
              type: object
            CollateralItemType:
              type: string
            CollateralItemValuation:
              type: string
            DocumentReference:
              type: object
    EvaluateUnderwritingAssessmentResponse:
      type: object
      properties:
        UnderwritingAssessment:
          type: object
          properties:
            UnderwritingGuidelines:
              type: string
            RequiredCustomerEmploymentHistoryDetails:
              type: string
            RequiredCustomerDebtOrAssetStatement:
              type: string
            RequiredCustomerCreditAssessment:
              type: string
            RequiredCollateralCoverage:
              type: string
            RequiredCustomerProductandServicePaymentHistory:
              type: string
            RequiredCustomerDocuments:
              type: string
            ProposedTransactionDetails:
              type: string
            DocumentReference:
              type: object
            UnderwritingAssessmentDecision:
              type: string
            UnderwritingAssessmentWorkProduct:
              type: string
    UpdateUnderwritingAssessmentRequest:
      type: object
      properties:
        UnderwritingAssessment:
          type: object
          properties:
            ProposedTransactionDetails:
              type: string
            ProductInstanceReference:
              type: object
            ProposedLoanTerms:
              type: string
            ProposedLoanAmount:
              type: number
            LoanPurpose:
              type: string
            CustomerReference:
              type: object
            CustomerReferenceDetails:
              type: object
            CustomerProductEligibilityTerms:
              type: string
            CustomerEmploymentHistory:
              type: string
            CustomerIncomeStatement:
              type: string
            CustomerDebtStatement:
              type: string
            CustomerAssetStatement:
              type: string
            CustomerCreditAssessment:
              type: string
            CustomerProductandServicePaymentHistory:
              type: string
            CollateralItemReference:
              type: object
            CollateralItemType:
              type: string
            CollateralItemValuation:
              type: string
            DocumentReference:
              type: object
    UpdateUnderwritingAssessmentResponse:
      type: object
      properties:
        UnderwritingAssessment:
          type: object
          properties:
            ProposedTransactionDetails:
              type: string
            ProductInstanceReference:
              type: object
            ProposedLoanTerms:
              type: string
            ProposedLoanAmount:
              type: number
            LoanPurpose:
              type: string
            CustomerReference:
              type: object
            CustomerReferenceDetails:
              type: object
            CustomerProductEligibilityTerms:
              type: string
            CustomerEmploymentHistory:
              type: string
            CustomerIncomeStatement:
              type: string
            CustomerDebtStatement:
              type: string
            CustomerAssetStatement:
              type: string
            CustomerCreditAssessment:
              type: string
            CustomerProductandServicePaymentHistory:
              type: string
            CollateralItemReference:
              type: object
            CollateralItemType:
              type: string
            CollateralItemValuation:
              type: string
            DocumentReference:
              type: object
    RetrieveUnderwritingAssessmentResponse:
      type: object
      properties:
        UnderwritingAssessment:
          type: object
          properties:
            UnderwritingGuidelines:
              type: string
            RequiredCustomerEmploymentHistoryDetails:
              type: string
            RequiredCustomerDebtOrAssetStatement:
              type: string
            RequiredCustomerCreditAssessment:
              type: string
            RequiredCollateralCoverage:
              type: string
            RequiredCustomerProductandServicePaymentHistory:
              type: string
            RequiredCustomerDocuments:
              type: string
            ProposedTransactionDetails:
              type: string
            ProductInstanceReference:
              type: object
            ProposedLoanTerms:
              type: string
            ProposedLoanAmount:
              type: number
            LoanPurpose:
              type: string
            CustomerReference:
              type: object
            CustomerReferenceDetails:
              type: object
            CustomerProductEligibilityTerms:
              type: string
            CustomerIncomeStatement:
              type: string
            CustomerDebtStatement:
              type: string
            CustomerAssetStatement:
              type: string
            CollateralItemReference:
              type: object
            CollateralItemType:
              type: string
            CollateralItemValuation:
              type: string
            DocumentReference:
              type: object
            UnderwritingAssessmentDecision:
              type: string
            UnderwritingAssessmentWorkProduct:
              type: string
  parameters:
    UnderwritingID:
      name: underwritingId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    EvaluateUnderwritingAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateUnderwritingAssessmentRequest'
    UpdateUnderwritingAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateUnderwritingAssessmentRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
