openapi: 3.0.1
info:
  title: Fraud Resolution
  description: This service domain sets up and processes a fraud case resulting from fraud behavior that has been detected during production processing
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/FraudResolution/10.0.0
paths:
  /FraudResolution/Initiate:
    post:
      tags:
      - CR - FraudResolutionProcedure
      summary: InCR Initiate a fraud case
      description: InCR Initiate a fraud case
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/FraudResolutionProcedure'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateFraudResolutionProcedureResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudResolution/{fraudresolutionId}/Update:
    put:
      tags:
      - CR - FraudResolutionProcedure
      summary: UpCR Update details of an active fraud case
      description: UpCR Update details of an active fraud case
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/FraudResolutionID'
      requestBody:
        $ref: '#/components/requestBodies/FraudResolutionProcedure'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FraudResolutionProcedure'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudResolution/{fraudresolutionId}/Retrieve:
    get:
      tags:
      - CR - FraudResolutionProcedure
      summary: ReCR Retrieve information about an active fraud case
      description: ReCR Retrieve information about an active fraud case
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/FraudResolutionID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FraudResolutionProcedure'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudResolution/{fraudresolutionId}/CaseAnalysis/{caseanalysisId}/Retrieve:
    get:
      tags:
      - BQ - CaseAnalysis
      summary: ReCR Retrieve information about an active fraud case analysis
      description: ReCR Retrieve information about an active fraud case analysis
      operationId: RetrieveCaseAnalysis
      parameters:
      - $ref: '#/components/parameters/FraudResolutionID'
      - $ref: '#/components/parameters/CaseAnalysisID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FraudResolutionProcedure'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudResolution/{fraudresolutionId}/CaseDetermination/{casedeterminationId}/Retrieve:
    get:
      tags:
      - BQ - CaseDetermination
      summary: ReCR Retrieve information about an active fraud case determination
      description: ReCR Retrieve information about an active fraud case determination
      operationId: RetrieveCaseDetermination
      parameters:
      - $ref: '#/components/parameters/FraudResolutionID'
      - $ref: '#/components/parameters/CaseDeterminationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveCaseDeterminationResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudResolution/{fraudresolutionId}/CaseResolution/{caseresolutionId}/Request:
    put:
      tags:
      - BQ - CaseResolution
      summary: RqBQ Request reworking of resolution to a case
      description: RqBQ Request reworking of resolution to a case
      operationId: RequestCaseResolution
      parameters:
      - $ref: '#/components/parameters/FraudResolutionID'
      - $ref: '#/components/parameters/CaseResolutionID'
      requestBody:
        $ref: '#/components/requestBodies/CaseResolution'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudResolution/{fraudresolutionId}/CaseResolution/{caseresolutionId}/Retrieve:
    get:
      tags:
      - BQ - CaseResolution
      summary: ReCR Retrieve information about an active fraud case resolution
      description: ReCR Retrieve information about an active fraud case resolution
      operationId: RetrieveCaseResolution
      parameters:
      - $ref: '#/components/parameters/FraudResolutionID'
      - $ref: '#/components/parameters/CaseResolutionID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveCaseResolutionResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    FraudResolutionProcedure:
      type: object
      properties:
        FraudCaseType:
          type: string
          description: Type of case (e.g.  disputed charge, merchant fraud, stolen/fake device)
        ProductInstanceReference:
          type: object
          description: Reference to the product/service associated with case
        CustomerReference:
          type: object
          description: Reference to the customer associated with case if applicable
        MerchantReference:
          type: object
          description: Reference to the merchant associated with case if applicable
        InterstedPartyReference:
          type: object
          description: Reference to any other interested parties (such as intermediaries)
        ContactReference:
          type: object
          description: Customer contact reference if the case was raised during a customer contact
        TransactionReference:
          type: object
          description: Reference to one or more product transactions associated with the case
        TransactionRecord:
          type: string
          description: Record contains all details of the transaction (not itemized)
        CaseLocation:
          type: string
          description: Record of a physical address or electronic venue the fraud was detected
        Date:
          type: string
          description: Specific dates and ties of significance to the case
        EmployeeOrBusinessUnitReference:
          type: object
          description: Business unit and or employee reference where the case was raised
        FraudCaseWorkProducts:
          type: string
          description: File of consolidated notes, forms and documents for the case
        FraudCaseResolutionSchedule:
          type: string
          description: Target and actual dates for case processing/resolution
        FraudCaseStatus:
          type: string
          description: The processing status for the case
    CaseAnalysis:
      type: object
      properties:
        FraudCaseRootCause:
          type: string
          description: The result of the case analysis
    CaseDetermination:
      type: object
      properties:
        CustomerAgreementReference:
          type: object
          description: Reference to the involved customer's agreement
        CustomerAgreement:
          type: string
          description: Customer agreement accessed to determine constraints on resolution approach
        MerchantAgreementReference:
          type: object
          description: Reference to the involved merchant's agreement
        MerchantAgreement:
          type: string
          description: Merchant agreement accessed to determine constraints on resolution approach
        InterestedPartyAgreementReference:
          type: object
          description: Reference to the interested party's agreement
        InterestedPartyAgreement:
          type: string
          description: Interested party agreement accessed to determine constraints on resolution approach
        FraudCaseDeterminationRecord:
          type: string
          description: Record of rules and guidelines applied to determine fraud case resolution
    CaseResolution:
      type: object
      properties:
        FraudCaseResolutionRecord:
          type: string
          description: Record sets out, defines and assigns resolution tasks
        Employee/BusinessUnitReference:
          type: object
          description: Employee and or business unit responsible for the resolution
        CorrespondenceReference:
          type: object
          description: Reference to all correspondence (e.g. confirmation messages sent to involved parties, includes internal and external legal/law enforcement authorities)
        Adjustment/ChargebackReference:
          type: object
          description: Reference to any associated adjustment or chargeback transaction initiated by the resolution
        ConsortiaReportingInstanceReference:
          type: object
          description: Reference to the consortia notification transaction for fraud resultion activity
        DocumentDirectoryEntryInstanceReference:
          type: object
          description: The document reference for associated documents
        PaymentOrderReference:
          type: object
          description: Reference to any financial adjustments that are made during the case
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: NA
        status:
          type: string
          description: NA
        message:
          type: string
          description: NA
    InitiateFraudResolutionProcedureResponse:
      type: object
      properties:
        FraudResolutionProcedure:
          type: object
          properties:
            FraudCaseType:
              type: string
              description: NA
            FraudCaseWorkProducts:
              type: string
              description: NA
            FraudCaseResolutionSchedule:
              type: string
              description: NA
            FraudCaseStatus:
              type: string
              description: NA
    RetrieveCaseDeterminationResponse:
      type: object
      properties:
        FraudResolutionProcedure:
          type: object
          properties:
            FraudCaseType:
              type: string
              description: NA
            ProductInstanceReference:
              type: object
              description: NA
            CustomerReference:
              type: object
              description: NA
            MerchantReference:
              type: object
              description: NA
            InterstedPartyReference:
              type: object
              description: NA
            ContactReference:
              type: object
              description: NA
            TransactionReference:
              type: object
              description: NA
            TransactionRecord:
              type: string
              description: NA
            CaseLocation:
              type: string
              description: NA
            Date:
              type: string
              description: NA
            EmployeeOrBusinessUnitReference:
              type: object
              description: NA
            FraudCaseWorkProducts:
              type: string
              description: NA
            FraudCaseResolutionSchedule:
              type: string
              description: NA
            FraudCaseStatus:
              type: string
              description: NA
        CaseAnalysis:
          type: object
          properties:
            FraudCaseRootCause:
              type: string
              description: NA
        CaseDetermination:
          type: object
          properties:
            CustomerAgreementReference:
              type: object
              description: NA
            MerchantAgreementReference:
              type: object
              description: NA
            InterestedPartyAgreementReference:
              type: object
              description: NA
            FraudCaseDeterminationRecord:
              type: string
              description: NA
    RetrieveCaseResolutionResponse:
      type: object
      properties:
        FraudResolutionProcedure:
          type: object
          properties:
            FraudCaseType:
              type: string
              description: NA
            ProductInstanceReference:
              type: object
              description: NA
            CustomerReference:
              type: object
              description: NA
            MerchantReference:
              type: object
              description: NA
            InterstedPartyReference:
              type: object
              description: NA
            ContactReference:
              type: object
              description: NA
            TransactionReference:
              type: object
              description: NA
            TransactionRecord:
              type: string
              description: NA
            CaseLocation:
              type: string
              description: NA
            Date:
              type: string
              description: NA
            EmployeeOrBusinessUnitReference:
              type: object
              description: NA
            FraudCaseWorkProducts:
              type: string
              description: NA
            FraudCaseResolutionSchedule:
              type: string
              description: NA
            FraudCaseStatus:
              type: string
              description: NA
        CaseAnalysis:
          type: object
          properties:
            FraudCaseRootCause:
              type: string
              description: NA
        CaseDetermination:
          type: object
          properties:
            FraudCaseDeterminationRecord:
              type: string
              description: NA
        CaseResolution:
          type: object
          properties:
            FraudCaseResolutionRecord:
              type: string
              description: NA
            CorrespondenceReference:
              type: object
              description: NA
            AdjustmentOrChargebackReference:
              type: object
              description: NA
            ConsortiaReportingInstanceReference:
              type: object
              description: NA
            DocumentDirectoryEntryInstanceReference:
              type: object
              description: NA
            PaymentOrderReference:
              type: object
              description: NA
  parameters:
    FraudResolutionID:
      name: fraudresolutionId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    CaseAnalysisID:
      name: caseanalysisId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    CaseDeterminationID:
      name: casedeterminationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    CaseResolutionID:
      name: caseresolutionId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    FraudResolutionProcedure:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FraudResolutionProcedure'
    CaseResolution:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CaseResolution'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
