openapi: 3.0.1
info:
  title: Servicing Order
  description: This service domain handles the processing of a customer servicing request as a predefined procedure. A range of standard servicing requests can be supported. The process can include a check of permissions when the request is made by a third party/service provider
  version: 10.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/ServicingOrder/10.0.0
paths:
  /ServicingOrder/Initiate:
    post:
      tags:
      - CR - ServicingOrderProcedure
      summary: InCR Initiate a servicing order (within a contact session)
      description: InCR Initiate a servicing order (within a contact session)
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/InitiateServicingOrderProcedureRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateServicingOrderProcedureResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingOrder/{servicingorderId}/Execute:
    put:
      tags:
      - CR - ServicingOrderProcedure
      summary: ExCR Execute an automated task in a servicing order (e.g. upload data)
      description: ExCR Execute an automated task in a servicing order (e.g. upload data)
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/ServicingOrderID'
      requestBody:
        $ref: '#/components/requestBodies/ExecuteServicingOrderProcedureRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteServicingOrderProcedureResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingOrder/{servicingorderId}/Request:
    put:
      tags:
      - CR - ServicingOrderProcedure
      summary: RqCR Request manual intervention in a servicing order (e.g. engage a servicing agent)
      description: RqCR Request manual intervention in a servicing order (e.g. engage a servicing agent)
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/ServicingOrderID'
      requestBody:
        $ref: '#/components/requestBodies/RequestServicingOrderProcedureRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestServicingOrderProcedureResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /ServicingOrder/{servicingorderId}/Retrieve:
    get:
      tags:
      - CR - ServicingOrderProcedure
      summary: ReCR Retrieve details about a servicing order
      description: ReCR Retrieve details about a servicing order
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/ServicingOrderID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveServicingOrderProcedureResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ServicingOrderProcedure:
      type: object
      properties:
        ThirdPartyReference:
          type: object
          description: Reference to a third party service provider that handles some aspect of customer servicing access with the bank
        ThirdPartyServicingMandateReference:
          type: object
          description: Reference to a third party servicing mandate - used when a third party is requesting the service order
        ThirdPartyServicingMandate:
          type: string
          description: The servicing mandate for a third party defines the customers and service access allowed
        CustomerReference:
          type: object
          description: The customer requesting the servicing order directly or the customer that is being serviced indirectly by the third party
        CustomerEligibilityAssessmentInstanceReference:
          type: object
          description: Reference to the customer's active services and products record
        ServicingOrderType:
          type: string
          description: The type of servicing order being processed (e.g. change of address, change of employment…)
        ServicingOrderTaskRecord:
          type: string
          description: The record for the servicing task
        ServicingOrderDescription:
          type: string
          description: Defines the processing tasks and their sequencing followed by the servicing order
        Date:
          type: string
          description: The date and time that the servicing order is processed
        EmployeeOrBusinessUnitReference:
          type: object
          description: Employees involved in the servicing order
        ServicingOrderWorkProduct:
          type: string
          description: Work documentation, forms and schedules produced and referenced during the analysis
        ServicingOrderWorkTaskResult:
          type: string
          description: The outcome of the servicing order
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: NA
        status:
          type: string
          description: NA
        message:
          type: string
          description: NA
    InitiateServicingOrderProcedureRequest:
      type: object
      properties:
        ServicingOrderProcedure:
          type: object
          properties:
            ThirdPartyReference:
              type: object
              description: NA
            ThirdPartyServicingMandateReference:
              type: object
              description: NA
            CustomerReference:
              type: object
              description: NA
            CustomerEligibilityAssessmentInstanceReference:
              type: object
              description: NA
            ServicingOrderType:
              type: string
              description: NA
            ServicingOrderTaskRecord:
              type: string
              description: NA
            EmployeeOrBusinessUnitReference:
              type: object
              description: NA
    InitiateServicingOrderProcedureResponse:
      type: object
      properties:
        ServicingOrderProcedure:
          type: object
          properties:
            ServicingOrderTaskRecord:
              type: string
              description: NA
            ServicingOrderDescription:
              type: string
              description: NA
            ServicingOrderWorkProduct:
              type: string
              description: NA
            ServicingOrderWorkTaskResult:
              type: string
              description: NA
    ExecuteServicingOrderProcedureRequest:
      type: object
      properties:
        ServicingOrderProcedure:
          type: object
          properties:
            ThirdPartyReference:
              type: object
              description: NA
            ThirdPartyServicingMandateReference:
              type: object
              description: NA
            CustomerReference:
              type: object
              description: NA
            CustomerEligibilityAssessmentInstanceReference:
              type: object
              description: NA
            ServicingOrderType:
              type: string
              description: NA
            ServicingOrderTaskRecord:
              type: string
              description: NA
            EmployeeOrBusinessUnitReference:
              type: object
              description: NA
    ExecuteServicingOrderProcedureResponse:
      type: object
      properties:
        ServicingOrderProcedure:
          type: object
          properties:
            ServicingOrderTaskRecord:
              type: string
              description: NA
            ServicingOrderDescription:
              type: string
              description: NA
            ServicingOrderWorkProduct:
              type: string
              description: NA
            ServicingOrderWorkTaskResult:
              type: string
              description: NA
    RequestServicingOrderProcedureRequest:
      type: object
      properties:
        ServicingOrderProcedure:
          type: object
          properties:
            ThirdPartyReference:
              type: object
              description: NA
            ThirdPartyServicingMandateReference:
              type: object
              description: NA
            CustomerReference:
              type: object
              description: NA
            CustomerEligibilityAssessmentInstanceReference:
              type: object
              description: NA
            ServicingOrderType:
              type: string
              description: NA
            ServicingOrderTaskRecord:
              type: string
              description: NA
            EmployeeOrBusinessUnitReference:
              type: object
              description: NA
    RequestServicingOrderProcedureResponse:
      type: object
      properties:
        ServicingOrderProcedure:
          type: object
          properties:
            ServicingOrderTaskRecord:
              type: string
              description: NA
            ServicingOrderDescription:
              type: string
              description: NA
            ServicingOrderWorkProduct:
              type: string
              description: NA
            ServicingOrderWorkTaskResult:
              type: string
              description: NA
    RetrieveServicingOrderProcedureResponse:
      type: object
      properties:
        ServicingOrderProcedure:
          type: object
          properties:
            ThirdPartyReference:
              type: object
              description: NA
            ThirdPartyServicingMandateReference:
              type: object
              description: NA
            CustomerReference:
              type: object
              description: NA
            CustomerEligibilityAssessmentInstanceReference:
              type: object
              description: NA
            ServicingOrderType:
              type: string
              description: NA
            ServicingOrderTaskRecord:
              type: string
              description: NA
            ServicingOrderDescription:
              type: string
              description: NA
            EmployeeOrBusinessUnitReference:
              type: object
              description: NA
            ServicingOrderWorkProduct:
              type: string
              description: NA
            ServicingOrderWorkTaskResult:
              type: string
              description: NA
  parameters:
    ServicingOrderID:
      name: servicingorderId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    InitiateServicingOrderProcedureRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateServicingOrderProcedureRequest'
    ExecuteServicingOrderProcedureRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExecuteServicingOrderProcedureRequest'
    RequestServicingOrderProcedureRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestServicingOrderProcedureRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
