openapi: 3.0.1
info:
  title: Competitor Analysis
  description: Solicit, consolidate and analyze competitor specific public domain data to develop competitor insights and comparisons
  version: 10.1.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/CompetitorAnalysis/10.1.0
paths:
  /CompetitorAnalysis/Evaluate:
    post:
      tags:
      - CR - CompetitorAnalysis
      summary: EvCR Initialize competitor analysis
      description: EvCR Initialize competitor analysis
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/EvaluateCompetitorAnalysisRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateCompetitorAnalysisResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CompetitorAnalysis/{competitoranalysisId}/Execute:
    put:
      tags:
      - CR - CompetitorAnalysis
      summary: ExCR Obtain an automated refresh of maintained competitor analysis
      description: ExCR Obtain an automated refresh of maintained competitor analysis
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/CompetitorAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/ExecuteCompetitorAnalysisRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteCompetitorAnalysisResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CompetitorAnalysis/{competitoranalysisId}/Request:
    put:
      tags:
      - CR - CompetitorAnalysis
      summary: RqCR Request a manual intervention in the development of competitor analysis
      description: RqCR Request a manual intervention in the development of competitor analysis
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/CompetitorAnalysisID'
      requestBody:
        $ref: '#/components/requestBodies/RequestCompetitorAnalysisRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestCompetitorAnalysisResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CompetitorAnalysis/{competitoranalysisId}/Retrieve:
    get:
      tags:
      - CR - CompetitorAnalysis
      summary: ReCR Retrieve details about competitor analysis activity
      description: ReCR Retrieve details about competitor analysis activity
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/CompetitorAnalysisID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveCompetitorAnalysisResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CompetitorAnalysis:
      type: object
      properties:
        CompetitorAnalysisType:
          type: string
          description: The type of research view provided by the research (e.g. pricing comparison)
        CompetitorAnalysisSpecification:
          type: string
          description: The definition of the specific competitor analysis
        CompetitorAnalysisGuidance:
          type: string
          description: Guidance on usage and interpretation of the competitor analysis (e.g. qualifying the accuracy/confidence of any findings)
        CompetitorAnalysisAlgorithmReference:
          type: object
          description: Reference to the algorithm/approach used to generate the analysis
        CompetitorAnalysisRequestRecord:
          type: string
          description: Request record for the competitor analysis
        CompetitorAnalysisRequest:
          type: string
          description: The specific details of the request
        EmployeeOrBusinessUnitReference:
          type: object
          description: The employee/business unit requesting the analysis
        CompetitorAnalysisRequestWorkProducts:
          type: string
          description: Work documentation, forms and schedules produced and referenced during the analysis
        CompetitorAnalysisRequestResult:
          type: string
          description: The output from performing the analysis
        CompetitorAnalysisUsageRecord:
          type: string
          description: Usage record of the competitor analysis maintained/developed by the function
        CompetitorAnalysisUsage:
          type: string
          description: A record of the usage of the analysis
        CompetitorAnalysisImpact:
          type: string
          description: A record of reported impact/accuracy of the competitor analysis
    AnalysisAlgorithm:
      type: object
      properties:
        AnalysisAlgorithmType:
          type: string
          description: Defines the type of algorithm/approach employed (e.g. competitor reviews, public domain research)
        AnalysisAlgorithmSpecification:
          type: string
          description: Description of the specific algorithms used and the approach taken to develop the competitor analysis
        AnalysisAlgorithmReferencedMarketResearchRecord:
          type: object
          description: The externally sourced general market research sources and any internal intelligence used in the competitor analysis
        MarketResearchReportTypeReference:
          type: string
          description: Reference to a specific type of predefined market research report or database
        MarketResearchReportTypeDefinition:
          type: string
          description: Describes the available market research report content (e.g. customer social network usage analysis)
        MarketResearchReportVersion/Period:
          type: string
          description: Defines the version and period covered by the research
        MarketResearchReport:
          type: string
          description: Is the content of the report or database in any suitable form
        AnalysisAlgorithmRequestRecord:
          type: string
          description: Request record for the competitor analysis algorithm/approach execution. Note this is defined in the general competitor analysis request and interpreted internally as the specific approach/algorithm is selected as necessary
        AnalysisAlgorithmRequest:
          type: string
          description: The specific details of the request
        AnalysisAlgorithmWorkProducts:
          type: string
          description: Work documentation, forms and schedules produced and referenced during the analysis
        AnalysisAlgorithmRequestResult:
          type: string
          description: The output from executing the algorithm
        AnalysisAlgorithmUsageRecord:
          type: string
          description: The record of the use of the specific competitor analysis algorithm/approach
        AnalysisAlgorithmUsage:
          type: string
          description: A record of the usage of the algorithm
        AnalysisAlgorithmImpact:
          type: string
          description: A record of reported impact/accuracy of the competitor analysis algorithm/approach
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: NA
        status:
          type: string
          description: NA
        message:
          type: string
          description: NA
    EvaluateCompetitorAnalysisRequest:
      type: object
      properties:
        CompetitorAnalysis:
          type: object
          properties:
            CompetitorAnalysisType:
              type: string
              description: The type of research view provided by the research (e.g. pricing comparison)
            CompetitorAnalysisAlgorithmReference:
              type: object
              description: Reference to the algorithm/approach used to generate the analysis
            CompetitorAnalysisRequestRecord:
              type: string
              description: Request record for the competitor analysis
            EmployeeOrBusinessUnitReference:
              type: object
              description: The employee/business unit requesting the analysis
            CompetitorAnalysisUsageRecord:
              type: string
              description: Usage record of the competitor analysis maintained/developed by the function
            CompetitorAnalysisImpact:
              type: string
              description: A record of reported impact/accuracy of the competitor analysis
    EvaluateCompetitorAnalysisResponse:
      type: object
      properties:
        CompetitorAnalysis:
          type: object
          properties:
            CompetitorAnalysisType:
              type: string
              description: The type of research view provided by the research (e.g. pricing comparison)
            CompetitorAnalysisSpecification:
              type: string
              description: The definition of the specific competitor analysis
            CompetitorAnalysisGuidance:
              type: string
              description: Guidance on usage and interpretation of the competitor analysis (e.g. qualifying the accuracy/confidence of any findings)
            CompetitorAnalysisAlgorithmReference:
              type: object
              description: Reference to the algorithm/approach used to generate the analysis
            CompetitorAnalysisRequestRecord:
              type: string
              description: Request record for the competitor analysis
            CompetitorAnalysisRequestWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the analysis
            CompetitorAnalysisRequestResult:
              type: string
              description: The output from performing the analysis
            CompetitorAnalysisUsageRecord:
              type: string
              description: Usage record of the competitor analysis maintained/developed by the function
            CompetitorAnalysisImpact:
              type: string
              description: A record of reported impact/accuracy of the competitor analysis
    ExecuteCompetitorAnalysisRequest:
      type: object
      properties:
        CompetitorAnalysis:
          type: object
          properties:
            CompetitorAnalysisRequestRecord:
              type: string
              description: Request record for the competitor analysis
            EmployeeOrBusinessUnitReference:
              type: object
              description: The employee/business unit requesting the analysis
            CompetitorAnalysisUsageRecord:
              type: string
              description: Usage record of the competitor analysis maintained/developed by the function
            CompetitorAnalysisImpact:
              type: string
              description: A record of reported impact/accuracy of the competitor analysis
    ExecuteCompetitorAnalysisResponse:
      type: object
      properties:
        CompetitorAnalysis:
          type: object
          properties:
            CompetitorAnalysisRequestRecord:
              type: string
              description: Request record for the competitor analysis
            CompetitorAnalysisRequestWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the analysis
            CompetitorAnalysisRequestResult:
              type: string
              description: The output from performing the analysis
    RequestCompetitorAnalysisRequest:
      type: object
      properties:
        CompetitorAnalysis:
          type: object
          properties:
            CompetitorAnalysisRequestRecord:
              type: string
              description: Request record for the competitor analysis
            EmployeeOrBusinessUnitReference:
              type: object
              description: The employee/business unit requesting the analysis
            CompetitorAnalysisUsageRecord:
              type: string
              description: Usage record of the competitor analysis maintained/developed by the function
            CompetitorAnalysisImpact:
              type: string
              description: A record of reported impact/accuracy of the competitor analysis
    RequestCompetitorAnalysisResponse:
      type: object
      properties:
        CompetitorAnalysis:
          type: object
          properties:
            CompetitorAnalysisRequestRecord:
              type: string
              description: Request record for the competitor analysis
            CompetitorAnalysisRequestWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the analysis
            CompetitorAnalysisRequestResult:
              type: string
              description: The output from performing the analysis
    RetrieveCompetitorAnalysisResponse:
      type: object
      properties:
        CompetitorAnalysis:
          type: object
          properties:
            CompetitorAnalysisType:
              type: string
              description: The type of research view provided by the research (e.g. pricing comparison)
            CompetitorAnalysisSpecification:
              type: string
              description: The definition of the specific competitor analysis
            CompetitorAnalysisGuidance:
              type: string
              description: Guidance on usage and interpretation of the competitor analysis (e.g. qualifying the accuracy/confidence of any findings)
            CompetitorAnalysisAlgorithmReference:
              type: object
              description: Reference to the algorithm/approach used to generate the analysis
            CompetitorAnalysisRequestRecord:
              type: string
              description: Request record for the competitor analysis
            EmployeeOrBusinessUnitReference:
              type: object
              description: The employee/business unit requesting the analysis
            CompetitorAnalysisRequestWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the analysis
            CompetitorAnalysisRequestResult:
              type: string
              description: The output from performing the analysis
            CompetitorAnalysisUsageRecord:
              type: string
              description: Usage record of the competitor analysis maintained/developed by the function
            CompetitorAnalysisImpact:
              type: string
              description: A record of reported impact/accuracy of the competitor analysis
  parameters:
    CompetitorAnalysisID:
      name: competitoranalysisId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    AnalysisAlgorithmID:
      name: analysisalgorithmId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    EvaluateCompetitorAnalysisRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateCompetitorAnalysisRequest'
    ExecuteCompetitorAnalysisRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExecuteCompetitorAnalysisRequest'
    RequestCompetitorAnalysisRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestCompetitorAnalysisRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
