openapi: 3.0.1
info:
  title: Credit Management
  description: This service domain provides a bank-wide/oversight function to qualify credit pricing for offered products and services to reflect the bank's appetite to write the business. This decision can override the standard product pricing procedure
  version: 10.1.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/CreditManagement/10.1.0
paths:
  /CreditManagement/Evaluate:
    post:
      tags:
      - CR - CreditPricingAssessment
      summary: EvCR Evaluate a proposed transaction pricing against group credit policy
      description: EvCR Evaluate a proposed transaction pricing against group credit policy
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/EvaluateCreditPricingAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateCreditPricingAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditManagement/{creditmanagementId}/Update:
    put:
      tags:
      - CR - CreditPricingAssessment
      summary: UpCR Update details of an active credit pricing assessment
      description: UpCR Update details of an active credit pricing assessment
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/CreditManagementID'
      requestBody:
        $ref: '#/components/requestBodies/UpdateCreditPricingAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCreditPricingAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /CreditManagement/{creditmanagementId}/Retrieve:
    get:
      tags:
      - CR - CreditPricingAssessment
      summary: ReCR Retrieve details about a credit pricing assessment
      description: ReCR Retrieve details about a credit pricing assessment
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/CreditManagementID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditPricingAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    CreditPricingAssessment:
      type: object
      properties:
        BusinessUnitReference:
          type: object
          description: Business unit submitting the proposed transaction for review
        CustomerReference:
          type: object
          description: Reference to the customer related to the proposed transaction
        SectorReference:
          type: object
          description: The sector where the proposed transaction would be booked
        ProductType:
          type: string
          description: The product type/category of the proposed transaction for the credit pricing assessment
        ProposedTransactionReference:
          type: object
          description: Reference to proposed transaction submitted for assessment
        ProposedTransactionRecord:
          type: string
          description: Key details of the proposed transaction
        ProposedTransactionType:
          type: string
          description: The type of credit instrument being considered
        ProposedTransactionAmount:
          type: number
          description: The financial structure of the proposed transaction
        ProposedTransactionRecordDate:
          type: string
          description: One or more key dates associated with the transaction
        ProposedTransactionBookingEntity:
          type: string
          description: The booking entity within the bank that the proposed transaction would impact
        ProposedTransactionCreditPricingAssessment:
          type: string
          description: Details of the credit pricing assessment, permitting or adjusting terms as necessary
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: NA
        status:
          type: string
          description: NA
        message:
          type: string
          description: NA
    EvaluateCreditPricingAssessmentRequest:
      type: object
      properties:
        CreditPricingAssessment:
          type: object
          properties:
            BusinessUnitReference:
              type: object
              description: Business unit submitting the proposed transaction for review
            CustomerReference:
              type: object
              description: Reference to the customer related to the proposed transaction
            SectorReference:
              type: object
              description: The sector where the proposed transaction would be booked
            ProductType:
              type: string
              description: The product type/category of the proposed transaction for the credit pricing assessment
            ProposedTransactionReference:
              type: object
              description: Reference to proposed transaction submitted for assessment
            ProposedTransactionRecord:
              type: string
              description: Key details of the proposed transaction
            ProposedTransactionType:
              type: string
              description: The type of credit instrument being considered
            ProposedTransactionAmount:
              type: number
              description: The financial structure of the proposed transaction
            ProposedTransactionRecordDate:
              type: string
              description: One or more key dates associated with the transaction
            ProposedTransactionBookingEntity:
              type: string
              description: The booking entity within the bank that the proposed transaction would impact
    EvaluateCreditPricingAssessmentResponse:
      type: object
      properties:
        CreditPricingAssessment:
          type: object
          properties:
            ProposedTransactionCreditPricingAssessment:
              type: string
              description: Details of the credit pricing assessment, permitting or adjusting terms as necessary
    UpdateCreditPricingAssessmentRequest:
      type: object
      properties:
        CreditPricingAssessment:
          type: object
          properties:
            BusinessUnitReference:
              type: object
              description: Business unit submitting the proposed transaction for review
            CustomerReference:
              type: object
              description: Reference to the customer related to the proposed transaction
            SectorReference:
              type: object
              description: The sector where the proposed transaction would be booked
            ProductType:
              type: string
              description: The product type/category of the proposed transaction for the credit pricing assessment
            ProposedTransactionReference:
              type: object
              description: Reference to proposed transaction submitted for assessment
            ProposedTransactionRecord:
              type: string
              description: Key details of the proposed transaction
            ProposedTransactionType:
              type: string
              description: The type of credit instrument being considered
            ProposedTransactionAmount:
              type: number
              description: The financial structure of the proposed transaction
            ProposedTransactionRecordDate:
              type: string
              description: One or more key dates associated with the transaction
            ProposedTransactionBookingEntity:
              type: string
              description: The booking entity within the bank that the proposed transaction would impact
    UpdateCreditPricingAssessmentResponse:
      type: object
      properties:
        CreditPricingAssessment:
          type: object
          properties:
            BusinessUnitReference:
              type: object
              description: Business unit submitting the proposed transaction for review
            CustomerReference:
              type: object
              description: Reference to the customer related to the proposed transaction
            SectorReference:
              type: object
              description: The sector where the proposed transaction would be booked
            ProductType:
              type: string
              description: The product type/category of the proposed transaction for the credit pricing assessment
            ProposedTransactionReference:
              type: object
              description: Reference to proposed transaction submitted for assessment
            ProposedTransactionRecord:
              type: string
              description: Key details of the proposed transaction
            ProposedTransactionType:
              type: string
              description: The type of credit instrument being considered
            ProposedTransactionAmount:
              type: number
              description: The financial structure of the proposed transaction
            ProposedTransactionRecordDate:
              type: string
              description: One or more key dates associated with the transaction
            ProposedTransactionBookingEntity:
              type: string
              description: The booking entity within the bank that the proposed transaction would impact
  parameters:
    CreditManagementID:
      name: creditmanagementId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    EvaluateCreditPricingAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateCreditPricingAssessmentRequest'
    UpdateCreditPricingAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateCreditPricingAssessmentRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
