openapi: 3.0.1
info:
  title: Credit Management
  description: This service domain provides a bank-wide/oversight function to qualify credit pricing for offered products and services to reflect the bank's appetite to write the business. This decision can override the standard product pricing procedure
  contact:
    name: BIAN
    url: https://bian.org
  version: '10.1.0'
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/CreditManagement/10.1.0
paths:
  /CreditManagement/Evaluate:
    post:
      tags:
        - CR - CreditPricingAssessment
      summary: EvCR Evaluate a proposed transaction pricing against group credit policy
      description: EvCR Evaluate a proposed transaction pricing against group credit policy
      operationId: Evaluate
      requestBody:
        $ref: '#/components/requestBodies/EvaluateCreditPricingAssessmentRequest'
      responses:
        '200':
          $ref: '#/components/responses/EvaluateCreditPricingAssessmentResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditManagement/{creditmanagementid}/Update':
    put:
      tags:
        - CR - CreditPricingAssessment
      summary: UpCR Update details of an active credit pricing assessment
      description: UpCR Update details of an active credit pricing assessment
      operationId: Update
      parameters:
        - $ref: '#/components/parameters/creditmanagementid'
      requestBody:
        $ref: '#/components/requestBodies/UpdateCreditPricingAssessmentRequest'
      responses:
        '200':
          $ref: '#/components/responses/UpdateCreditPricingAssessmentResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/CreditManagement/{creditmanagementid}/Retrieve':
    get:
      tags:
        - CR - CreditPricingAssessment
      summary: ReCR Retrieve details about a credit pricing assessment
      description: ReCR Retrieve details about a credit pricing assessment
      operationId: Retrieve
      parameters:
        - $ref: '#/components/parameters/creditmanagementid'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveCreditPricingAssessmentResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    string:
      type: object
    HTTPError:
      type: object
      properties:
        status_code:
          $ref: '#/components/schemas/string'
        status:
          $ref: '#/components/schemas/string'
        message:
          $ref: '#/components/schemas/string'
      description: Status Attributes
    datatype:
      type: object
      description: ''
    object:
      type: object
      properties:
        Object:
          $ref: '#/components/schemas/string'
      description: Business unit submitting the proposed transaction for review
    amount:
      type: object
      properties:
        Amount:
          $ref: '#/components/schemas/string'
      description: The financial structure of the proposed transaction
    date:
      type: object
      properties:
        Date:
          $ref: '#/components/schemas/string'
      description: One or more key dates associated with the transaction
    CreditPricingAssessment:
      type: object
      properties:
        BusinessUnitReference:
          $ref: '#/components/schemas/object'
        CustomerReference:
          $ref: '#/components/schemas/object'
        SectorReference:
          $ref: '#/components/schemas/object'
        ProductType:
          type: string
          description: The product type/category of the proposed transaction for the credit pricing assessment
          format: string
        ProposedTransactionReference:
          $ref: '#/components/schemas/object'
        ProposedTransactionRecord:
          type: string
          description: Key details of the proposed transaction
          format: string
        ProposedTransactionType:
          type: string
          description: The type of credit instrument being considered
          format: string
        ProposedTransactionAmount:
          $ref: '#/components/schemas/amount'
        ProposedTransactionRecordDate:
          $ref: '#/components/schemas/date'
        ProposedTransactionBookingEntity:
          type: string
          description: The booking entity within the bank that the proposed transaction would impact
          format: string
        ProposedTransactionCreditPricingAssessment:
          type: string
          description: 'Details of the credit pricing assessment, permitting or adjusting terms as necessary'
          format: string
      description: 'To test or assess an entity, possibly against some formal qualification or certification requirement within Credit Management. '
    EvaluateCreditPricingAssessmentRequest:
      type: object
      properties:
        CreditPricingAssessment:
          type: object
          properties:
            BusinessUnitReference:
              $ref: '#/components/schemas/object'
            CustomerReference:
              $ref: '#/components/schemas/object'
            SectorReference:
              $ref: '#/components/schemas/object'
            ProductType:
              type: string
              description: The product type/category of the proposed transaction for the credit pricing assessment
              format: string
            ProposedTransactionReference:
              $ref: '#/components/schemas/object'
            ProposedTransactionRecord:
              type: string
              description: Key details of the proposed transaction
              format: string
            ProposedTransactionType:
              type: string
              description: The type of credit instrument being considered
              format: string
            ProposedTransactionAmount:
              $ref: '#/components/schemas/amount'
            ProposedTransactionRecordDate:
              $ref: '#/components/schemas/date'
            ProposedTransactionBookingEntity:
              type: string
              description: The booking entity within the bank that the proposed transaction would impact
              format: string
      description: 'Input: EvCR Evaluate a proposed transaction pricing against group credit policy'
    EvaluateCreditPricingAssessmentResponse:
      type: object
      properties:
        CreditPricingAssessment:
          type: object
          properties:
            ProposedTransactionCreditPricingAssessment:
              type: string
              description: 'Details of the credit pricing assessment, permitting or adjusting terms as necessary'
              format: string
      description: 'Output: EvCR Evaluate a proposed transaction pricing against group credit policy'
    UpdateCreditPricingAssessmentRequest:
      type: object
      properties:
        CreditPricingAssessment:
          type: object
          properties:
            BusinessUnitReference:
              $ref: '#/components/schemas/object'
            CustomerReference:
              $ref: '#/components/schemas/object'
            SectorReference:
              $ref: '#/components/schemas/object'
            ProductType:
              type: string
              description: The product type/category of the proposed transaction for the credit pricing assessment
              format: string
            ProposedTransactionReference:
              $ref: '#/components/schemas/object'
            ProposedTransactionRecord:
              type: string
              description: Key details of the proposed transaction
              format: string
            ProposedTransactionType:
              type: string
              description: The type of credit instrument being considered
              format: string
            ProposedTransactionAmount:
              $ref: '#/components/schemas/amount'
            ProposedTransactionRecordDate:
              $ref: '#/components/schemas/date'
            ProposedTransactionBookingEntity:
              type: string
              description: The booking entity within the bank that the proposed transaction would impact
              format: string
      description: 'Input: UpCR Update details of an active credit pricing assessment'
    UpdateCreditPricingAssessmentResponse:
      type: object
      properties:
        CreditPricingAssessment:
          type: object
          properties:
            BusinessUnitReference:
              $ref: '#/components/schemas/object'
            CustomerReference:
              $ref: '#/components/schemas/object'
            SectorReference:
              $ref: '#/components/schemas/object'
            ProductType:
              type: string
              description: The product type/category of the proposed transaction for the credit pricing assessment
              format: string
            ProposedTransactionReference:
              $ref: '#/components/schemas/object'
            ProposedTransactionRecord:
              type: string
              description: Key details of the proposed transaction
              format: string
            ProposedTransactionType:
              type: string
              description: The type of credit instrument being considered
              format: string
            ProposedTransactionAmount:
              $ref: '#/components/schemas/amount'
            ProposedTransactionRecordDate:
              $ref: '#/components/schemas/date'
            ProposedTransactionBookingEntity:
              type: string
              description: The booking entity within the bank that the proposed transaction would impact
              format: string
      description: 'Output: UpCR Update details of an active credit pricing assessment'
    RetrieveCreditPricingAssessmentResponse:
      type: object
      properties:
        CreditPricingAssessment:
          type: object
          properties:
            BusinessUnitReference:
              $ref: '#/components/schemas/object'
            CustomerReference:
              $ref: '#/components/schemas/object'
            SectorReference:
              $ref: '#/components/schemas/object'
            ProductType:
              type: string
              description: The product type/category of the proposed transaction for the credit pricing assessment
              format: string
            ProposedTransactionReference:
              $ref: '#/components/schemas/object'
            ProposedTransactionRecord:
              type: string
              description: Key details of the proposed transaction
              format: string
            ProposedTransactionType:
              type: string
              description: The type of credit instrument being considered
              format: string
            ProposedTransactionAmount:
              $ref: '#/components/schemas/amount'
            ProposedTransactionRecordDate:
              $ref: '#/components/schemas/date'
            ProposedTransactionBookingEntity:
              type: string
              description: The booking entity within the bank that the proposed transaction would impact
              format: string
            ProposedTransactionCreditPricingAssessment:
              type: string
              description: 'Details of the credit pricing assessment, permitting or adjusting terms as necessary'
              format: string
      description: 'Output: ReCR Retrieve details about a credit pricing assessment'
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    EvaluateCreditPricingAssessmentResponse:
      description: EvaluateCreditPricingAssessmentResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateCreditPricingAssessmentResponse'
    UpdateCreditPricingAssessmentResponse:
      description: UpdateCreditPricingAssessmentResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateCreditPricingAssessmentResponse'
    RetrieveCreditPricingAssessmentResponse:
      description: RetrieveCreditPricingAssessmentResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveCreditPricingAssessmentResponse'
  parameters:
    creditmanagementid:
      name: creditmanagementid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    EvaluateCreditPricingAssessmentRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateCreditPricingAssessmentRequest'
      required: true
    UpdateCreditPricingAssessmentRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateCreditPricingAssessmentRequest'
      required: true