openapi: 3.0.1
info:
  title: Fraud Diagnosis
  description: This service domain handles the evaluation of detected possible fraud to support an appropriate response to contain the exposure
  version: 10.1.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/FraudDiagnosis/10.1.0
paths:
  /FraudDiagnosis/Evaluate:
    post:
      tags:
      - CR - FraudDiagnosisAnalysis
      summary: EvCR Start a fraud diagnosis evaluation on a transaction
      description: EvCR Start a fraud diagnosis evaluation on a transaction
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/EvaluateFraudDiagnosisAnalysisRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateFraudDiagnosisAnalysisResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudDiagnosis/{frauddiagnosisId}/Update:
    put:
      tags:
      - CR - FraudDiagnosisAnalysis
      summary: UpCR Update details for an active fraud diagnosis
      description: UpCR Update details for an active fraud diagnosis
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/FraudDiagnosisID'
      requestBody:
        $ref: '#/components/requestBodies/UpdateFraudDiagnosisAnalysisRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateFraudDiagnosisAnalysisResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudDiagnosis/{frauddiagnosisId}/Retrieve:
    get:
      tags:
      - CR - FraudDiagnosisAnalysis
      summary: ReCR Retrieve details about a fraud diagnosis
      description: ReCR Retrieve details about a fraud diagnosis
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/FraudDiagnosisID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FraudDiagnosisAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudDiagnosis/{frauddiagnosisId}/CustomerBehavior/{customerbehaviorId}/Retrieve:
    get:
      tags:
      - BQ - CustomerBehavior
      summary: ReBQ Retrieve details about a customer behavior analysis
      description: ReBQ Retrieve details about a customer behavior analysis
      operationId: RetrieveCustomerBehavior
      parameters:
      - $ref: '#/components/parameters/FraudDiagnosisID'
      - $ref: '#/components/parameters/CustomerBehaviorID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FraudDiagnosisAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudDiagnosis/{frauddiagnosisId}/EconomicModel/{economicmodelId}/Retrieve:
    get:
      tags:
      - BQ - EconomicModel
      summary: ReBQ Retrieve details about an economic model analysis
      description: ReBQ Retrieve details about an economic model analysis
      operationId: RetrieveEconomicModel
      parameters:
      - $ref: '#/components/parameters/FraudDiagnosisID'
      - $ref: '#/components/parameters/EconomicModelID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FraudDiagnosisAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudDiagnosis/{frauddiagnosisId}/AnalystReview/{analystreviewId}/Request:
    put:
      tags:
      - BQ - AnalystReview
      summary: RqBQ Request access to an analist for an active diagnosis
      description: RqBQ Request access to an analist for an active diagnosis
      operationId: RequestAnalystReview
      parameters:
      - $ref: '#/components/parameters/FraudDiagnosisID'
      - $ref: '#/components/parameters/AnalystReviewID'
      requestBody:
        $ref: '#/components/requestBodies/RequestAnalystReviewRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalystReview'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /FraudDiagnosis/{frauddiagnosisId}/AnalystReview/{analystreviewId}/Retrieve:
    get:
      tags:
      - BQ - AnalystReview
      summary: ReBQ Retrieve details about a analyst review of a transaction
      description: ReBQ Retrieve details about a analyst review of a transaction
      operationId: RetrieveAnalystReview
      parameters:
      - $ref: '#/components/parameters/FraudDiagnosisID'
      - $ref: '#/components/parameters/AnalystReviewID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FraudDiagnosisAnalysis'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    FraudDiagnosisAnalysis:
      type: object
      properties:
        ProductProductionSessionReference:
          type: object
          description: Reference to the product fulfillment production session for which fraud diagnosis is performed
        FraudDiagnosisEvaluationProfile:
          type: string
          description: Details the types of fraud diagnosis algorithms and tests are applied
        FraudDiagnosisTransactionConsolidationRecord:
          type: string
          description: The production transaction details that are submitted for fraud diagnosis
        FraudEvaluationProductionAnomalyRecord:
          type: string
          description: Details of detected out of pattern production activity that could be fraud highlighted by Fraud Evaluation
        FraudEvaluationProductionAnomalyProductionTransactionReference:
          type: object
          description: Reference to the one or more production transactions isolated by the fraud evaluation tests identified by Fraud Evaluation
        FraudDiagnosisDetermination:
          type: string
          description: Details the conclusion of the analysis and determination (e.g. diagnosis of likely fraud)
        FraudDiagnosisRecommendation:
          type: string
          description: Details the recommended action in response to the analysis (e.g. accept or reject the transaction, flag account for fraud)
    CustomerBehavior:
      type: object
      properties:
        CustomerBehaviorAnalysisResult:
          type: string
          description: The production transaction customer behavior analysis results
        CustomerBehaviorAnalysisWorkProduct:
          type: string
          description: Work documentation, forms and schedules produced and referenced during the analysis (for future reference)
    EconomicModel:
      type: object
      properties:
        EconomicModelAnalysisResult:
          type: string
          description: The result of the economic model, including the recommended response
        EconomicModelWorkProduct:
          type: string
          description: Work documentation, forms and schedules produced and referenced during the analysis (for future reference)
    AnalystReview:
      type: object
      properties:
        CustomerReference:
          type: object
          description: Reference to the customer, extracted from the financial transaction details, used to access customer details
        OutboundContactReference:
          type: object
          description: Reference to an outbound contact established with the customer
        AnalystReviewAnalysisResult:
          type: string
          description: The result of the economic model, including the recommended response
        AnalystReviewWorkProduct:
          type: string
          description: Work documentation, forms and schedules produced and referenced during the analysis (for future reference)
        AnalystReviewRecommendedAction:
          type: string
          description: The recommended action resulting from the analysts review
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: NA
        status:
          type: string
          description: NA
        message:
          type: string
          description: NA
    EvaluateFraudDiagnosisAnalysisRequest:
      type: object
      properties:
        FraudDiagnosisAnalysis:
          type: object
          properties:
            ProductProductionSessionReference:
              type: object
              description: Reference to the product fulfillment production session for which fraud diagnosis is performed
            FraudDiagnosisEvaluationProfile:
              type: string
              description: Details the types of fraud diagnosis algorithms and tests are applied
            FraudDiagnosisTransactionConsolidationRecord:
              type: string
              description: The production transaction details that are submitted for fraud diagnosis
            FraudEvaluationProductionAnomalyRecord:
              type: string
              description: Details of detected out of pattern production activity that could be fraud highlighted by Fraud Evaluation
            FraudEvaluationProductionAnomalyProductionTransactionReference:
              type: object
              description: Reference to the one or more production transactions isolated by the fraud evaluation tests identified by Fraud Evaluation
    EvaluateFraudDiagnosisAnalysisResponse:
      type: object
      properties:
        FraudDiagnosisAnalysis:
          type: object
          properties:
            FraudDiagnosisEvaluationProfile:
              type: string
              description: Details the types of fraud diagnosis algorithms and tests are applied
            FraudDiagnosisDetermination:
              type: string
              description: Details the conclusion of the analysis and determination (e.g. diagnosis of likely fraud)
            FraudDiagnosisRecommendation:
              type: string
              description: Details the recommended action in response to the analysis (e.g. accept or reject the transaction, flag account for fraud)
    UpdateFraudDiagnosisAnalysisRequest:
      type: object
      properties:
        FraudDiagnosisAnalysis:
          type: object
          properties:
            ProductProductionSessionReference:
              type: object
              description: Reference to the product fulfillment production session for which fraud diagnosis is performed
            FraudDiagnosisEvaluationProfile:
              type: string
              description: Details the types of fraud diagnosis algorithms and tests are applied
            FraudDiagnosisTransactionConsolidationRecord:
              type: string
              description: The production transaction details that are submitted for fraud diagnosis
            FraudEvaluationProductionAnomalyRecord:
              type: string
              description: Details of detected out of pattern production activity that could be fraud highlighted by Fraud Evaluation
            FraudEvaluationProductionAnomalyProductionTransactionReference:
              type: object
              description: Reference to the one or more production transactions isolated by the fraud evaluation tests identified by Fraud Evaluation
    UpdateFraudDiagnosisAnalysisResponse:
      type: object
      properties:
        FraudDiagnosisAnalysis:
          type: object
          properties:
            ProductProductionSessionReference:
              type: object
              description: Reference to the product fulfillment production session for which fraud diagnosis is performed
            FraudDiagnosisEvaluationProfile:
              type: string
              description: Details the types of fraud diagnosis algorithms and tests are applied
            FraudDiagnosisTransactionConsolidationRecord:
              type: string
              description: The production transaction details that are submitted for fraud diagnosis
            FraudEvaluationProductionAnomalyRecord:
              type: string
              description: Details of detected out of pattern production activity that could be fraud highlighted by Fraud Evaluation
            FraudEvaluationProductionAnomalyProductionTransactionReference:
              type: object
              description: Reference to the one or more production transactions isolated by the fraud evaluation tests identified by Fraud Evaluation
    RequestAnalystReviewRequest:
      type: object
      properties:
        AnalystReview:
          type: object
          properties:
            CustomerReference:
              type: object
              description: Reference to the customer, extracted from the financial transaction details, used to access customer details
  parameters:
    FraudDiagnosisID:
      name: frauddiagnosisId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    CustomerBehaviorID:
      name: customerbehaviorId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    EconomicModelID:
      name: economicmodelId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    AnalystReviewID:
      name: analystreviewId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    EvaluateFraudDiagnosisAnalysisRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateFraudDiagnosisAnalysisRequest'
    UpdateFraudDiagnosisAnalysisRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateFraudDiagnosisAnalysisRequest'
    RequestAnalystReviewRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestAnalystReviewRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
