openapi: 3.0.1
info:
  title: Information Provider Operation
  description: ''
  contact:
    name: BIAN
    url: https://bian.org
  version: '10.1.0'
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/InformationProviderOperation/10.1.0
paths:
  '/InformationProviderOperation/{informationprovideroperationid}/Control':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Control Information Feed Operating Session
      description: Control Information Feed Operating Session
      operationId: Control
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Exchange':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Exchange Information Feed Operating Session
      description: Exchange Information Feed Operating Session
      operationId: Exchange
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Execute':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Execute Information Feed Operating Session
      description: Execute Information Feed Operating Session
      operationId: Execute
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/Initiate:
    post:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Initiate Information Feed Operating Session
      description: Initiate Information Feed Operating Session
      operationId: Initiate
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Notify':
    get:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Notify Information Feed Operating Session
      description: Notify Information Feed Operating Session
      operationId: Notify
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Request':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Request Information Feed Operating Session
      description: Request Information Feed Operating Session
      operationId: Request
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Retrieve':
    get:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Retrieve Information Feed Operating Session
      description: Retrieve Information Feed Operating Session
      operationId: Retrieve
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Update':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Update Information Feed Operating Session
      description: Update Information Feed Operating Session
      operationId: Update
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    attribute:
      type: object
      properties:
        String:
          type: string
          description: ''
          format: primitivetype
      description: ''
    event:
      type: object
      properties:
        EventType:
          $ref: '#/components/schemas/attribute'
        EventDateTime:
          $ref: '#/components/schemas/attribute'
        EventDescription:
          $ref: '#/components/schemas/attribute'
        EventSource:
          $ref: '#/components/schemas/attribute'
        EventLocation:
          $ref: '#/components/schemas/attribute'
        EventAction:
          $ref: '#/components/schemas/attribute'
        EventStatus:
          $ref: '#/components/schemas/attribute'
        EventValue:
          $ref: '#/components/schemas/attribute'
        EventValidityPeriod:
          $ref: '#/components/schemas/attribute'
        EventIdentification:
          $ref: '#/components/schemas/attribute'
      description: ''
    text:
      type: object
      properties:
        Text:
          type: string
          description: Text is a character string such as a finite set of characters generally in the form of words of a language. (UN/CEFACT)
          format: datatype
      description: ''
    InformationProviderOperationOutcome:
      type: object
      properties:
        InformationProviderOperationIncident:
          $ref: '#/components/schemas/event'
        InformationProviderOperationProvision:
          $ref: '#/components/schemas/text'
      description: "The collection of operational serivces/functions offered by the operational facility\n\nExamples: messages, capture, routines"
    schedule:
      type: object
      properties:
        Schedule:
          type: string
          description: "Defined sequence of planned tasks/actions or a timetable of available services\n\nA schedule is a time based series of something"
          format: datatype
      description: Timetable to operate Information Feed Operating Session
    status:
      type: object
      properties:
        Status:
          type: string
          description: A characteristic that describe the object by referring to a state transition in its lifecycle.
          format: datatype
      description: The status of Information Feed Operating Session
    log:
      type: object
      properties:
        LogType:
          $ref: '#/components/schemas/attribute'
        LogPeriod:
          $ref: '#/components/schemas/attribute'
        LogDate:
          $ref: '#/components/schemas/attribute'
        LogIdentification:
          $ref: '#/components/schemas/attribute'
      description: Reference to the log of (usage) ativities/events  of Information Feed Operating Session
    involvedparty:
      type: object
      properties:
        Involvedparty:
          type: string
          description: ''
          format: datatype
      description: Reference to the party who is involved in Information Feed Operating Session
    sessiontype:
      type: object
      properties:
        Sessiontype:
          type: string
          description: "A Classification value that distinguishes between the type of operations within the session like\n- Customer Contact Session\n- Customer Dialogue Session\n- Channel Operating Session\n- Gateway Operating Session\n- Switch Operating Session"
          format: datatype
      description: A Classification value that distinguishes between the type of operations within Information Feed Operating Session
    servicetype:
      type: object
      properties:
        Servicetype:
          type: string
          description: Data type specifies the classification of service
          format: datatype
      description: A Classification value that distinguishes between the type of services within Information Feed Operating Session
    systemconfigurationoption:
      type: object
      properties:
        SystemConfigurationOption:
          type: string
          description: "Options for configuring the system or the function/feature of system.\n"
          format: class
      description: The configuration of Information Feed Operating Session
    session:
      type: object
      properties:
        SessionDuration:
          $ref: '#/components/schemas/attribute'
        SessionDateTime:
          $ref: '#/components/schemas/attribute'
        SessionStatus:
          $ref: '#/components/schemas/attribute'
        SessionType:
          $ref: '#/components/schemas/attribute'
        SessionScheduel:
          $ref: '#/components/schemas/attribute'
      description: An unique reference to an item or an occurrence of Information Feed Operating Session
    InformationFeedOperatingSession:
      type: object
      properties:
        InformationFeedOperatingSessionSchedule:
          $ref: '#/components/schemas/schedule'
        InformationFeedOperatingSessionStatus:
          $ref: '#/components/schemas/status'
        InformationFeedOperatingSessionUsageLog:
          $ref: '#/components/schemas/log'
        InformationFeedOperatingSessionAssociatedPartyReference:
          $ref: '#/components/schemas/involvedparty'
        InformationFeedOperatingSessionServiceProviderReference:
          $ref: '#/components/schemas/involvedparty'
        InformationFeedOperatingSessionType:
          $ref: '#/components/schemas/sessiontype'
        InformationFeedOperatingSessionServiceProviderSchedule:
          $ref: '#/components/schemas/schedule'
        InformationFeedOperatingSessionServiceType:
          $ref: '#/components/schemas/servicetype'
        InformationFeedOperatingSessionServiceConfiguration:
          $ref: '#/components/schemas/systemconfigurationoption'
        InformationFeedOperatingSessionReference:
          $ref: '#/components/schemas/session'
      description: 'Operate equipment and/or a largely automated facility within Information Provider Operation. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InformationFeedOperatingSession:
      description: InformationFeedOperatingSession
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InformationFeedOperatingSession'
  parameters:
    informationprovideroperationid:
      name: informationprovideroperationid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    InformationFeedOperatingSession:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InformationFeedOperatingSession'
      required: true