openapi: 3.0.1
info:
  title: Information Provider Operation
  description: ''
  contact:
    name: BIAN
    url: https://bian.org
  version: '10.1.0'
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/InformationProviderOperation/10.1.0
paths:
  '/InformationProviderOperation/{informationprovideroperationid}/Control':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Control Information Feed Operating Session
      description: Control Information Feed Operating Session
      operationId: Control
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Exchange':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Exchange Information Feed Operating Session
      description: Exchange Information Feed Operating Session
      operationId: Exchange
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Execute':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Execute Information Feed Operating Session
      description: Execute Information Feed Operating Session
      operationId: Execute
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/Initiate:
    post:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Initiate Information Feed Operating Session
      description: Initiate Information Feed Operating Session
      operationId: Initiate
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Notify':
    get:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Notify Information Feed Operating Session
      description: Notify Information Feed Operating Session
      operationId: Notify
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Request':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Request Information Feed Operating Session
      description: Request Information Feed Operating Session
      operationId: Request
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Retrieve':
    get:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Retrieve Information Feed Operating Session
      description: Retrieve Information Feed Operating Session
      operationId: Retrieve
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Update':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Update Information Feed Operating Session
      description: Update Information Feed Operating Session
      operationId: Update
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    event:
      type: object
      properties:
        EventType:
          type: string
          description: ''
          format: string
        Event:
          type: string
          description: 'Something that happens, has happened, can happen or is planned to happen.'
          format: class
      description: ''
    text:
      type: object
      properties:
        Text:
          type: string
          description: Text is a character string such as a finite set of characters generally in the form of words of a language. (UN/CEFACT)
          format: datatype
      description: ''
    InformationProviderOperationOutcome:
      type: object
      properties:
        InformationProviderOperationIncident:
          $ref: '#/components/schemas/event'
        InformationProviderOperationProvision:
          $ref: '#/components/schemas/text'
      description: "The collection of operational serivces/functions offered by the operational facility\n\nExamples: messages, capture, routines"
    schedule:
      type: object
      properties:
        ScheduleType:
          type: string
          description: ''
          format: string
      description: Timetable to operate Information Feed Operating Session
    status:
      type: object
      properties:
        StatusReason:
          $ref: '#/components/schemas/text'
        Status:
          type: string
          description: A characteristic that describe the object by referring to a state transition in its lifecycle.
          format: datatype
      description: The status of Information Feed Operating Session
    log:
      type: object
      properties:
        LogType:
          type: string
          description: ''
          format: string
        Log:
          type: string
          description: "A record of events/entries.\n"
          format: class
      description: Reference to the log of (usage) ativities/events  of Information Feed Operating Session
    name:
      type: object
      properties:
        Name:
          type: string
          description: 'A name is a word or phrase that constitutes the distinctive designation of a person, place, thing or concept. (UN/CEFAT)'
          format: datatype
      description: Name by which a party is known and which is usually used to identify that party. (ISO20022)
    party:
      type: object
      properties:
        PartyName:
          $ref: '#/components/schemas/name'
        Party:
          type: string
          description: "A party represents an autonomous entity in which a bank has a business interest. It has a legal definition and identity. A party is a Person, Organization, (a proposed definition for BIAN BOM adapted from BIAN Party Working Group) \n\n- Entity involved in an activity. (ISO20022)"
          format: class
      description: ''
    involvedparty:
      type: object
      properties:
        PartyReference:
          $ref: '#/components/schemas/party'
        Involvedparty:
          type: string
          description: ''
          format: datatype
      description: Reference to the party who is involved in Information Feed Operating Session
    sessiontype:
      type: object
      properties:
        SessionTypeName:
          $ref: '#/components/schemas/name'
        Sessiontype:
          type: string
          description: "A Classification value that distinguishes between the type of operations within the session like\n- Customer Contact Session\n- Customer Dialogue Session\n- Channel Operating Session\n- Gateway Operating Session\n- Switch Operating Session"
          format: datatype
      description: A Classification value that distinguishes between the type of operations within Information Feed Operating Session
    servicetype:
      type: object
      properties:
        ServiceTypeName:
          $ref: '#/components/schemas/name'
        Servicetype:
          type: string
          description: Data type specifies the classification of service
          format: datatype
      description: A Classification value that distinguishes between the type of services within Information Feed Operating Session
    systemconfigurationoption:
      type: object
      properties:
        SystemConfigurationOption:
          type: string
          description: "Options for configuring the system or the function/feature of system.\n"
          format: class
      description: The configuration of Information Feed Operating Session
    duration:
      type: object
      properties:
        Duration:
          type: string
          description: 'A duration is the specification of a length of time without a fixed start or end time, expressed in Gregorian calendar time units (Year, Month, Week, Day) and Hours, Minutes or Seconds. (UN/CEFACT)'
          format: datatype
      description: The time the session was active
    session:
      type: object
      properties:
        SessionDuration:
          $ref: '#/components/schemas/duration'
        Session:
          type: string
          description: "The operation of a system -- typically an automated system -- for a bounded period of time.\n\nSemi-permanent container of state for an information exchange with a system.\n\nTime-bounded, temporal unit of context and continuity, identifying a unit of work.\n"
          format: class
      description: An unique reference to an item or an occurrence of Information Feed Operating Session
    InformationFeedOperatingSession:
      type: object
      properties:
        InformationFeedOperatingSessionSchedule:
          $ref: '#/components/schemas/schedule'
        InformationFeedOperatingSessionStatus:
          $ref: '#/components/schemas/status'
        InformationFeedOperatingSessionUsageLog:
          $ref: '#/components/schemas/log'
        InformationFeedOperatingSessionAssociatedPartyReference:
          $ref: '#/components/schemas/involvedparty'
        InformationFeedOperatingSessionServiceProviderReference:
          $ref: '#/components/schemas/involvedparty'
        InformationFeedOperatingSessionType:
          $ref: '#/components/schemas/sessiontype'
        InformationFeedOperatingSessionServiceProviderSchedule:
          $ref: '#/components/schemas/schedule'
        InformationFeedOperatingSessionServiceType:
          $ref: '#/components/schemas/servicetype'
        InformationFeedOperatingSessionServiceConfiguration:
          $ref: '#/components/schemas/systemconfigurationoption'
        InformationFeedOperatingSessionReference:
          $ref: '#/components/schemas/session'
      description: 'Operate equipment and/or a largely automated facility within Information Provider Operation. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InformationFeedOperatingSession:
      description: InformationFeedOperatingSession
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InformationFeedOperatingSession'
  parameters:
    informationprovideroperationid:
      name: informationprovideroperationid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    InformationFeedOperatingSession:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InformationFeedOperatingSession'
      required: true