openapi: 3.0.1
info:
  title: Information Provider Operation
  description: ''
  version: 10.1.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/InformationProviderOperation/10.1.0
paths:
  /InformationProviderOperation/{informationprovideroperationId}/Control:
    put:
      tags:
      - CR - InformationFeedOperatingSession
      summary: Control Information Feed Operating Session
      description: Control Information Feed Operating Session
      operationId: Control
      parameters:
      - $ref: '#/components/parameters/InformationProviderOperationID'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformationFeedOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/{informationprovideroperationId}/Exchange:
    put:
      tags:
      - CR - InformationFeedOperatingSession
      summary: Exchange Information Feed Operating Session
      description: Exchange Information Feed Operating Session
      operationId: Exchange
      parameters:
      - $ref: '#/components/parameters/InformationProviderOperationID'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformationFeedOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/{informationprovideroperationId}/Execute:
    put:
      tags:
      - CR - InformationFeedOperatingSession
      summary: Execute Information Feed Operating Session
      description: Execute Information Feed Operating Session
      operationId: Execute
      parameters:
      - $ref: '#/components/parameters/InformationProviderOperationID'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformationFeedOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/Initiate:
    post:
      tags:
      - CR - InformationFeedOperatingSession
      summary: Initiate Information Feed Operating Session
      description: Initiate Information Feed Operating Session
      operationId: Initiate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformationFeedOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/{informationprovideroperationId}/Notify:
    get:
      tags:
      - CR - InformationFeedOperatingSession
      summary: Notify Information Feed Operating Session
      description: Notify Information Feed Operating Session
      operationId: Notify
      parameters:
      - $ref: '#/components/parameters/InformationProviderOperationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformationFeedOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/{informationprovideroperationId}/Request:
    put:
      tags:
      - CR - InformationFeedOperatingSession
      summary: Request Information Feed Operating Session
      description: Request Information Feed Operating Session
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/InformationProviderOperationID'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformationFeedOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/{informationprovideroperationId}/Retrieve:
    get:
      tags:
      - CR - InformationFeedOperatingSession
      summary: Retrieve Information Feed Operating Session
      description: Retrieve Information Feed Operating Session
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/InformationProviderOperationID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformationFeedOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/{informationprovideroperationId}/Update:
    put:
      tags:
      - CR - InformationFeedOperatingSession
      summary: Update Information Feed Operating Session
      description: Update Information Feed Operating Session
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/InformationProviderOperationID'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformationFeedOperatingSession'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    InformationFeedOperatingSession:
      type: object
      properties:
        InformationFeedOperatingSessionSchedule:
          type: object
          description: Timetable to operate Information Feed Operating Session
        InformationFeedOperatingSessionStatus:
          type: string
          description: The status of Information Feed Operating Session
        InformationFeedOperatingSessionUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events  of Information Feed Operating Session
        InformationFeedOperatingSessionAssociatedPartyReference:
          type: object
          description: Reference to the party who is involved in Information Feed Operating Session
        InformationFeedOperatingSessionServiceProviderReference:
          type: object
          description: Reference to the party who provides the services of Information Feed Operating Session
        InformationFeedOperatingSessionType:
          type: string
          description: A Classification value that distinguishes between the type of operations within Information Feed Operating Session
        InformationFeedOperatingSessionServiceProviderSchedule:
          type: object
          description: The schedule according to which the service provider will operate the Information Feed Operating Session
        InformationFeedOperatingSessionServiceType:
          type: string
          description: A Classification value that distinguishes between the type of services within Information Feed Operating Session
        InformationFeedOperatingSessionServiceConfiguration:
          type: string
          description: The configuration of Information Feed Operating Session
        InformationFeedOperatingSessionReference:
          type: string
          description: An unique reference to an item or an occurrence of Information Feed Operating Session
    InformationProviderOperationOutcome:
      type: object
      properties:
        InformationProviderOperationIncident:
          type: string
          description: ''
        InformationProviderOperationProvision:
          type: string
          description: ''
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: NA
        status:
          type: string
          description: NA
        message:
          type: string
          description: NA
  parameters:
    InformationProviderOperationID:
      name: informationprovideroperationId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    InformationProviderOperationOutcomeID:
      name: informationprovideroperationoutcomeId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    InformationFeedOperatingSession:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InformationFeedOperatingSession'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
