openapi: 3.0.1
info:
  title: Interactive Help
  description: Operate the automated facility that provides interactive context sensitive servicing guidance to employees and self-serve customers
  version: 10.1.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/InteractiveHelp/10.1.0
paths:
  /InteractiveHelp/{interactivehelpId}/HelpServiceSelection/Initiate:
    post:
      tags:
      - BQ - HelpServiceSelection
      summary: InBQ Initiate an interactive help service exchange
      description: InBQ Initiate an interactive help service exchange
      operationId: InitiateHelpServiceSelection
      parameters:
      - $ref: '#/components/parameters/InteractiveHelpID'
      requestBody:
        $ref: '#/components/requestBodies/InitiateHelpServiceSelectionRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateHelpServiceSelectionResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InteractiveHelp/{interactivehelpId}/HelpServiceSelection/{helpserviceselectionId}/Capture:
    put:
      tags:
      - BQ - HelpServiceSelection
      summary: CaBQ Capture user feedback relating to the service exchange
      description: CaBQ Capture user feedback relating to the service exchange
      operationId: CaptureHelpServiceSelection
      parameters:
      - $ref: '#/components/parameters/InteractiveHelpID'
      - $ref: '#/components/parameters/HelpServiceSelectionID'
      requestBody:
        $ref: '#/components/requestBodies/CaptureHelpServiceSelectionRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaptureHelpServiceSelectionResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InteractiveHelp/{interactivehelpId}/HelpServiceSelection/{helpserviceselectionId}/Execute:
    put:
      tags:
      - BQ - HelpServiceSelection
      summary: ExBQ Execute an automated action within the exchange
      description: ExBQ Execute an automated action within the exchange
      operationId: ExecuteHelpServiceSelection
      parameters:
      - $ref: '#/components/parameters/InteractiveHelpID'
      - $ref: '#/components/parameters/HelpServiceSelectionID'
      requestBody:
        $ref: '#/components/requestBodies/ExecuteHelpServiceSelectionRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecuteHelpServiceSelectionResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /InteractiveHelp/{interactivehelpId}/HelpServiceSelection/{helpserviceselectionId}/Retrieve:
    get:
      tags:
      - BQ - HelpServiceSelection
      summary: ReBQ Retrieve details about an interactive help service exchange
      description: ReBQ Retrieve details about an interactive help service exchange
      operationId: RetrieveHelpServiceSelection
      parameters:
      - $ref: '#/components/parameters/InteractiveHelpID'
      - $ref: '#/components/parameters/HelpServiceSelectionID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelpServiceSelection'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    interactiveHelpServiceOperatingSession:
      type: object
      properties: {}
    HelpServiceSelection:
      type: object
      properties:
        HelpSelectionInteractionType:
          type: string
          description: The type of session provides context for filtering content (e.g. employee, self-service customer)
        HelpSelectionProductandServiceType:
          type: string
          description: The type of product or service that is in context for the help request
        HelpSelectionProductFeatureType:
          type: string
          description: The specific product feature being accessed at the time of the help request
        SessionDialogueRecord:
          type: string
          description: The session dialogue log of actions during the contact to this point can be mined for key words that might improve the help selection
        HelpSelectionKeyWordMenu:
          type: string
          description: An interactive exchange can be supported where the service presents a menu of selection options or key words to narrow the search
        HelpSelectionKeyWordSelection:
          type: string
          description: The selected keyword or menu option
        InteractiveHelp:
          type: string
          description: The returned interactive help in any suitable form
        HelpSelectionTaskResult:
          type: string
          description: The user provided result of the interactive help service, including interaction statistics such as exchange frequency and duration
        HelpSelectionFeedback:
          type: string
          description: User provided commentary on the service provided
        Employee/BusinessUnitReference:
          type: object
          description: Reference to the employee, business unit providing service feedback
        Date/Time:
          type: string
          description: The date, time (and duration) of the service usage
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: NA
        status:
          type: string
          description: NA
        message:
          type: string
          description: NA
    InitiateHelpServiceSelectionRequest:
      type: object
      properties:
        HelpServiceSelection:
          type: object
          properties:
            HelpSelectionInteractionType:
              type: string
              description: The type of session provides context for filtering content (e.g. employee, self-service customer)
            HelpSelectionProductandServiceType:
              type: string
              description: The type of product or service that is in context for the help request
            HelpSelectionProductFeatureType:
              type: string
              description: The specific product feature being accessed at the time of the help request
            SessionDialogueRecord:
              type: string
              description: The session dialogue log of actions during the contact to this point can be mined for key words that might improve the help selection
            HelpSelectionKeyWordMenu:
              type: string
              description: An interactive exchange can be supported where the service presents a menu of selection options or key words to narrow the search
            HelpSelectionKeyWordSelection:
              type: string
              description: The selected keyword or menu option
            HelpSelectionTaskResult:
              type: string
              description: The user provided result of the interactive help service, including interaction statistics such as exchange frequency and duration
            HelpSelectionFeedback:
              type: string
              description: User provided commentary on the service provided
            EmployeeOrBusinessUnitReference:
              type: object
              description: Reference to the employee, business unit providing service feedback
            DateOrTime:
              type: string
              description: The date, time (and duration) of the service usage
    InitiateHelpServiceSelectionResponse:
      type: object
      properties:
        HelpServiceSelection:
          type: object
          properties:
            HelpSelectionInteractionType:
              type: string
              description: The type of session provides context for filtering content (e.g. employee, self-service customer)
            HelpSelectionProductandServiceType:
              type: string
              description: The type of product or service that is in context for the help request
            HelpSelectionProductFeatureType:
              type: string
              description: The specific product feature being accessed at the time of the help request
            HelpSelectionKeyWordMenu:
              type: string
              description: An interactive exchange can be supported where the service presents a menu of selection options or key words to narrow the search
            DateOrTime:
              type: string
              description: The date, time (and duration) of the service usage
    CaptureHelpServiceSelectionRequest:
      type: object
      properties:
        HelpServiceSelection:
          type: object
          properties:
            HelpSelectionTaskResult:
              type: string
              description: The user provided result of the interactive help service, including interaction statistics such as exchange frequency and duration
            HelpSelectionFeedback:
              type: string
              description: User provided commentary on the service provided
            EmployeeOrBusinessUnitReference:
              type: object
              description: Reference to the employee, business unit providing service feedback
            DateOrTime:
              type: string
              description: The date, time (and duration) of the service usage
    CaptureHelpServiceSelectionResponse:
      type: object
      properties:
        HelpServiceSelection:
          type: object
          properties:
            DateOrTime:
              type: string
              description: The date, time (and duration) of the service usage
    ExecuteHelpServiceSelectionRequest:
      type: object
      properties:
        HelpServiceSelection:
          type: object
          properties:
            HelpSelectionInteractionType:
              type: string
              description: The type of session provides context for filtering content (e.g. employee, self-service customer)
            HelpSelectionProductandServiceType:
              type: string
              description: The type of product or service that is in context for the help request
            HelpSelectionProductFeatureType:
              type: string
              description: The specific product feature being accessed at the time of the help request
            SessionDialogueRecord:
              type: string
              description: The session dialogue log of actions during the contact to this point can be mined for key words that might improve the help selection
            HelpSelectionKeyWordMenu:
              type: string
              description: An interactive exchange can be supported where the service presents a menu of selection options or key words to narrow the search
            HelpSelectionKeyWordSelection:
              type: string
              description: The selected keyword or menu option
            HelpSelectionTaskResult:
              type: string
              description: The user provided result of the interactive help service, including interaction statistics such as exchange frequency and duration
            HelpSelectionFeedback:
              type: string
              description: User provided commentary on the service provided
            EmployeeOrBusinessUnitReference:
              type: object
              description: Reference to the employee, business unit providing service feedback
            DateOrTime:
              type: string
              description: The date, time (and duration) of the service usage
    ExecuteHelpServiceSelectionResponse:
      type: object
      properties:
        HelpServiceSelection:
          type: object
          properties:
            HelpSelectionInteractionType:
              type: string
              description: The type of session provides context for filtering content (e.g. employee, self-service customer)
            HelpSelectionProductandServiceType:
              type: string
              description: The type of product or service that is in context for the help request
            HelpSelectionProductFeatureType:
              type: string
              description: The specific product feature being accessed at the time of the help request
            HelpSelectionKeyWordMenu:
              type: string
              description: An interactive exchange can be supported where the service presents a menu of selection options or key words to narrow the search
            InteractiveHelp:
              type: string
              description: The returned interactive help in any suitable form
            DateOrTime:
              type: string
              description: The date, time (and duration) of the service usage
  parameters:
    InteractiveHelpID:
      name: interactivehelpId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
    HelpServiceSelectionID:
      name: helpserviceselectionId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    InitiateHelpServiceSelectionRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitiateHelpServiceSelectionRequest'
    CaptureHelpServiceSelectionRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CaptureHelpServiceSelectionRequest'
    ExecuteHelpServiceSelectionRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExecuteHelpServiceSelectionRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
