openapi: 3.0.1
info:
  title: Legal Compliance
  description: Provide specialist legal advice, assess for legal compliance and resolve legal cases as they occur
  version: 10.1.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/LegalCompliance/10.1.0
paths:
  /LegalCompliance/Evaluate:
    post:
      tags:
      - CR - LegalComplianceAssessment
      summary: EvCR Start a legal assessment action
      description: EvCR Start a legal assessment action
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/EvaluateLegalComplianceAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateLegalComplianceAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /LegalCompliance/{legalcomplianceId}/Update:
    put:
      tags:
      - CR - LegalComplianceAssessment
      summary: UpCR Update submitted details or content for an on-going legal assessment
      description: UpCR Update submitted details or content for an on-going legal assessment
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/LegalComplianceID'
      requestBody:
        $ref: '#/components/requestBodies/UpdateLegalComplianceAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateLegalComplianceAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /LegalCompliance/{legalcomplianceId}/Request:
    put:
      tags:
      - CR - LegalComplianceAssessment
      summary: RqCR Request a review or adjudication for an assessment
      description: RqCR Request a review or adjudication for an assessment
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/LegalComplianceID'
      requestBody:
        $ref: '#/components/requestBodies/RequestLegalComplianceAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestLegalComplianceAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /LegalCompliance/{legalcomplianceId}/Retrieve:
    get:
      tags:
      - CR - LegalComplianceAssessment
      summary: ReCR Retrieve details and content from a legal assessment action
      description: ReCR Retrieve details and content from a legal assessment action
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/LegalComplianceID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalComplianceAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    LegalComplianceAssessment:
      type: object
      properties:
        LegalAssessmentType:
          type: string
          description: The type of law that is applied by the assessment action
        BusinessUnitReference:
          type: object
          description: The business function or unit assessed if appropriate
        ProductandServiceReference:
          type: object
          description: The associated product/service being assessed if appropriate
        CustomerReference:
          type: object
          description: Reference to the customer assessed if appropriate
        JurisdictionReference:
          type: object
          description: Indication of the legal jurisdiction that applies
        LawReference:
          type: object
          description: Reference to the specific law
        LawDefinition:
          type: string
          description: A definition of the required behavior to remain within the law
        LawComplianceandReportingRequirements:
          type: string
          description: Description of the measurements and reporting required to demonstrate legal compliance
        LawComplianceAccountability:
          type: string
          description: Explanation of the business context, responsibility and accountability for legal compliance
        LegalPenalties:
          type: string
          description: Outline of the possible implications of breaking the law
        LegalGuideline:
          type: string
          description: Guidelines and requirements for following the law
        DocumentReference:
          type: object
          description: Reference to any documentation classified/archived as appropriate
        LegalAssessmentWorkProducts:
          type: string
          description: Work documentation, forms and schedules produced and referenced during the legal assessment action
        LegalAssessmentResult:
          type: string
          description: Outcome/result of the legal assessment, this can include remedial actions
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: NA
        status:
          type: string
          description: NA
        message:
          type: string
          description: NA
    EvaluateLegalComplianceAssessmentRequest:
      type: object
      properties:
        LegalComplianceAssessment:
          type: object
          properties:
            LegalAssessmentType:
              type: string
              description: The type of law that is applied by the assessment action
            BusinessUnitReference:
              type: object
              description: The business function or unit assessed if appropriate
            ProductandServiceReference:
              type: object
              description: The associated product/service being assessed if appropriate
            CustomerReference:
              type: object
              description: Reference to the customer assessed if appropriate
            JurisdictionReference:
              type: object
              description: Indication of the legal jurisdiction that applies
            LawReference:
              type: object
              description: Reference to the specific law
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            LegalAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the legal assessment action
    EvaluateLegalComplianceAssessmentResponse:
      type: object
      properties:
        LegalComplianceAssessment:
          type: object
          properties:
            LegalAssessmentType:
              type: string
              description: The type of law that is applied by the assessment action
            LawDefinition:
              type: string
              description: A definition of the required behavior to remain within the law
            LawComplianceandReportingRequirements:
              type: string
              description: Description of the measurements and reporting required to demonstrate legal compliance
            LawComplianceAccountability:
              type: string
              description: Explanation of the business context, responsibility and accountability for legal compliance
            LegalPenalties:
              type: string
              description: Outline of the possible implications of breaking the law
            LegalGuideline:
              type: string
              description: Guidelines and requirements for following the law
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            LegalAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the legal assessment action
            LegalAssessmentResult:
              type: string
              description: Outcome/result of the legal assessment, this can include remedial actions
    UpdateLegalComplianceAssessmentRequest:
      type: object
      properties:
        LegalComplianceAssessment:
          type: object
          properties:
            LegalAssessmentType:
              type: string
              description: The type of law that is applied by the assessment action
            BusinessUnitReference:
              type: object
              description: The business function or unit assessed if appropriate
            ProductandServiceReference:
              type: object
              description: The associated product/service being assessed if appropriate
            CustomerReference:
              type: object
              description: Reference to the customer assessed if appropriate
            JurisdictionReference:
              type: object
              description: Indication of the legal jurisdiction that applies
            LawReference:
              type: object
              description: Reference to the specific law
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            LegalAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the legal assessment action
    UpdateLegalComplianceAssessmentResponse:
      type: object
      properties:
        LegalComplianceAssessment:
          type: object
          properties:
            LegalAssessmentType:
              type: string
              description: The type of law that is applied by the assessment action
            BusinessUnitReference:
              type: object
              description: The business function or unit assessed if appropriate
            ProductandServiceReference:
              type: object
              description: The associated product/service being assessed if appropriate
            CustomerReference:
              type: object
              description: Reference to the customer assessed if appropriate
            JurisdictionReference:
              type: object
              description: Indication of the legal jurisdiction that applies
            LawReference:
              type: object
              description: Reference to the specific law
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            LegalAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the legal assessment action
    RequestLegalComplianceAssessmentRequest:
      type: object
      properties:
        LegalComplianceAssessment:
          type: object
          properties:
            LegalAssessmentType:
              type: string
              description: The type of law that is applied by the assessment action
            BusinessUnitReference:
              type: object
              description: The business function or unit assessed if appropriate
            ProductandServiceReference:
              type: object
              description: The associated product/service being assessed if appropriate
            CustomerReference:
              type: object
              description: Reference to the customer assessed if appropriate
            JurisdictionReference:
              type: object
              description: Indication of the legal jurisdiction that applies
            LawReference:
              type: object
              description: Reference to the specific law
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            LegalAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the legal assessment action
    RequestLegalComplianceAssessmentResponse:
      type: object
      properties:
        LegalComplianceAssessment:
          type: object
          properties:
            LegalAssessmentType:
              type: string
              description: The type of law that is applied by the assessment action
            BusinessUnitReference:
              type: object
              description: The business function or unit assessed if appropriate
            ProductandServiceReference:
              type: object
              description: The associated product/service being assessed if appropriate
            CustomerReference:
              type: object
              description: Reference to the customer assessed if appropriate
            JurisdictionReference:
              type: object
              description: Indication of the legal jurisdiction that applies
            LawReference:
              type: object
              description: Reference to the specific law
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            LegalAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the legal assessment action
            LegalAssessmentResult:
              type: string
              description: Outcome/result of the legal assessment, this can include remedial actions
  parameters:
    LegalComplianceID:
      name: legalcomplianceId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    EvaluateLegalComplianceAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateLegalComplianceAssessmentRequest'
    UpdateLegalComplianceAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateLegalComplianceAssessmentRequest'
    RequestLegalComplianceAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestLegalComplianceAssessmentRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
