openapi: 3.0.1
info:
  title: Public Reference Data Management
  description: 'Provide structured access to standard ''global'' reference data and definitions associated with market activity such as currency, country and segment identifiers.'
  contact:
    name: BIAN
    url: https://bian.org
  version: '10.1.0'
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/PublicReferenceDataManagement/10.1.0
paths:
  '/PublicReferenceDataManagement/{publicreferencedatamanagementid}/Capture':
    put:
      tags:
        - CR - GlobalStandardSpecification
      summary: CaCR Capture Global Standard Specification activity or event related information
      description: CaCR Capture Global Standard Specification activity or event related information
      operationId: Capture
      parameters:
        - $ref: '#/components/parameters/publicreferencedatamanagementid'
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        '200':
          $ref: '#/components/responses/GlobalStandardSpecification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/PublicReferenceDataManagement/{publicreferencedatamanagementid}/Control':
    put:
      tags:
        - CR - GlobalStandardSpecification
      summary: CoCR Control the processing of Global Standard Specification
      description: CoCR Control the processing of Global Standard Specification
      operationId: Control
      parameters:
        - $ref: '#/components/parameters/publicreferencedatamanagementid'
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        '200':
          $ref: '#/components/responses/GlobalStandardSpecification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/PublicReferenceDataManagement/{publicreferencedatamanagementid}/Exchange':
    put:
      tags:
        - CR - GlobalStandardSpecification
      summary: 'EcCR Accept, verify, etc. aspects of Global Standard Specification processing'
      description: 'EcCR Accept, verify, etc. aspects of Global Standard Specification processing'
      operationId: Exchange
      parameters:
        - $ref: '#/components/parameters/publicreferencedatamanagementid'
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        '200':
          $ref: '#/components/responses/GlobalStandardSpecification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /PublicReferenceDataManagement/Initiate:
    post:
      tags:
        - CR - GlobalStandardSpecification
      summary: InCR Instantiate a new Global Standard Specification
      description: InCR Instantiate a new Global Standard Specification
      operationId: Initiate
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        '200':
          $ref: '#/components/responses/GlobalStandardSpecification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/PublicReferenceDataManagement/{publicreferencedatamanagementid}/Retrieve':
    get:
      tags:
        - CR - GlobalStandardSpecification
      summary: ReCR Retrieve details about any aspect of Global Standard Specification
      description: ReCR Retrieve details about any aspect of Global Standard Specification
      operationId: Retrieve
      parameters:
        - $ref: '#/components/parameters/publicreferencedatamanagementid'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveGlobalStandardSpecificationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/PublicReferenceDataManagement/{publicreferencedatamanagementid}/Request':
    put:
      tags:
        - CR - GlobalStandardSpecification
      summary: RqCR Request manual intervention or a decision with respect to Global Standard Specification
      description: RqCR Request manual intervention or a decision with respect to Global Standard Specification
      operationId: Request
      parameters:
        - $ref: '#/components/parameters/publicreferencedatamanagementid'
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        '200':
          $ref: '#/components/responses/GlobalStandardSpecification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/PublicReferenceDataManagement/{publicreferencedatamanagementid}/Update':
    put:
      tags:
        - CR - GlobalStandardSpecification
      summary: UpCR Update details relating to Global Standard Specification
      description: UpCR Update details relating to Global Standard Specification
      operationId: Update
      parameters:
        - $ref: '#/components/parameters/publicreferencedatamanagementid'
      requestBody:
        $ref: '#/components/requestBodies/GlobalStandardSpecification'
      responses:
        '200':
          $ref: '#/components/responses/GlobalStandardSpecification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/PublicReferenceDataManagement/{publicreferencedatamanagementid}/GlobalReferenceData/{globalreferencedataid}/Initiate':
    post:
      tags:
        - BQ - GlobalReferenceData
      summary: InBQ Instantiate a new Global Reference Data
      description: InBQ Instantiate a new Global Reference Data
      operationId: InitiateGlobalReferenceData
      parameters:
        - $ref: '#/components/parameters/publicreferencedatamanagementid'
        - $ref: '#/components/parameters/globalreferencedataid'
      requestBody:
        $ref: '#/components/requestBodies/GlobalReferenceData'
      responses:
        '200':
          $ref: '#/components/responses/GlobalReferenceData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/PublicReferenceDataManagement/{publicreferencedatamanagementid}/GlobalReferenceData/{globalreferencedataid}/Retrieve':
    get:
      tags:
        - BQ - GlobalReferenceData
      summary: ReBQ Retrieve details about any aspect of Global Reference Data
      description: ReBQ Retrieve details about any aspect of Global Reference Data
      operationId: RetrieveGlobalReferenceData
      parameters:
        - $ref: '#/components/parameters/publicreferencedatamanagementid'
        - $ref: '#/components/parameters/globalreferencedataid'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveGlobalReferenceDataResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    PublicReferenceDataManagementOutcome:
      type: object
      properties:
        PublicReferenceDataManagementTask:
          $ref: '#/components/schemas/object'
        PublicReferenceDataManagementDesign:
          $ref: '#/components/schemas/object'
        PublicReferenceDataManagementWorkProduct:
          $ref: '#/components/schemas/object'
        PublicReferenceDataManagementImpactAnalysis:
          $ref: '#/components/schemas/object'
      description: "The main design elements/views making up the overall specification\n\nExamples: Business Requirements"
    GlobalReferenceData:
      type: object
      properties:
        GlobalReferenceDataPreconditions:
          $ref: '#/components/schemas/object'
        GlobalReferenceDataSpecificationSchedule:
          $ref: '#/components/schemas/object'
        GlobalReferenceDataVersionNumber:
          $ref: '#/components/schemas/object'
        ExternalReferenceData:
          $ref: '#/components/schemas/businessservice'
        ExternalReferenceDataServiceType:
          type: string
          description: Reference to the specific business service type
          format: string
        ExternalReferenceDataServiceDescription:
          $ref: '#/components/schemas/object'
        ExternalReferenceDataServiceInputsandOuputs:
          $ref: '#/components/schemas/object'
        ExternalReferenceDataServiceWorkProduct:
          $ref: '#/components/schemas/object'
        ExternalReferenceDataServiceName:
          $ref: '#/components/schemas/object'
      description: "The main design elements/views making up the overall specification\n\nExamples: Business Requirements"
    GlobalStandardSpecification:
      type: object
      properties:
        GlobalStandardSpecificationParameterType:
          type: string
          description: 'A Classification value that distinguishes between designs according to the type of business services and/or aspect within Global Standard Specification . Eg Product Design, Campaign Design, Risk Model Design etc. '
          format: string
        GlobalStandardSpecificationSelectedOption:
          type: string
          description: A selected optional business service as subject matter of design
          format: string
        GlobalStandardSpecificationDescription:
          type: string
          description: Documentation of Global Standard Specification
          format: string
        GlobalStandardSpecificationVersion:
          type: string
          description: The version of Global Standard Specification
          format: string
        GlobalStandardSpecificationStatus:
          type: string
          description: The status of Global Standard Specification
          format: string
        GlobalStandardSpecificationUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events of Global Standard Specification
          format: string
        GlobalStandardSpecificationFeedback:
          type: string
          description: Information about reactions to a design which is used as a basis for improvement for the Global Standard Specification.
          format: string
        GlobalStandardSpecificationServiceProviderReference:
          $ref: '#/components/schemas/object'
      description: "Create and maintain a design for a procedure, product/service model or other such entity  within Public Reference Data Management. \nExample: Create and maintain product designs and analytical models."
    RetrieveGlobalStandardSpecificationResponse:
      type: object
      properties:
        GlobalStandardSpecification:
          type: object
          properties:
            GlobalStandardSpecificationParameterType:
              type: string
              description: 'A Classification value that distinguishes between designs according to the type of business services and/or aspect within Global Standard Specification . Eg Product Design, Campaign Design, Risk Model Design etc. '
              format: string
            GlobalStandardSpecificationSelectedOption:
              type: string
              description: A selected optional business service as subject matter of design
              format: string
            GlobalStandardSpecificationDescription:
              type: string
              description: Documentation of Global Standard Specification
              format: string
            GlobalStandardSpecificationVersion:
              type: string
              description: The version of Global Standard Specification
              format: string
            GlobalStandardSpecificationStatus:
              type: string
              description: The status of Global Standard Specification
              format: string
            GlobalStandardSpecificationUsageLog:
              type: string
              description: Reference to the log of (usage) ativities/events of Global Standard Specification
              format: string
            GlobalStandardSpecificationFeedback:
              type: string
              description: Information about reactions to a design which is used as a basis for improvement for the Global Standard Specification.
              format: string
            GlobalStandardSpecificationServiceProviderReference:
              $ref: '#/components/schemas/object'
      description: 'Output: ReCR Retrieve details about any aspect of Global Standard Specification'
    RetrieveGlobalReferenceDataResponse:
      type: object
      properties:
        GlobalReferenceData:
          type: object
          properties:
            GlobalReferenceDataPreconditions:
              $ref: '#/components/schemas/object'
            GlobalReferenceDataSpecificationSchedule:
              $ref: '#/components/schemas/object'
            GlobalReferenceDataVersionNumber:
              $ref: '#/components/schemas/object'
            ExternalReferenceData:
              $ref: '#/components/schemas/businessservice'
            ExternalReferenceDataServiceType:
              type: string
              description: Reference to the specific business service type
              format: string
            ExternalReferenceDataServiceDescription:
              $ref: '#/components/schemas/object'
            ExternalReferenceDataServiceInputsandOuputs:
              $ref: '#/components/schemas/object'
            ExternalReferenceDataServiceWorkProduct:
              $ref: '#/components/schemas/object'
            ExternalReferenceDataServiceName:
              $ref: '#/components/schemas/object'
      description: 'Output: ReBQ Retrieve details about any aspect of Global Reference Data'
    object:
      type: object
      properties:
        Object:
          type: string
          description: ''
          format: datatype
    businessservice:
      type: object
      properties:
        BusinessServiceName:
          $ref: '#/components/schemas/name'
        BusinessServiceType:
          $ref: '#/components/schemas/businessservicetypevalues'
        BusinessServiceDescription:
          $ref: '#/components/schemas/text'
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    GlobalStandardSpecification:
      description: GlobalStandardSpecification
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GlobalStandardSpecification'
    RetrieveGlobalStandardSpecificationResponse:
      description: RetrieveGlobalStandardSpecificationResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveGlobalStandardSpecificationResponse'
    GlobalReferenceData:
      description: GlobalReferenceData
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GlobalReferenceData'
    RetrieveGlobalReferenceDataResponse:
      description: RetrieveGlobalReferenceDataResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveGlobalReferenceDataResponse'
  parameters:
    publicreferencedatamanagementid:
      name: publicreferencedatamanagementid
      in: path
      required: true
      style: simple
      schema:
        type: string
    globalreferencedataid:
      name: globalreferencedataid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    GlobalStandardSpecification:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GlobalStandardSpecification'
      required: true
    GlobalReferenceData:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GlobalReferenceData'
      required: true