openapi: 3.0.1
info:
  title: Regulatory Compliance
  description: This service domain provides a service to interpret regulatory requirements, provide guidance and define and implement a portfolio of regulatory compliance tests across all appropriate bank activities
  version: 10.1.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/B154/RegulatoryCompliance/10.1.0
paths:
  /RegulatoryCompliance/Evaluate:
    post:
      tags:
      - CR - RegulatoryComplianceAssessment
      summary: EvCR Start a compliance evaluation assessment
      description: EvCR Start a compliance evaluation assessment
      operationId: Evaluate
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/EvaluateRegulatoryComplianceAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateRegulatoryComplianceAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /RegulatoryCompliance/{regulatorycomplianceId}/Update:
    put:
      tags:
      - CR - RegulatoryComplianceAssessment
      summary: UpCR Update submitted details or content for an on-going compliance assessment
      description: UpCR Update submitted details or content for an on-going compliance assessment
      operationId: Update
      parameters:
      - $ref: '#/components/parameters/RegulatoryComplianceID'
      requestBody:
        $ref: '#/components/requestBodies/UpdateRegulatoryComplianceAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateRegulatoryComplianceAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /RegulatoryCompliance/{regulatorycomplianceId}/Request:
    put:
      tags:
      - CR - RegulatoryComplianceAssessment
      summary: RqCR Request a review or adjudication for an assessment
      description: RqCR Request a review or adjudication for an assessment
      operationId: Request
      parameters:
      - $ref: '#/components/parameters/RegulatoryComplianceID'
      requestBody:
        $ref: '#/components/requestBodies/RequestRegulatoryComplianceAssessmentRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestRegulatoryComplianceAssessmentResponse'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
  /RegulatoryCompliance/{regulatorycomplianceId}/Retrieve:
    get:
      tags:
      - CR - RegulatoryComplianceAssessment
      summary: ReCR Retrieve details and content from an active compliance assessment
      description: ReCR Retrieve details and content from an active compliance assessment
      operationId: Retrieve
      parameters:
      - $ref: '#/components/parameters/RegulatoryComplianceID'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegulatoryComplianceAssessment'
        400:
          $ref: '#/components/responses/BadRequestError'
        401:
          $ref: '#/components/responses/UnauthorizedError'
        403:
          $ref: '#/components/responses/ForbiddenError'
        404:
          $ref: '#/components/responses/NotFoundError'
        429:
          $ref: '#/components/responses/TooManyRequestsError'
        500:
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    RegulatoryComplianceAssessment:
      type: object
      properties:
        RegulatoryAssessmentType:
          type: string
          description: The type and make-up of regulatory tests referenced in the assessment
        BusinessUnitReference:
          type: object
          description: The business function or unit assessed for compliance if appropriate
        ProductandServiceReference:
          type: object
          description: The associated product/service being assessed if appropriate
        CustomerReference:
          type: object
          description: Reference to the customer assessed if appropriate
        RegulatoryAuthorityReference:
          type: object
          description: Indication of the authority pertaining to the applied regulation
        RegulationReference:
          type: object
          description: Reference to the specific regulation
        RegulationDefinition:
          type: string
          description: A definition of the goals/required actions addressed by the regulation
        RegulationComplianceandReportingRequirements:
          type: string
          description: Description of the measurements and reporting required to demonstrate compliance
        RegulationAccountability:
          type: string
          description: Explanation of the business context, responsibility and accountability for compliance
        RegulationPenalties:
          type: string
          description: Outline of the possible implications of non-compliance
        RegulationGuideline:
          type: string
          description: Guidelines and requirements for compliance
        DocumentReference:
          type: object
          description: Reference to any documentation classified/archived as appropriate
        RegulatoryAssessmentWorkProducts:
          type: string
          description: Work documentation, forms and schedules produced and referenced during the assessment
        RegulatoryAssessmentResult:
          type: string
          description: Outcome/result of the assessment, can include remedial actions
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          description: NA
        status:
          type: string
          description: NA
        message:
          type: string
          description: NA
    EvaluateRegulatoryComplianceAssessmentRequest:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          type: object
          properties:
            RegulatoryAssessmentType:
              type: string
              description: The type and make-up of regulatory tests referenced in the assessment
            BusinessUnitReference:
              type: object
              description: The business function or unit assessed for compliance if appropriate
            ProductandServiceReference:
              type: object
              description: The associated product/service being assessed if appropriate
            CustomerReference:
              type: object
              description: Reference to the customer assessed if appropriate
            RegulatoryAuthorityReference:
              type: object
              description: Indication of the authority pertaining to the applied regulation
            RegulationReference:
              type: object
              description: Reference to the specific regulation
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            RegulatoryAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the assessment
    EvaluateRegulatoryComplianceAssessmentResponse:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          type: object
          properties:
            RegulatoryAssessmentType:
              type: string
              description: The type and make-up of regulatory tests referenced in the assessment
            RegulationDefinition:
              type: string
              description: A definition of the goals/required actions addressed by the regulation
            RegulationComplianceandReportingRequirements:
              type: string
              description: Description of the measurements and reporting required to demonstrate compliance
            RegulationAccountability:
              type: string
              description: Explanation of the business context, responsibility and accountability for compliance
            RegulationPenalties:
              type: string
              description: Outline of the possible implications of non-compliance
            RegulationGuideline:
              type: string
              description: Guidelines and requirements for compliance
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            RegulatoryAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the assessment
            RegulatoryAssessmentResult:
              type: string
              description: Outcome/result of the assessment, can include remedial actions
    UpdateRegulatoryComplianceAssessmentRequest:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          type: object
          properties:
            RegulatoryAssessmentType:
              type: string
              description: The type and make-up of regulatory tests referenced in the assessment
            BusinessUnitReference:
              type: object
              description: The business function or unit assessed for compliance if appropriate
            ProductandServiceReference:
              type: object
              description: The associated product/service being assessed if appropriate
            CustomerReference:
              type: object
              description: Reference to the customer assessed if appropriate
            RegulatoryAuthorityReference:
              type: object
              description: Indication of the authority pertaining to the applied regulation
            RegulationReference:
              type: object
              description: Reference to the specific regulation
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            RegulatoryAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the assessment
    UpdateRegulatoryComplianceAssessmentResponse:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          type: object
          properties:
            RegulatoryAssessmentType:
              type: string
              description: The type and make-up of regulatory tests referenced in the assessment
            BusinessUnitReference:
              type: object
              description: The business function or unit assessed for compliance if appropriate
            ProductandServiceReference:
              type: object
              description: The associated product/service being assessed if appropriate
            CustomerReference:
              type: object
              description: Reference to the customer assessed if appropriate
            RegulatoryAuthorityReference:
              type: object
              description: Indication of the authority pertaining to the applied regulation
            RegulationReference:
              type: object
              description: Reference to the specific regulation
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            RegulatoryAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the assessment
    RequestRegulatoryComplianceAssessmentRequest:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          type: object
          properties:
            RegulatoryAssessmentType:
              type: string
              description: The type and make-up of regulatory tests referenced in the assessment
            BusinessUnitReference:
              type: object
              description: The business function or unit assessed for compliance if appropriate
            ProductandServiceReference:
              type: object
              description: The associated product/service being assessed if appropriate
            CustomerReference:
              type: object
              description: Reference to the customer assessed if appropriate
            RegulatoryAuthorityReference:
              type: object
              description: Indication of the authority pertaining to the applied regulation
            RegulationReference:
              type: object
              description: Reference to the specific regulation
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            RegulatoryAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the assessment
    RequestRegulatoryComplianceAssessmentResponse:
      type: object
      properties:
        RegulatoryComplianceAssessment:
          type: object
          properties:
            RegulatoryAssessmentType:
              type: string
              description: The type and make-up of regulatory tests referenced in the assessment
            BusinessUnitReference:
              type: object
              description: The business function or unit assessed for compliance if appropriate
            ProductandServiceReference:
              type: object
              description: The associated product/service being assessed if appropriate
            CustomerReference:
              type: object
              description: Reference to the customer assessed if appropriate
            RegulatoryAuthorityReference:
              type: object
              description: Indication of the authority pertaining to the applied regulation
            RegulationReference:
              type: object
              description: Reference to the specific regulation
            DocumentReference:
              type: object
              description: Reference to any documentation classified/archived as appropriate
            RegulatoryAssessmentWorkProducts:
              type: string
              description: Work documentation, forms and schedules produced and referenced during the assessment
            RegulatoryAssessmentResult:
              type: string
              description: Outcome/result of the assessment, can include remedial actions
  parameters:
    RegulatoryComplianceID:
      name: regulatorycomplianceId
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  requestBodies:
    EvaluateRegulatoryComplianceAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateRegulatoryComplianceAssessmentRequest'
    UpdateRegulatoryComplianceAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateRegulatoryComplianceAssessmentRequest'
    RequestRegulatoryComplianceAssessmentRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestRegulatoryComplianceAssessmentRequest'
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
...
