openapi: 3.0.1
info:
  title: Guideline Compliance
  description: 'This service domain develops and applies a portfolio of guideline compliance tests to confirm adherence to bank and regulator imposed internal procedures. Tests may be made on complete transaction data or a meaningful samples as appropriate to mitigate exposure to non-compliant behaviors. Compliance checks may be in response to a schedule, a specific request as part of normal processing or may be initiated randomly as an oversight activity'
  contact:
    name: BIAN
    url: https://bian.org
  version: 12.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/GuidelineCompliance/12.0.0
paths:
  /GuidelineCompliance/Evaluate:
    post:
      tags:
        - CR - GuidelineComplianceAssessment
      summary: EvCR Start a guideline compliance evaluation assessment
      description: EvCR Start a guideline compliance evaluation assessment
      operationId: Evaluate
      requestBody:
        $ref: '#/components/requestBodies/EvaluateGuidelineComplianceAssessmentRequest'
      responses:
        '200':
          $ref: '#/components/responses/EvaluateGuidelineComplianceAssessmentResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/GuidelineCompliance/{guidelinecomplianceid}/Update':
    put:
      tags:
        - CR - GuidelineComplianceAssessment
      summary: UpCR Update submitted details or content for an on-going guideline compliance assessment
      description: UpCR Update submitted details or content for an on-going guideline compliance assessment
      operationId: Update
      parameters:
        - $ref: '#/components/parameters/guidelinecomplianceid'
      requestBody:
        $ref: '#/components/requestBodies/UpdateGuidelineComplianceAssessmentRequest'
      responses:
        '200':
          $ref: '#/components/responses/UpdateGuidelineComplianceAssessmentResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/GuidelineCompliance/{guidelinecomplianceid}/Retrieve':
    get:
      tags:
        - CR - GuidelineComplianceAssessment
      summary: ReCR Retrieve details and content from an active guideline compliance assessment
      description: ReCR Retrieve details and content from an active guideline compliance assessment
      operationId: Retrieve
      parameters:
        - $ref: '#/components/parameters/guidelinecomplianceid'
      responses:
        '200':
          $ref: '#/components/responses/RetrieveGuidelineComplianceAssessmentResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    GuidelineComplianceAssessment:
      type: object
      properties:
        GuidelineComplianceAssessmentType:
          type: string
          description: The type and make-up of guideline compliance tests referenced in the assessment
          format: string
        BusinessUnitReference:
          type: string
          description: The business function or unit assessed for compliance if appropriate
          format: object
        ProductandServiceReference:
          type: string
          description: The associated product/service being assessed if appropriate
          format: object
        CustomerReference:
          type: string
          description: Reference to the customer assessed if appropriate
          format: object
        DocumentReference:
          type: string
          description: Reference to any documentation classified/archived as appropriate
          format: object
        GuidelineComplianceAssessmentWorkProducts:
          type: string
          description: 'Work documentation, forms and schedules produced and referenced during the assessment'
          format: string
        GuidelineComplianceAssessmentResult:
          type: string
          description: 'Outcome/result of the assessment, can include remedial actions'
          format: string
      description: 'To test or assess an entity, possibly against some formal qualification or certification requirement within Guideline Compliance. '
    EvaluateGuidelineComplianceAssessmentRequest:
      type: object
      properties:
        GuidelineComplianceAssessment:
          type: object
          properties:
            GuidelineComplianceAssessmentType:
              type: string
              description: "\r\n"
              format: string
            BusinessUnitReference:
              type: string
              description: "\r\n"
              format: object
            ProductandServiceReference:
              type: string
              description: "\r\n"
              format: object
            CustomerReference:
              type: string
              description: "\r\n"
              format: object
            DocumentReference:
              type: string
              description: "\r\n"
              format: object
            GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: "\r\n"
              format: string
      description: 'Input: EvCR Start a guideline compliance evaluation assessment'
    EvaluateGuidelineComplianceAssessmentResponse:
      type: object
      properties:
        GuidelineComplianceAssessment:
          type: object
          properties:
            DocumentReference:
              type: string
              description: "\r\n"
              format: object
            GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: "\r\n"
              format: string
            GuidelineComplianceAssessmentResult:
              type: string
              description: "\r\n"
              format: string
      description: 'Output: EvCR Start a guideline compliance evaluation assessment'
    UpdateGuidelineComplianceAssessmentRequest:
      type: object
      properties:
        GuidelineComplianceAssessment:
          type: object
          properties:
            GuidelineComplianceAssessmentType:
              type: string
              description: "\r\n"
              format: string
            BusinessUnitReference:
              type: string
              description: "\r\n"
              format: object
            ProductandServiceReference:
              type: string
              description: "\r\n"
              format: object
            CustomerReference:
              type: string
              description: "\r\n"
              format: object
            DocumentReference:
              type: string
              description: "\r\n"
              format: object
            GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: "\r\n"
              format: string
      description: 'Input: UpCR Update submitted details or content for an on-going guideline compliance assessment'
    UpdateGuidelineComplianceAssessmentResponse:
      type: object
      properties:
        GuidelineComplianceAssessment:
          type: object
          properties:
            GuidelineComplianceAssessmentType:
              type: string
              description: "\r\n"
              format: string
            BusinessUnitReference:
              type: string
              description: "\r\n"
              format: object
            ProductandServiceReference:
              type: string
              description: "\r\n"
              format: object
            CustomerReference:
              type: string
              description: "\r\n"
              format: object
            DocumentReference:
              type: string
              description: "\r\n"
              format: object
            GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: "\r\n"
              format: string
      description: 'Output: UpCR Update submitted details or content for an on-going guideline compliance assessment'
    RetrieveGuidelineComplianceAssessmentResponse:
      type: object
      properties:
        GuidelineComplianceAssessment:
          type: object
          properties:
            GuidelineComplianceAssessmentType:
              type: string
              description: "\r\n"
              format: string
            BusinessUnitReference:
              type: string
              description: "\r\n"
              format: object
            ProductandServiceReference:
              type: string
              description: "\r\n"
              format: object
            CustomerReference:
              type: string
              description: "\r\n"
              format: object
            DocumentReference:
              type: string
              description: "\r\n"
              format: object
            GuidelineComplianceAssessmentWorkProducts:
              type: string
              description: "\r\n"
              format: string
            GuidelineComplianceAssessmentResult:
              type: string
              description: "\r\n"
              format: string
      description: 'Output: ReCR Retrieve details and content from an active guideline compliance assessment'
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    EvaluateGuidelineComplianceAssessmentResponse:
      description: EvaluateGuidelineComplianceAssessmentResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateGuidelineComplianceAssessmentResponse'
    UpdateGuidelineComplianceAssessmentResponse:
      description: UpdateGuidelineComplianceAssessmentResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateGuidelineComplianceAssessmentResponse'
    RetrieveGuidelineComplianceAssessmentResponse:
      description: RetrieveGuidelineComplianceAssessmentResponse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RetrieveGuidelineComplianceAssessmentResponse'
  parameters:
    guidelinecomplianceid:
      name: guidelinecomplianceid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    EvaluateGuidelineComplianceAssessmentRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EvaluateGuidelineComplianceAssessmentRequest'
      required: true
    UpdateGuidelineComplianceAssessmentRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateGuidelineComplianceAssessmentRequest'
      required: true