openapi: 3.0.1
info:
  title: Information Provider Operation
  description: ''
  contact:
    name: BIAN
    url: https://bian.org
  version: 11.0.0
servers:
  - url: https://virtserver.swaggerhub.com/B154/BIAN/InformationProviderOperation/11.0.0
paths:
  '/InformationProviderOperation/{informationprovideroperationid}/Control':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Control Information Feed Operating Session
      description: Control Information Feed Operating Session
      operationId: Control
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Exchange':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Exchange Information Feed Operating Session
      description: Exchange Information Feed Operating Session
      operationId: Exchange
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Execute':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Execute Information Feed Operating Session
      description: Execute Information Feed Operating Session
      operationId: Execute
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /InformationProviderOperation/Initiate:
    post:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Initiate Information Feed Operating Session
      description: Initiate Information Feed Operating Session
      operationId: Initiate
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Notify':
    get:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Notify Information Feed Operating Session
      description: Notify Information Feed Operating Session
      operationId: Notify
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/InformationProviderOperation/{informationprovideroperationid}/Request':
    put:
      tags:
        - CR - InformationFeedOperatingSession
      summary: Request Information Feed Operating Session
      description: Request Information Feed Operating Session
      operationId: Request
      parameters:
        - $ref: '#/components/parameters/informationprovideroperationid'
      requestBody:
        $ref: '#/components/requestBodies/InformationFeedOperatingSession'
      responses:
        '200':
          $ref: '#/components/responses/InformationFeedOperatingSession'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
      description: Status Attributes
    InformationProviderOperationOutcome:
      type: object
      properties:
        InformationProviderOperationIncident:
          type: string
          description: ''
          format: event
        InformationProviderOperationProvision:
          type: string
          description: ''
          format: text
      description: "The collection of operational serivces/functions offered by the operational facility\n\nExamples: messages, capture, routines"
    InformationFeedOperatingSession:
      type: object
      properties:
        InformationFeedOperatingSessionSchedule:
          type: string
          description: Timetable to operate Information Feed Operating Session
          format: schedule
        InformationFeedOperatingSessionStatus:
          type: string
          description: The status of Information Feed Operating Session
          format: status
        InformationFeedOperatingSessionUsageLog:
          type: string
          description: Reference to the log of (usage) ativities/events  of Information Feed Operating Session
          format: log
        InformationFeedOperatingSessionAssociatedPartyReference:
          type: string
          description: Reference to the party who is involved in Information Feed Operating Session
          format: involvedparty
        InformationFeedOperatingSessionServiceProviderReference:
          type: string
          description: Reference to the party who provides the services of Information Feed Operating Session
          format: involvedparty
        InformationFeedOperatingSessionType:
          type: string
          description: A Classification value that distinguishes between the type of operations within Information Feed Operating Session
          format: sessiontype
        InformationFeedOperatingSessionServiceProviderSchedule:
          type: string
          description: The schedule according to which the service provider will operate the Information Feed Operating Session
          format: schedule
        InformationFeedOperatingSessionServiceType:
          type: string
          description: A Classification value that distinguishes between the type of services within Information Feed Operating Session
          format: servicetype
        InformationFeedOperatingSessionServiceConfiguration:
          type: string
          description: The configuration of Information Feed Operating Session
          format: systemconfigurationoption
        InformationFeedOperatingSessionReference:
          type: string
          description: An unique reference to an item or an occurrence of Information Feed Operating Session
          format: session
      description: 'Operate equipment and/or a largely automated facility within Information Provider Operation. '
  responses:
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InformationFeedOperatingSession:
      description: InformationFeedOperatingSession
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InformationFeedOperatingSession'
  parameters:
    informationprovideroperationid:
      name: informationprovideroperationid
      in: path
      required: true
      style: simple
      schema:
        type: string
  requestBodies:
    InformationFeedOperatingSession:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InformationFeedOperatingSession'
      required: true